// Child presentation, progression and flee policy.
(() => {
'use strict';
const BUILD='20261001-child-system-v1', H=1.45, DEFAULT_SCALE=.72, DANGER=12, RETREAT=10;
const PATH={front:'images/characters/human_child/body_front.png',side:'images/characters/human_child/body_side.png',back:'images/characters/human_child/body_back.png'};
const ANCHOR={
 front:{helmet:[.50,.015],main:[.22,.575],off:[.78,.575],shield:[.73,.47]},
 side:{helmet:[.53,.015],main:[.58,.57],off:[.47,.55],shield:[.49,.46]},
 back:{helmet:[.50,.015],main:[.78,.575],off:[.22,.575],shield:[.27,.47]}
};
const GRIP={sword:[.5,.92],dagger:[.5,.92],axe:[.5,.82],spear:[.5,.88],club:[.5,.84],bow:[.5,.5],shield:[.5,.5]};
const ADULT={front:{shirt:[.077,.195,.846,.340],pants:[.077,.535,.846,.470]},side:{shirt:[.212,.195,.576,.340],pants:[.212,.535,.576,.470]},back:{shirt:[.077,.195,.846,.340],pants:[.077,.535,.846,.470]}};
const CHILD={front:{shirt:[.14,.275,.72,.31],pants:[.20,.545,.60,.325]},side:{shirt:[.30,.275,.40,.31],pants:[.34,.545,.32,.325]},back:{shirt:[.14,.275,.72,.31],pants:[.20,.545,.60,.325]}};
const cache=new Map(), trim=new WeakMap();
let drawInstalled=false, progressionInstalled=false;
function isChild(e){return !!e&&(e.appearance?.ageBand==='child'||e.ageBand==='child'||e.isChild===true);}
function isHumanChild(e){return isChild(e)&&e.race==='human'&&!e.customImage;}
function view(f){return f==='up'?'back':(f==='left'||f==='right')?'side':'front';}
function ready(i){return !!i&&((i.complete&&i.naturalWidth>0&&i.naturalHeight>0)||(i.width>0&&i.height>0));}
function image(src){if(cache.has(src))return cache.get(src);const i=window.assetManager?.request?.(src)||null;if(i){cache.set(src,i);window.assetManager?.whenReady?.(src).then(()=>{window.drawMap?.();window.renderEntities?.();}).catch(()=>{});}return i;}
function alpha(i){if(trim.has(i))return trim.get(i);let t=null;try{t=window.suggestSpriteAlphaTrim?.(i,8)||null;}catch(_){}if(!t){const w=i?.naturalWidth||i?.width||1,h=i?.naturalHeight||i?.height||1;t={trimLeft:0,trimTop:0,trimWidth:w,trimHeight:h};}trim.set(i,t);return t;}
function drawFit(ctx,i,b){if(!ready(i))return false;const t=alpha(i);ctx.drawImage(i,t.trimLeft,t.trimTop,t.trimWidth,t.trimHeight,b.left,b.top,b.width,b.height);return true;}
function bounds(e,x,y,z=1,fly=0,v='front'){const hs=window.hexSize||1,zoom=Number.isFinite(z)?z:(window.cameraZoom||1),raw=Number(e.appearance?.heightScale??e.heightScale??DEFAULT_SCALE),m=Number.isFinite(raw)?Math.max(.76,Math.min(1.18,raw/DEFAULT_SCALE)):1,h=H*m*hs*zoom,w=h*(v==='side'?.36:.50),bottom=y+.96*hs*zoom+fly;return {left:x-w/2,top:bottom-h,width:w,height:h};}
function pt(b,a){return {x:b.left+a[0]*b.width,y:b.top+a[1]*b.height};}
function hair(ctx,e,v,b){if(e.equipped?.helmet&&window.equipmentAppearanceSystem?.isSlotVisible?.(e,'helmet')!==false)return;const set=window.DIRECTIONAL_CHARACTER_ASSETS?.human_female?.hair,s=e.hairStyle||'brown_1';let i=set?.[s]?.[v]||set?.brown_1?.[v];if(!ready(i))return;if(e.hairHue!==undefined&&window.getRecoloredCharacterHairSprite)i=window.getRecoloredCharacterHairSprite(i,e.hairHue,e.hairLightMult||1,e.hairSatMult||1)||i;const t=v==='side'?[.27,-.035,.50,.36]:[.12,-.04,.76,.36];drawFit(ctx,i,{left:b.left+t[0]*b.width,top:b.top+t[1]*b.height,width:t[2]*b.width,height:t[3]*b.height});}
function clothes(ctx,e,v,b){if(e.displayClothes===false)return;window.clothingSystem?.migrateLegacyEquipment?.(e);window.clothingSystem?.preloadOutfit?.(e,v);for(const slot of ['pants','shirt']){if(!e.equipped?.[slot])continue;const a=ADULT[v][slot],c=CHILD[v][slot],w=b.width*c[2]/a[2],h=b.height*c[3]/a[3],vb={left:b.left+b.width*c[0]-w*a[0],top:b.top+b.height*c[1]-h*a[1],width:w,height:h};window.clothingSystem?.drawSlot?.(ctx,e,slot,v,vb);}}
function weapon(id){if(!id||window.items?.[id]?.type!=='weapon')return null;const g=window.gameVisuals||{},s=String(id).toLowerCase();if(s.includes('bow'))return [g.bow,'bow',.46];if(s.includes('spear'))return [g.spear,'spear',.50];if(s.includes('axe')||s.includes('pickaxe'))return [g.axe,'axe',.44];if(s.includes('club')||s.includes('chair'))return [g.club,'club',.44];if(s.includes('dagger'))return [g.swordIcon,'dagger',.30];if(s.includes('sword'))return [g.swordIcon,'sword',.44];return null;}
function held(ctx,e,v,b,slot,want){const id=slot==='main'?e.equipped?.weapon:e.equipped?.offhand,item=window.items?.[id];if(!item)return false;let i,k,scale;if(item.type==='shield'){if(want==='weapon')return false;k='shield';scale=.36;const sets=window.SHIELD_VISUAL_ASSETS,set=sets?.[item.shieldVisual]||sets?.round;i=v==='back'?(set?.back||set?.front):set?.front;i=i||window.gameVisuals?.shield;}else{if(want==='shield')return false;const s=weapon(id);if(!s)return false;[i,k,scale]=s;i=window.equipmentAppearanceSystem?.resolveWeaponImage?.(e,id,i,k)||i;}if(!ready(i))return false;const a=pt(b,ANCHOR[v][k==='shield'?'shield':slot]);const gr=GRIP[k]||GRIP.sword;let h=b.height*scale,w=h;if(k==='shield')w=h*(i.naturalWidth||i.width||1)/(i.naturalHeight||i.height||1);if(slot==='off'&&k!=='shield'){ctx.save();ctx.translate(a.x,a.y);ctx.scale(-1,1);ctx.drawImage(i,-gr[0]*w,-gr[1]*h,w,h);ctx.restore();}else ctx.drawImage(i,a.x-gr[0]*w,a.y-gr[1]*h,w,h);return true;}
function helmet(ctx,e,v,b){if(!e.equipped?.helmet||window.equipmentAppearanceSystem?.isSlotVisible?.(e,'helmet')===false)return;let i=v==='back'?window.REAR_HUMAN_EQUIPMENT_ASSETS?.helmet:window.gameVisuals?.nasal_helm;if(!ready(i))return;if(e.goldGear&&window.getGoldTintedSprite)i=window.getGoldTintedSprite(i)||i;const a=pt(b,ANCHOR[v].helmet),t=v==='side'?[-.18,-.02,.36,.23]:[-.22,-.02,.44,.23];drawFit(ctx,i,{left:a.x+t[0]*b.width,top:a.y+t[1]*b.height,width:t[2]*b.width,height:t[3]*b.height});}
function armour(ctx,e,v,b){const id=e.equipped?.armor;if(!id||e.displayArmour===false||window.equipmentAppearanceSystem?.isSlotVisible?.(e,'armor')===false)return;const r=Number(window.items?.[id]?.reduction||0),tier=r>=3?'heavy':r>=2?'medium':'light',set=window.ARMOUR_VISUAL_ASSETS?.[tier];let i=v==='back'?(set?.back||set?.front):set?.front;if(!ready(i))i=tier==='heavy'?window.gameVisuals?.humanHeavy:tier==='medium'?window.gameVisuals?.humanMedium:window.gameVisuals?.humanLight;if(!ready(i))return;if(e.goldGear&&window.getGoldTintedSprite)i=window.getGoldTintedSprite(i)||i;const t=v==='side'?[.24,.255,.52,.66]:[.10,.255,.80,.66];drawFit(ctx,i,{left:b.left+t[0]*b.width,top:b.top+t[1]*b.height,width:t[2]*b.width,height:t[3]*b.height});}
function drawChild(ctx,e,x,y,z=1,fly=0){if(!isHumanChild(e))return false;const f=['up','down','left','right'].includes(e.facing)?e.facing:'down',v=view(f),base=image(PATH[v]);if(!ready(base))return false;const b=bounds(e,x,y,z,fly,v),mirror=f==='left',cx=b.left+b.width/2,shieldBack=v==='back'||f==='right';ctx.save();if(mirror){ctx.translate(cx,0);ctx.scale(-1,1);ctx.translate(-cx,0);}try{if(shieldBack){held(ctx,e,v,b,'off','shield');held(ctx,e,v,b,'main','shield');}if(v==='back'){held(ctx,e,v,b,'main','weapon');held(ctx,e,v,b,'off','weapon');}drawFit(ctx,base,b);clothes(ctx,e,v,b);armour(ctx,e,v,b);if(e.equipped?.helmet)helmet(ctx,e,v,b);else hair(ctx,e,v,b);if(!shieldBack){held(ctx,e,v,b,'off','shield');held(ctx,e,v,b,'main','shield');}if(v!=='back'){held(ctx,e,v,b,'main','weapon');held(ctx,e,v,b,'off','weapon');}}finally{ctx.restore();}return true;}
function installDraw(){if(drawInstalled)return true;const old=window.drawPlayerCharacter;if(typeof old!=='function')return false;if(old.__childSystem){drawInstalled=true;return true;}const fn=function(){if(drawChild(...arguments))return;return old.apply(this,arguments);};fn.__childSystem=true;fn.__previous=old;window.drawPlayerCharacter=fn;drawInstalled=true;return true;}
function normalize(e){if(!isChild(e))return;e.isChild=true;e.appearance=e.appearance||{};e.appearance.ageBand='child';e.classLevels=[];e.classLevelCounts={};e.level=0;e.class=null;e.npcClassPackage=null;}
function installProgression(){const p=window.NPCProgression;if(!p||typeof p.rebuildProgression!=='function')return false;if(p.rebuildProgression.__childSystem){progressionInstalled=true;return true;}const old=p.rebuildProgression,fn=function(e,o={}){const c=isChild(e),out=old.call(this,e,c?{...o,classLevels:[]}:o);if(c)normalize(out);return out;};fn.__childSystem=true;fn.__previous=old;p.rebuildProgression=fn;progressionInstalled=true;return true;}
function passable(h,e){const t=window.getTerrainAt?.(h.q,h.r);if(!t||['Wall','Void','Lava','Water'].includes(t.name))return false;return !(window.entities||[]).some(x=>x!==e&&x.alive&&x.hex?.q===h.q&&x.hex?.r===h.r);}
function threats(e,r=DANGER){return (window.entities||[]).filter(o=>o&&o!==e&&o.alive&&o.hex&&window.distance?.(e.hex,o.hex)<=r&&(o.side==='enemy'||(e.side!=='neutral'&&o.side!==e.side&&o.side!=='neutral')||o.combatDirective?.hostileTo===e.side));}
function retreat(e,ts){if(!e.hex||!ts.length)return e.hex;let cur={...e.hex};for(let n=0;n<RETREAT;n++){const opts=(window.getNeighbors?.(cur.q,cur.r)||[]).filter(h=>passable(h,e));if(!opts.length)break;opts.sort((a,b)=>Math.min(...ts.map(t=>window.distance(b,t.hex)))-Math.min(...ts.map(t=>window.distance(a,t.hex))));cur=opts[0];}return cur;}
function behaviour(e){if(!isChild(e)||!e.alive||!e.hex)return;normalize(e);const ts=threats(e),fight=!!window.isInCombat&&(e.aiState==='combat'||e.wasDirectlyAttacked||ts.length);if(fight){if(e.__childWasNpc===undefined)e.__childWasNpc=!!e.isNPC;e.isNPC=false;e.aiControlled=true;e.aiState='combat';e.combatDirective=e.combatDirective||{};if(e.__childOldHostileTo===undefined)e.__childOldHostileTo=e.combatDirective.hostileTo??null;e.combatDirective.hostileTo='__child_flee__';e.combatDirective.mode='retreat';e.combatDirective.retreatTo=retreat(e,ts.length?ts:threats(e,40));e.__childRetreat=true;return;}if(ts.length)e.destination=retreat(e,ts);if(e.__childRetreat&&!window.isInCombat){e.combatDirective=e.combatDirective||{};e.combatDirective.mode=null;e.combatDirective.retreatTo=null;e.combatDirective.hostileTo=e.__childOldHostileTo??null;delete e.__childOldHostileTo;e.aiState='idle';e.aiControlled=false;if(e.__childWasNpc!==undefined)e.isNPC=e.__childWasNpc;e.__childRetreat=false;}}
function tick(){installDraw();installProgression();for(const e of window.entities||[])behaviour(e);}
Object.values(PATH).forEach(image);
window.ChildSystem={BUILD,isChild,isHumanChild,drawChild,normalize,retreat,behaviour,PATH,ANCHOR};window.__childSystemInstalled=true;tick();setInterval(tick,250);
})();
