// Inventory appearance controls: per-item colour and render visibility.
(() => {
  'use strict';
  const BUILD='20260929-inventory-appearance-v5';let wrapped=false;
  function ensurePicker(){if(window.buildPreciseColorPicker||document.querySelector('script[data-precise-appearance-colour]'))return;const s=document.createElement('script');s.src=`preciseAppearanceColor.js?build=${BUILD}`;s.async=false;s.dataset.preciseAppearanceColour='true';document.head.appendChild(s);}
  function colourControl(label,key,value,onChange){if(window.buildPreciseColorPicker)return window.buildPreciseColorPicker({key,label,hue:value.hue,saturation:value.saturation,value:value.value,compact:true,onChange});const row=document.createElement('label');row.style.cssText='display:grid;grid-template-columns:130px 1fr;gap:8px;align-items:center;margin:5px 0;font-size:.88em;';const t=document.createElement('span');t.textContent=label;const i=document.createElement('input');i.type='range';i.min='0';i.max='359';i.value=String(value.hue);i.oninput=()=>onChange({...value,hue:Number(i.value)});row.append(t,i);return row;}
  function transparencyControl(label,value,onChange){const row=document.createElement('label');row.style.cssText='display:grid;grid-template-columns:130px 1fr 38px;gap:8px;align-items:center;margin:5px 0;font-size:.88em;';const t=document.createElement('span');t.textContent=`${label} transparency`;const i=document.createElement('input');i.type='range';i.min='0';i.max='100';i.step='1';const out=document.createElement('span');out.style.cssText='font-size:.8em;text-align:right;color:#bbb;';const n=Math.round((1-Math.max(0,Math.min(1,Number(value.opacity??1))))*100);i.value=String(n);out.textContent=`${n}%`;i.oninput=()=>{const x=Number(i.value);out.textContent=`${x}%`;onChange({...value,opacity:1-x/100});};row.append(t,i,out);return row;}
  function materialSlider(part,value,onChange,reopen){
    const wrap=document.createElement('div');wrap.style.cssText='border:1px solid #444;border-radius:4px;padding:7px;margin:6px 0;';
    const labels={metal:'Metal',wood:'Wood',leather:'Main leather',trim:'Leather trim'};const label=labels[part]||part;
    const top=document.createElement('label');top.style.cssText='display:flex;gap:6px;align-items:center;font-size:.84em;margin-bottom:5px;';const unlock=document.createElement('input');unlock.type='checkbox';unlock.checked=!!value.unlocked;top.append(unlock,document.createTextNode('Unlock full colour range'));unlock.onchange=()=>{onChange({...value,unlocked:unlock.checked});reopen();};wrap.appendChild(top);
    const row=document.createElement('label');row.style.cssText='display:grid;grid-template-columns:130px 1fr 38px;gap:8px;align-items:center;font-size:.88em;';const t=document.createElement('span'),i=document.createElement('input'),out=document.createElement('span');out.style.cssText='font-size:.8em;text-align:right;color:#bbb;';i.type='range';
    if(part==='metal'&&!value.unlocked){t.textContent='Metallic tone';i.min='0';i.max='100';i.value=String(Math.round(value.value));out.textContent=i.value;i.oninput=()=>{out.textContent=i.value;onChange({...value,value:Number(i.value),hue:210,saturation:8});};}
    else{const earthy=part==='wood'||part==='leather'||part==='trim';t.textContent=`${label} hue`;i.min=value.unlocked?'0':(earthy?'15':'195');i.max=value.unlocked?'359':(earthy?'60':'225');i.value=String(Math.round(value.hue));out.textContent=i.value;i.oninput=()=>{out.textContent=i.value;onChange({...value,hue:Number(i.value)});};}
    row.append(t,i,out);wrap.appendChild(row);wrap.appendChild(transparencyControl(label,value,onChange));return wrap;
  }
  function weaponPartLabel(id,part){const s=String(id||'').toLowerCase();if(part==='metal'){if(s.includes('sword')||s.includes('dagger'))return'Blade';if(s.includes('axe')||s.includes('pickaxe'))return'Head';if(s.includes('spear'))return'Tip';return'Metal';}if(part==='wood'){if(s.includes('sword')||s.includes('dagger')||s.includes('axe')||s.includes('pickaxe'))return'Handle';if(s.includes('spear'))return'Shaft';if(s.includes('bow'))return'Bow';if(s.includes('club'))return'Body';return'Wood';}return part;}
  function weaponMaterialControl(id,part,value,onChange,reopen){
    const label=weaponPartLabel(id,part),wrap=document.createElement('div');wrap.style.cssText='border:1px solid #444;border-radius:4px;padding:7px;margin:6px 0;';
    const heading=document.createElement('div');heading.textContent=label;heading.style.cssText='font-size:.85em;font-weight:bold;margin-bottom:5px;';wrap.appendChild(heading);
    const top=document.createElement('label');top.style.cssText='display:flex;gap:6px;align-items:center;font-size:.84em;margin-bottom:5px;';const unlock=document.createElement('input');unlock.type='checkbox';unlock.checked=!!value.unlocked;top.append(unlock,document.createTextNode('Unlock full colour range'));unlock.onchange=()=>{onChange({...value,opacity:1,unlocked:unlock.checked});reopen();};wrap.appendChild(top);
    if(value.unlocked){wrap.appendChild(colourControl(`${label} colour`,`weapon-${id}-${part}`,value,next=>onChange({...value,...next,opacity:1,unlocked:true})));return wrap;}
    const row=document.createElement('label');row.style.cssText='display:grid;grid-template-columns:130px 1fr 38px;gap:8px;align-items:center;font-size:.88em;';const t=document.createElement('span'),i=document.createElement('input'),out=document.createElement('span');out.style.cssText='font-size:.8em;text-align:right;color:#bbb;';i.type='range';
    if(part==='metal'){t.textContent='Metallic tone';i.min='0';i.max='100';i.value=String(Math.round(value.value));out.textContent=i.value;i.oninput=()=>{out.textContent=i.value;onChange({...value,value:Number(i.value),hue:210,saturation:8,opacity:1});};}
    else{t.textContent=`${label} hue`;i.min='15';i.max='60';i.value=String(Math.max(15,Math.min(60,Math.round(value.hue))));out.textContent=i.value;i.oninput=()=>{out.textContent=i.value;onChange({...value,hue:Number(i.value),opacity:1});};}
    row.append(t,i,out);wrap.appendChild(row);return wrap;
  }
  function fullColourMaterial(part,value,onChange,id){const labels={cloth:'Cloth',clothTrim:'Cloth trim'};const label=labels[part]||part,box=document.createElement('div');box.style.cssText='border:1px solid #444;border-radius:4px;padding:7px;margin:6px 0;';const h=document.createElement('div');h.textContent=label;h.style.cssText='font-size:.85em;font-weight:bold;margin-bottom:4px;';box.appendChild(h);box.appendChild(colourControl('Colour',`armour-${id}-${part}`,value,onChange));box.appendChild(transparencyControl(label,value,onChange));return box;}
  const clothingSpec=id=>window.clothingSystem?.getItemSpec?.(id)||null;
  const weaponParts=id=>window.equipmentAppearanceSystem?.weaponParts?.(id)||[];
  const armourParts=id=>window.equipmentAppearanceSystem?.armourParts?.(id)||[];
  function isColourable(id){const sp=clothingSpec(id);return !!(sp?.layers?.some(p=>p.tint)||weaponParts(id).length||armourParts(id).length);}
  function redraw(p){window.equipmentAppearanceSystem?.redraw?.(p);}
  function openEditor(box,p,id){
    box.querySelector('[data-item-appearance-editor]')?.remove();const name=window.items?.[id]?.name||id,editor=document.createElement('div');editor.dataset.itemAppearanceEditor='true';editor.style.cssText='border-top:1px solid #555;margin-top:8px;padding-top:8px;';const head=document.createElement('div');head.style.cssText='display:flex;justify-content:space-between;align-items:center;';const title=document.createElement('strong');title.textContent=`Colour: ${name}`;const close=document.createElement('button');close.textContent='Close';close.type='button';close.style.cssText='width:auto;padding:4px 8px;font-size:.8em;';close.onclick=()=>editor.remove();head.append(title,close);editor.appendChild(head);
    const sp=clothingSpec(id),ap=armourParts(id);
    if(sp){for(const part of sp.layers){if(!part.tint)continue;const c=window.clothingSystem.getLayerColour(p,id,part),b=document.createElement('div');b.style.cssText='border:1px solid #444;border-radius:4px;padding:6px;margin:6px 0;';if(sp.layers.length>1){const h=document.createElement('div');h.textContent=part.label;h.style.cssText='font-size:.85em;font-weight:bold;margin-bottom:4px;';b.appendChild(h);}b.appendChild(colourControl(sp.layers.length>1?'Colour':`${name} colour`,`clothing-${id}-${part.id}`,c,next=>{window.clothingSystem.setLayerColour(p,id,part.id,next);redraw(p);}));b.appendChild(transparencyControl(sp.layers.length>1?part.label:name,c,next=>{window.clothingSystem.setLayerColour(p,id,part.id,next);redraw(p);}));editor.appendChild(b);}}
    else if(ap.length){for(const part of ap){const c=window.equipmentAppearanceSystem.getArmourMaterial(p,id,part),change=next=>{window.equipmentAppearanceSystem.setArmourMaterial(p,id,part,next);redraw(p);};if(part==='cloth'||part==='clothTrim')editor.appendChild(fullColourMaterial(part,c,change,id));else editor.appendChild(materialSlider(part,c,change,()=>openEditor(box,p,id)));}}
    else{for(const part of weaponParts(id)){const c=window.equipmentAppearanceSystem.getWeaponMaterial(p,id,part);editor.appendChild(weaponMaterialControl(id,part,c,next=>{window.equipmentAppearanceSystem.setWeaponMaterial(p,id,part,next);redraw(p);},()=>openEditor(box,p,id)));}}
    box.appendChild(editor);
  }
  function equippedRows(p){const ea=window.equipmentAppearanceSystem,rows=[];if(!ea)return rows;ea.ensure(p);for(const slot of ea.renderSlots){const id=p.equipped?.[slot];if(id)rows.push({slot,id});}return rows;}
  function inject(){const host=document.getElementById('inventory-content'),p=window.player,ea=window.equipmentAppearanceSystem;if(!host||!p||!ea||host.querySelector('[data-equipment-appearance]'))return;window.clothingSystem?.migrateLegacyEquipment?.(p);ea.ensure(p);const rows=equippedRows(p),box=document.createElement('div');box.dataset.equipmentAppearance='true';box.style.cssText='border:1px solid #555;border-radius:5px;padding:8px;margin:8px 0 12px;';const title=document.createElement('strong');title.textContent='Equipment appearance';box.appendChild(title);const list=document.createElement('div');list.style.cssText='display:flex;flex-direction:column;gap:5px;margin-top:7px;';for(const {slot,id} of rows){const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:minmax(105px,1fr) auto auto;gap:7px;align-items:center;border-bottom:1px solid #3f3f3f;padding:4px 0 7px;';const name=document.createElement('span');name.textContent=`${ea.slotLabels[slot]||slot}: ${window.items?.[id]?.name||id}`;row.appendChild(name);if(isColourable(id)){const colour=document.createElement('button');colour.type='button';colour.textContent='Colour';colour.style.cssText='width:auto;padding:5px 9px;font-size:.8em;';colour.onclick=()=>openEditor(box,p,id);row.appendChild(colour);}else row.appendChild(document.createElement('span'));const vis=document.createElement('label');vis.style.cssText='display:flex;gap:4px;align-items:center;font-size:.8em;white-space:nowrap;';const cb=document.createElement('input');cb.type='checkbox';cb.checked=ea.isSlotVisible(p,slot);cb.onchange=()=>{ea.setSlotVisible(p,slot,cb.checked);redraw(p);};vis.append(cb,document.createTextNode('Visible'));row.appendChild(vis);list.appendChild(row);}box.appendChild(list);const stored=[...new Set(p.inventory||[])].filter(id=>isColourable(id)&&!rows.some(r=>r.id===id));if(stored.length){const h=document.createElement('div');h.textContent='Stored colourable items';h.style.cssText='font-size:.8em;color:#aaa;margin-top:8px;';box.appendChild(h);const r=document.createElement('div');r.style.cssText='display:flex;flex-wrap:wrap;gap:5px;margin-top:4px;';for(const id of stored){const b=document.createElement('button');b.type='button';b.textContent=`Colour ${window.items?.[id]?.name||id}`;b.style.cssText='width:auto;padding:4px 7px;font-size:.76em;';b.onclick=()=>openEditor(box,p,id);r.appendChild(b);}box.appendChild(r);}host.prepend(box);}
  function install(){ensurePicker();if(wrapped||typeof window.showInventoryScreen!=='function')return;const base=window.showInventoryScreen;window.showInventoryScreen=function(){const r=base.apply(this,arguments);inject();return r;};wrapped=true;}
  window.injectClothingColourControls=inject;window.injectEquipmentAppearanceControls=inject;const timer=setInterval(()=>{install();if(wrapped)clearInterval(timer);},50);if(document.readyState==='complete')install();else window.addEventListener('load',install,{once:true});
})();
