// companionQuestChains.js
// Completes the authored personal-quest arcs for Aldric, Mirabel, Fenn, Reyna
// and Alden. Each chapter continues the persistent character arc established
// by the companion's earlier quests instead of resetting their personality.
(() => {
'use strict';
const root=typeof window!=='undefined'?window:globalThis;
const BUILD='20261001-companion-quest-chains-v1';
const now=()=>Number(root.worldSeconds||0), party=()=>Array.isArray(root.party)?root.party:[], quest=id=>(root.questLog||[]).find(q=>q?.id===id)||null;
const companion=name=>party().find((m,i)=>i>0&&m?.name===name)||null;

const CHAPTERS=[
{
 id:'aldric_weight_of_command',previous:'aldric_measure_of_oath',companion:'Ser Aldric Thorne',chapter:3,title:'The Weight of Command',actor:'High Cleric Adelram',arcApi:'aldricMeasureOfOath',arcMethod:'adjustArc',xp:350,
 intro:'The Silver Vigil asks Aldric to command a mixed relief column through Red Ford: junior wardens, civilian wagons and wounded pilgrims. He can protect everyone only by deciding what must be his burden and what must be trusted to other people.',
 actorPrompt:'Ask Adelram about the Silver Vigil’s Red Ford request.',
 actorText:'Adelram passes over Preceptor Garran’s Red Ford plan. One warden must screen the ridge, another must stay with the wagons, and somebody must coordinate the whole movement. “Garran’s note says that if Aldric tries to do all three jobs personally, he will fail at least two,” Adelram says. Aldric looks as if this is a personal accusation.',
 reckoning:'Aldric studies Garran’s route marks. “I know how to stand a post until I fall over. I am less certain I know how to tell someone else: this part is yours, and I will trust you with it.”',
 resolutions:{
  shared_command:{label:'“Lead the column. Give the wardens real responsibility and let them carry it.”',relationship:{approval:9,trust:11,familiarity:5},affinity:{friendship:7,romanticBond:3},arc:{discernment:10,sharedBurden:24},reason:'helped Aldric lead by sharing responsibility instead of hoarding every burden',line:'Aldric assigns the ridge and wagon guard, then keeps himself where he can see both instead of replacing either. When the column reaches safety he looks almost surprised. “Delegation,” he says. “Disturbingly effective.”'},
  take_every_burden:{label:'“If you gave your word to protect them, take the dangerous parts yourself.”',relationship:{approval:4,trust:2,familiarity:4},affinity:{friendship:2},arc:{discernment:-8,sharedBurden:-22},reason:'reinforced Aldric’s instinct to make himself responsible for every danger',line:'Aldric spends the crossing running from ridge to wagons to rear guard until even Garran stops praising his endurance. Everyone arrives. So does Aldric, barely. “It worked,” he says, “which is not quite the same as saying it was wise.”'},
  refuse_command:{label:'“You do not have to turn every useful skill into another obligation.”',relationship:{approval:2,trust:7,familiarity:5},affinity:{friendship:4,romanticBond:1},arc:{discernment:12,sharedBurden:4},reason:'helped Aldric distinguish being capable from being endlessly obligated',line:'Aldric declines the command but helps Garran build a workable rota. “I used to think refusing a burden meant abandoning someone. Perhaps sometimes it means leaving room for another person to become capable.”'},
  companion_decides:{label:'“You know what your vows mean now. You decide.”',relationship:{approval:6,trust:12,familiarity:6},affinity:{friendship:8,romanticBond:3},reason:'trusted Aldric to decide what responsible command required'}
 },
 selfDecision:s=>Number(s?.sharedBurden||0)>=0?'shared_command':'take_every_burden',personality:[['duty',1],['burden',2]]
},
{
 id:'mirabel_borrowed_voice',previous:'mirabel_unquiet_concordance',companion:'Mirabel Quill',chapter:2,title:'The Borrowed Voice',actor:'Court Wizard Thessaly',arcApi:'mirabelUnquietConcordance',arcMethod:'applyArcChange',xp:300,
 intro:'Thessaly has a dead courier’s damaged message-stone. The Concordance technique could recover a magical echo of the courier’s final minutes. Mirabel wants to know whether an echo can be useful evidence without quietly being treated as a dead person forced to testify.',
 actorPrompt:'Ask Thessaly to show Mirabel the damaged message-stone.',
 actorText:'Thessaly sets the cracked stone between warding rings. A faint voice catches and vanishes: half a word, a breath, the scrape of boots. “Enough pattern remains to reconstruct more,” she says. “The question is how much more you are willing to manufacture from incomplete evidence.” Mirabel stops reaching for her notebook.',
 reckoning:'Mirabel turns the stone over in both hands. “We can extract only what the echo actually contains. Or we can interpolate until it sounds like a person again. The second option would tell us more. That is precisely why I no longer entirely trust it.”',
 resolutions:{
  limited_testimony:{label:'“Recover only what is actually present. Mark every uncertainty.”',relationship:{approval:8,trust:11,familiarity:5},affinity:{friendship:7,romanticBond:3},arc:{restraint:20,rootedness:5},reason:'helped Mirabel use dangerous scholarship without pretending uncertainty away',line:'They recover fragments: a place-name, a crest, the courier’s fear. Mirabel writes every gap into the transcript instead of filling it. “Less satisfying,” she says. “Much more honest.”'},
  full_reconstruction:{label:'“Reconstruct as much as you can. Better an imperfect answer than none.”',relationship:{approval:9,trust:3,familiarity:4},affinity:{friendship:5,attraction:3},arc:{restraint:-22,rootedness:1},reason:'encouraged Mirabel to push echo reconstruction beyond what could be cleanly verified',line:'For several minutes the room contains something eerily like a living voice. It gives them a lead. Later, Mirabel stares at the transcript. “Useful. And I can no longer tell which sentence belonged to the courier and which belonged to us.”'},
  refuse_method:{label:'“A dead person should not become a tool because the magic makes it possible.”',relationship:{approval:-2,trust:8,familiarity:5},affinity:{friendship:4,romanticBond:1},arc:{restraint:24,rootedness:4},reason:'drew a hard ethical boundary around reconstructing a dead person from a magical echo',line:'Mirabel closes the warding ring herself. “I dislike losing an answer. I dislike even more that I understand the objection.” She copies the failure modes instead of the voice.'},
  companion_decides:{label:'“It is your field and your responsibility. You decide the limit.”',relationship:{approval:7,trust:12,familiarity:6},affinity:{friendship:8,romanticBond:3},reason:'trusted Mirabel to set her own ethical limit on the echo technique'}
 },
 selfDecision:s=>Number(s?.restraint||0)>=0?'limited_testimony':'full_reconstruction',personality:[['curiosity',1]]
},
{
 id:'mirabel_place_for_dangerous_books',previous:'mirabel_borrowed_voice',companion:'Mirabel Quill',chapter:3,title:'A Place for Dangerous Books',actor:'Court Wizard Thessaly',arcApi:'mirabelUnquietConcordance',arcMethod:'applyArcChange',xp:350,
 intro:'Thessaly offers Mirabel a permanent hand in the restricted archive. It is the work she always wanted, except that accepting it means choosing responsibility to a place and to people instead of remaining free to leave whenever things become complicated.',
 actorPrompt:'Ask Thessaly what she is actually offering Mirabel.',
 actorText:'Thessaly is precise: Mirabel would catalogue dangerous work, decide access cases with other scholars, train successors and still travel when research requires it. “But you would be answerable to people here,” Thessaly says. “That is the part clever wanderers usually find frightening.”',
 reckoning:'Mirabel leans against the archive door. “I always thought freedom meant keeping my bags light enough to leave. Annoyingly, this place is offering me work worth coming back to.”',
 resolutions:{
  accept_curatorship:{label:'“Take the post. Choosing a place is not the same as being trapped by it.”',relationship:{approval:7,trust:9,familiarity:7},affinity:{friendship:7,romanticBond:4},arc:{restraint:12,rootedness:28},reason:'encouraged Mirabel to choose a lasting responsibility to Silverhart’s dangerous archive',line:'Mirabel signs the appointment, then immediately adds a travel clause in the margin. “Rooted,” she says experimentally. “With loopholes.”'},
  shared_archive:{label:'“Build a network. Make responsibility shared instead of tying it to one keeper.”',relationship:{approval:10,trust:12,familiarity:7},affinity:{friendship:9,romanticBond:4},arc:{restraint:18,rootedness:18},reason:'helped Mirabel turn dangerous knowledge into a shared institution rather than a private possession',line:'Mirabel proposes three custodians, travelling copies with access logs, and mandatory dissent notes beside every restricted theorem. Thessaly reads the plan twice. “I hate how much administration this contains.” Mirabel beams. “Growth.”'},
  keep_wandering:{label:'“You can care about the archive without making it your home.”',relationship:{approval:5,trust:7,familiarity:6},affinity:{friendship:6,romanticBond:2},arc:{restraint:3,rootedness:-18},reason:'affirmed Mirabel’s choice to remain itinerant while keeping ties to the archive',line:'Mirabel refuses the chair but agrees to correspond and return discoveries under seal. “I am not fleeing. I am leaving and intending to come back. Apparently those are different.”'},
  companion_decides:{label:'“You know what leaving and staying cost you now. Choose.”',relationship:{approval:6,trust:13,familiarity:8},affinity:{friendship:9,romanticBond:5},reason:'trusted Mirabel to choose her own relationship to scholarship, responsibility and home'}
 },
 selfDecision:s=>Number(s?.rootedness||0)>=30?'accept_curatorship':(Number(s?.rootedness||0)>=0||Number(s?.restraint||0)>=15?'shared_archive':'keep_wandering'),personality:[['roots',2],['curiosity',1]]
},
{
 id:'fenn_fire_in_understory',previous:'fenn_living_boundary',companion:'Fenn Oakheart',chapter:2,title:'Fire in the Understory',actor:'Elder Nessa Wren',arcApi:'fennLivingBoundary',arcMethod:'applyArcChange',xp:300,
 intro:'A dry year has packed Emberwood’s understory with deadfall. Nessa fears a summer crown fire but the grove’s old rule forbids deliberate burning. Fenn has to decide whether stewardship means preserving the rule, changing the land deliberately, or finding a slower compromise.',
 actorPrompt:'Ask Nessa why the grove forbids a controlled burn.',
 actorText:'Nessa does not call the old rule sacred. It was written after a careless charcoal burn killed a stand of ancient oaks. “Fire is a tool that believes it is a master,” she says. “The rule exists because people overestimate their control.” Fenn looks into the dry fern. “And doing nothing is also a decision about fire.”',
 reckoning:'Fenn has marked three patches where a cool mosaic burn could break the fuel line without crossing the stream. “I can obey the rule. I can break it carefully. Or we can spend weeks clearing by hand and pretend labour has no cost either.”',
 resolutions:{
  mosaic_burn:{label:'“Use the cool mosaic burn. Manage the risk instead of pretending intervention is unnatural.”',relationship:{approval:9,trust:10,familiarity:5},affinity:{friendship:7,romanticBond:2},arc:{stewardship:22,independence:16},reason:'supported Fenn in actively managing the grove while owning the ecological risk',line:'The burn moves slowly under damp dawn air, leaving black islands between untouched green. Fenn watches until the last edge is cold. “Not untouched,” he says. “Not ruined either.”'},
  obey_rule:{label:'“The grove has survived by respecting limits. Do not burn it deliberately.”',relationship:{approval:3,trust:5,familiarity:4},affinity:{friendship:3},arc:{stewardship:-16,independence:-16},reason:'reinforced the grove’s traditional rule against deliberate intervention',line:'Fenn accepts Nessa’s rule and organises fire watches instead. “Maybe caution is wisdom. I just hope we are not calling fear by the nicer name.”'},
  hand_clear:{label:'“Clear the worst fuel by hand. Slower, but it buys safety without the burn.”',relationship:{approval:7,trust:8,familiarity:5},affinity:{friendship:6,romanticBond:1},arc:{stewardship:10,independence:7},reason:'helped Fenn find a labour-intensive compromise between intervention and restraint',line:'It takes days and everybody hates the third day. By the end, the driest corridor is broken and the grove remains unburned. Fenn flexes blistered hands. “Compromise is apparently very physical.”'},
  companion_decides:{label:'“You can hear Nessa without borrowing her judgement. Decide.”',relationship:{approval:7,trust:12,familiarity:6},affinity:{friendship:8,romanticBond:3},reason:'trusted Fenn to make and own his own stewardship decision'}
 },
 selfDecision:s=>Number(s?.stewardship||0)>=5&&Number(s?.independence||0)>=0?'mosaic_burn':'hand_clear',personality:[['stewardship',2],['independence',1]]
},
{
 id:'fenn_groves_answer',previous:'fenn_fire_in_understory',companion:'Fenn Oakheart',chapter:3,title:"The Grove's Answer",actor:'Elder Nessa Wren',arcApi:'fennLivingBoundary',arcMethod:'applyArcChange',xp:350,
 intro:'Emberwood’s elders ask Fenn to become one of the grove’s recognised voices. They want the judgement he learned on the road, but some expect him to fold that judgement back into the old doctrine. The invitation forces him to decide whether independence requires leaving or can survive belonging.',
 actorPrompt:'Ask Nessa what becoming a voice of the grove would require.',
 actorText:'Nessa offers no hidden oath. A grove voice mediates disputes, teaches apprentices and speaks for Emberwood beyond its trees. “You would owe us honesty, not obedience,” she says. Then, more carefully, “Though some elders will expect the old answers from you.” Fenn laughs. “There it is.”',
 reckoning:'Fenn turns an acorn between his fingers. “I left because I needed to know which thoughts were mine. Going back would be easier now. That makes it more dangerous, not less.”',
 resolutions:{
  return_traditional:{label:'“Return. Traditions can hold you without owning every answer.”',relationship:{approval:5,trust:7,familiarity:7},affinity:{friendship:6,romanticBond:2},arc:{stewardship:-4,independence:-14},reason:'encouraged Fenn to return to the grove within its existing traditions',line:'Fenn accepts the staff of office without trying to redesign it. “I can come home without pretending I never left,” he says. “I think.”'},
  changed_charter:{label:'“Accept, but make the role explicitly yours: people and managed landscapes belong in the grove’s ethic too.”',relationship:{approval:10,trust:12,familiarity:7},affinity:{friendship:9,romanticBond:4},arc:{stewardship:18,independence:24},reason:'helped Fenn belong to the grove without surrendering the judgement he developed beyond it',line:'Fenn accepts after Nessa agrees that dissent belongs in the role, not outside it. “That sounds less like coming back,” he says, smiling, “and more like bringing the road home.”'},
  remain_outside:{label:'“Keep your ties, but do not take an office. You do not owe the grove your adulthood.”',relationship:{approval:6,trust:9,familiarity:6},affinity:{friendship:7,romanticBond:3},arc:{stewardship:5,independence:18},reason:'supported Fenn in remaining connected to Emberwood without returning to its authority',line:'Fenn refuses the staff and offers to return as teacher, helper and nuisance. Nessa calls that predictable. He looks pleased.'},
  companion_decides:{label:'“This is your home and your voice. Choose what relationship they have.”',relationship:{approval:7,trust:13,familiarity:8},affinity:{friendship:9,romanticBond:4},reason:'trusted Fenn to decide whether belonging and independence could coexist'}
 },
 selfDecision:s=>Number(s?.independence||0)>=20?'changed_charter':(Number(s?.independence||0)<=-20?'return_traditional':'remain_outside'),personality:[['independence',2],['stewardship',1]]
},
{
 id:'reyna_shared_watch',previous:'reyna_empty_blind',companion:'Reyna Fletcher',chapter:2,title:'The Shared Watch',actor:'Commander Hart',arcApi:'reynaEmptyBlind',arcMethod:'applyArcChange',xp:300,
 intro:'Northwatch needs a scout screen rebuilt after the route leaks. Hart asks Reyna to coordinate soldiers, civilian trackers and whoever survived the Tamsin affair. Reyna can solve the immediate problem alone; the harder task is creating a watch that still works when she is not personally in every blind.',
 actorPrompt:'Ask Hart what she needs from Reyna’s scouts.',
 actorText:'Hart wants overlapping routes, paired reports and a rule that no tracker disappears without somebody noticing by nightfall. “I can order soldiers to use it,” she says. “I cannot make independent hunters trust the system.” Reyna mutters, “Systems have not exactly distinguished themselves.”',
 reckoning:'Reyna has three route plans. One puts her on the dangerous centre line. One pairs every scout and shares the map. One keeps the civilian network outside Northwatch entirely. “All three work,” she says. “They just answer different questions about who gets trusted.”',
 resolutions:{
  joint_watch:{label:'“Build the shared watch. Pair people, share maps and make everyone responsible for noticing who is missing.”',relationship:{approval:9,trust:11,familiarity:5},affinity:{friendship:7,romanticBond:3},arc:{interdependence:24,institutionalTrust:12},reason:'helped Reyna build a scouting system based on deliberate mutual reliance',line:'The first patrol comes back late, muddy and complete. Reyna checks each name once, then stops checking. “Horrible,” she says. “I delegated anxiety.”'},
  reyna_centre:{label:'“Take the centre route yourself. If it fails, at least the risk is yours.”',relationship:{approval:5,trust:3,familiarity:4},affinity:{friendship:3},arc:{interdependence:-20,institutionalTrust:-4},reason:'reinforced Reyna’s belief that the safest system is still herself carrying the critical risk',line:'Reyna’s route works because Reyna makes it work. At the end she is exhausted and everyone else still waits for her judgement. “Efficient,” she says. Neither of you believes the word.'},
  private_network:{label:'“Keep the trackers independent. Cooperate with Hart, but do not put them inside the garrison system.”',relationship:{approval:7,trust:8,familiarity:5},affinity:{friendship:6,romanticBond:2},arc:{interdependence:10,institutionalTrust:-16},reason:'helped Reyna rely on people while keeping the scouting network institutionally independent',line:'Reyna builds a civilian relay that hands Northwatch information without handing it ownership. “Trust people,” she says. “Audit institutions. I can live with that.”'},
  companion_decides:{label:'“You know these roads and these people. Build the watch you would actually trust.”',relationship:{approval:7,trust:13,familiarity:6},affinity:{friendship:8,romanticBond:3},reason:'trusted Reyna to decide what kind of reliance she could live with'}
 },
 selfDecision:s=>Number(s?.interdependence||0)>=10&&Number(s?.institutionalTrust||0)>=0?'joint_watch':(Number(s?.interdependence||0)>=0?'private_network':'reyna_centre'),personality:[['trust',2]]
},
{
 id:'reyna_rangers_writ',previous:'reyna_shared_watch',companion:'Reyna Fletcher',chapter:3,title:"The Ranger's Writ",actor:'Commander Hart',arcApi:'reynaEmptyBlind',arcMethod:'applyArcChange',xp:350,
 intro:'Hart has convinced the Crown to authorise a frontier ranger charter: civilian scouts gain legal protection, pay and a voice in patrol planning, but somebody must sign for the corps and answer when it fails. Hart offers that role to Reyna.',
 actorPrompt:'Ask Hart what powers and obligations the ranger writ actually creates.',
 actorText:'The writ gives rangers the right to refuse suicidal routes, requires written reasons for command overrides, protects coerced scouts from automatic treason charges, and puts complaints before a mixed military-civilian board. It also names a chief ranger who must sign the reports. Hart taps the blank. “Accountability cuts both ways.”',
 reckoning:'Reyna reads the blank signature line twice. “I spent years avoiding organisations because I knew exactly how they fail people. This one contains several paragraphs written because I was annoying about how they fail people.”',
 resolutions:{
  take_writ:{label:'“Sign it. If institutions can be changed, somebody has to inhabit the changed version.”',relationship:{approval:8,trust:10,familiarity:7},affinity:{friendship:8,romanticBond:4},arc:{interdependence:14,institutionalTrust:26},reason:'encouraged Reyna to lead an accountable frontier institution rather than remain outside it',line:'Reyna signs, then makes Hart initial two amended clauses. “If I become unbearable with paperwork,” she says, “remember this was your idea.”'},
  distributed_charter:{label:'“Create the corps, but do not make one chief indispensable. Use an elected rotating lead.”',relationship:{approval:10,trust:12,familiarity:7},affinity:{friendship:9,romanticBond:4},arc:{interdependence:24,institutionalTrust:16},reason:'helped Reyna create an accountable ranger corps that does not depend on one heroic individual',line:'The final writ has three rotating signatures and an automatic review after every season. Hart sighs at the extra clauses. Reyna smiles. “Now it might survive me.”'},
  reject_writ:{label:'“Keep the network outside the Crown. Legal recognition is still a leash.”',relationship:{approval:5,trust:7,familiarity:6},affinity:{friendship:6,romanticBond:2},arc:{interdependence:5,institutionalTrust:-22},reason:'supported Reyna in keeping frontier scouts independent of Crown command',line:'Reyna returns the unsigned writ but keeps the reporting protocol. “Useful ideas do not become bad because they came on official paper. The paper can stay with Hart.”'},
  companion_decides:{label:'“You have spent enough time reacting to institutions. Decide what you want one to be.”',relationship:{approval:7,trust:14,familiarity:8},affinity:{friendship:9,romanticBond:5},reason:'trusted Reyna to choose whether formal institutions deserved her participation'}
 },
 selfDecision:s=>Number(s?.institutionalTrust||0)>=20?(Number(s?.interdependence||0)>=20?'distributed_charter':'take_writ'):(Number(s?.institutionalTrust||0)>=0&&Number(s?.interdependence||0)>=10?'distributed_charter':'reject_writ'),personality:[['justice',1],['trust',2]]
},
{
 id:'alden_missing_sixth',previous:'alden_uncounted',companion:'Brother Alden',chapter:2,title:'The Missing Sixth',actor:'High Cleric Adelram',arcApi:'aldenUncounted',arcMethod:'applyArcChange',xp:300,
 intro:'The cathedral finds the road clerk who closed the missing-body transfer. A torn burial token and a family mark finally give the sixth dead person a name: Tarin Pell. The same evidence suggests the body was deliberately diverted by people buying remains for necromantic work.',
 actorPrompt:'Ask Adelram what the cathedral found about the sixth body.',
 actorText:'Adelram produces a mended wooden token: TARIN PELL, carter, East Mere road. The road clerk remembers a false undertaker collecting the body with forged cathedral papers. “We can restore the name,” Adelram says. “Finding what became of the remains may be uglier.” Alden takes the token as though it weighs more than wood.',
 reckoning:'Alden has a name now and a probable trail into the corpse trade. “I began this because six people were reduced to a number. One of them has become a person again. That makes walking away harder, not easier.”',
 resolutions:{
  return_and_name:{label:'“Restore Tarin’s name first. Bring the family the truth and keep pursuing the thieves through lawful records.”',relationship:{approval:9,trust:11,familiarity:6},affinity:{friendship:8,romanticBond:2},arc:{engagement:18,particularity:24},reason:'helped Alden put Tarin Pell’s personhood before the abstraction of the wider investigation',line:'Alden writes Tarin Pell into the cathedral register in his own hand before copying the forged-paper trail. “The network matters. But it does not get to swallow the person who led us to it.”'},
  pursue_network:{label:'“Use the lead immediately. If the corpse trade continues, there will be more Tarins.”',relationship:{approval:5,trust:6,familiarity:5},affinity:{friendship:5},arc:{engagement:24,particularity:5},reason:'pushed Alden toward active pursuit of the corpse-taking network over immediate memorial work',line:'Alden hands the token to Adelram for safekeeping and starts mapping the forged transfers. “The name waits one more day,” he says, troubled but moving. “The living do not.”'},
  close_record:{label:'“Restore the name and stop there. You do not have to chase every horror attached to it.”',relationship:{approval:3,trust:7,familiarity:6},affinity:{friendship:5,romanticBond:1},arc:{engagement:-16,particularity:18},reason:'supported Alden in honouring Tarin Pell while refusing to make every discovered harm his personal duty',line:'Alden restores the name and gives the lead to the cathedral watch. “There is humility in admitting another person may carry the next part. I am trying to believe that.”'},
  companion_decides:{label:'“You know why this matters to you now. Decide how far you follow it.”',relationship:{approval:7,trust:13,familiarity:7},affinity:{friendship:9,romanticBond:3},reason:'trusted Alden to decide how compassion should divide itself between one person and a wider harm'}
 },
 selfDecision:s=>Number(s?.particularity||0)>=10?'return_and_name':(Number(s?.engagement||0)>=10?'pursue_network':'close_record'),personality:[['dignity',2],['engagement',1]]
},
{
 id:'alden_rule_for_living',previous:'alden_missing_sixth',companion:'Brother Alden',chapter:3,title:'A Rule for the Living',actor:'High Cleric Adelram',arcApi:'aldenUncounted',arcMethod:'applyArcChange',xp:350,
 intro:'The Grand Cathedral wants a permanent ministry for unidentified dead, missing burials and families lost between military and civil records. Adelram asks Alden to shape it. The work would turn his new convictions into an institution, but it would also bind him to exactly the worldly attachments he once treated with suspicion.',
 actorPrompt:'Ask Adelram what he expects from Alden.',
 actorText:'Adelram wants a rule, not a saint: a rotating team that checks names, burial transfers and family notices, with enough independence to embarrass armies and churches alike. “I am asking you to design it,” he says. “I am not asking you to become its permanent martyr.” Alden smiles despite himself.',
 reckoning:'Alden has drafted three versions. One makes him the first permanent keeper. One creates a rotating ministry. One records the reforms and leaves the work to others. “Detachment used to mean keeping the world from fastening itself to me. I am beginning to think compassion is partly choosing what may fasten.”',
 resolutions:{
  take_office:{label:'“Take the office. Some bonds are worth accepting deliberately.”',relationship:{approval:8,trust:10,familiarity:8},affinity:{friendship:8,romanticBond:4},arc:{engagement:26,particularity:18},reason:'encouraged Alden to accept an enduring worldly responsibility for people who might otherwise disappear from record',line:'Alden accepts the first term as keeper of names. “A title is not enlightenment. But perhaps it can be a useful filing system for compassion.”'},
  rotating_ministry:{label:'“Build the ministry so nobody has to become indispensable, including you.”',relationship:{approval:10,trust:12,familiarity:8},affinity:{friendship:9,romanticBond:4},arc:{engagement:20,particularity:22},reason:'helped Alden turn personal compassion into a shared practice rather than another solitary burden',line:'Alden writes rotation, review and handover into the first page. “Care that only works while one good person refuses to rest is badly designed,” he says.'},
  return_contemplation:{label:'“Write the rule, then let others carry it. Your path does not have to become an office.”',relationship:{approval:5,trust:9,familiarity:7},affinity:{friendship:7,romanticBond:2},arc:{engagement:-8,particularity:10},reason:'supported Alden in preserving contemplative distance while leaving a practical institution behind',line:'Alden hands Adelram the finished rule and keeps no title. “Leaving is different when you have first made sure somebody else knows what must continue.”'},
  companion_decides:{label:'“You are allowed to choose attachments now. That includes choosing their limits.”',relationship:{approval:7,trust:14,familiarity:9},affinity:{friendship:10,romanticBond:5},reason:'trusted Alden to decide what a compassionate life should ask of him'}
 },
 selfDecision:s=>Number(s?.engagement||0)>=25&&Number(s?.particularity||0)>=10?'take_office':(Number(s?.engagement||0)>=5||Number(s?.particularity||0)>=15?'rotating_ministry':'return_contemplation'),personality:[['engagement',2],['dignity',1]]
}
];

const BY_ID=new Map(CHAPTERS.map(ch=>[ch.id,ch])), BY_COMPANION=new Map();
for(const ch of CHAPTERS){const list=BY_COMPANION.get(ch.companion)||[];list.push(ch);BY_COMPANION.set(ch.companion,list);ch.actorAliases ||= [ch.actor];}
function arcState(ch){const api=root[ch.arcApi];if(typeof api?.getArcState==='function')return api.getArcState();if(typeof api?.ensureArc==='function')return api.ensureArc();return null;}
function applyArc(ch,key,deltas,reason){const api=root[ch.arcApi],fn=api?.[ch.arcMethod];return typeof fn==='function'?fn.call(api,`quest_chain:${ch.id}:${key}`,deltas||{},reason||key):null;}
function canStart(chOrId){const ch=typeof chOrId==='string'?BY_ID.get(chOrId):chOrId;if(!ch||!companion(ch.companion))return false;const prev=quest(ch.previous);if(prev?.status!=='completed')return false;if(ch.chapter>=3&&Number.isFinite(Number(prev.completedAt))&&now()-Number(prev.completedAt)<43200)return false;return true;}
function ensureQuest(chOrId,{announce=true}={}){const ch=typeof chOrId==='string'?BY_ID.get(chOrId):chOrId;if(!ch||!canStart(ch))return null;root.questLog ||= [];let q=quest(ch.id);if(!q){q={id:ch.id,title:ch.title,giver:ch.companion,status:'active',chapter:ch.chapter,stage:'consult',resolution:null,consulted:false,offeredAt:now(),description:`${ch.intro} Speak with ${ch.actor}.`};root.questLog.push(q);if(announce)root.showMessage?.(`Companion quest added: ${ch.title}.`);}return q;}
function start(chOrId){const ch=typeof chOrId==='string'?BY_ID.get(chOrId):chOrId,c=ch&&companion(ch.companion),q=ch&&ensureQuest(ch);if(!ch||!c||!q)return false;q.introSeen=true;root.noteCompanionConversation?.(c,`${ch.id}:opened`,3);root.showDialogue?.(c,ch.intro,[{label:`“We should speak with ${ch.actor}.”`,action:()=>{}},{label:'“What do you want from this?”',action:()=>root.showDialogue?.(c,ch.reckoning,[{label:'We will see it through.',action:()=>{}}])}]);return true;}
function consult(chOrId,npc=null){const ch=typeof chOrId==='string'?BY_ID.get(chOrId):chOrId,q=ch&&ensureQuest(ch,{announce:false});if(!ch||!q||q.status!=='active')return false;q.consulted=true;q.stage='reckoning';q.consultedAt=now();q.description=`${ch.actor} has given you the missing context. Talk to ${ch.companion} and decide what comes next.`;root.showDialogue?.(npc||companion(ch.companion),ch.actorText,[{label:`Talk this through with ${ch.companion}.`,action:()=>{}}]);return true;}
function effectiveResolution(ch,requested){if(requested!=='companion_decides')return requested;const chosen=ch.selfDecision?.(arcState(ch));return ch.resolutions[chosen]?chosen:Object.keys(ch.resolutions).find(k=>k!=='companion_decides');}
function pronoun(name){return /Aldric|Alden|Fenn/.test(name)?'himself':'herself';}
function complete(chOrId,requested){const ch=typeof chOrId==='string'?BY_ID.get(chOrId):chOrId,c=ch&&companion(ch.companion),q=ch&&quest(ch.id);if(!ch||!c||!q||q.status!=='active'||!q.consulted)return false;const base=ch.resolutions[requested];if(!base)return false;const effective=effectiveResolution(ch,requested),effect=ch.resolutions[effective]||base,reward=requested==='companion_decides'?base:effect;q.status='completed';q.stage='completed';q.resolution=requested;q.effectiveResolution=effective;q.completedAt=now();q.description=`${ch.title} is complete. ${effect.reason}.`;root.adjustCompanionRelationship?.(c,reward.relationship||{},reward.reason||ch.title);root.adjustCompanionAffinity?.(c,reward.affinity||{},reward.reason||ch.title,`${ch.id}:${requested}`);applyArc(ch,effective,effect.arc,effect.reason);for(const [trait,amount] of ch.personality||[])root.learnCompanionPersonality?.(ch.companion,trait,amount||1,`quest:${ch.id}`);root.gainExp?.(Number(ch.xp||250));root.showMessage?.(`Companion quest complete: ${ch.title}.`);const extra=requested==='companion_decides'?`\n\nGiven the choice, ${ch.companion} chooses for ${pronoun(ch.companion)}.`:'';root.showDialogue?.(c,`${effect.line||'The decision is made.'}${extra}`,[{label:'Stay with them a while.',action:()=>{}}]);return true;}
function openReckoning(chOrId){const ch=typeof chOrId==='string'?BY_ID.get(chOrId):chOrId,c=ch&&companion(ch.companion),q=ch&&quest(ch.id);if(!ch||!c||!q||q.status!=='active'||!q.consulted)return false;const options=Object.entries(ch.resolutions).map(([key,spec])=>({label:spec.label,action:()=>complete(ch,key)}));options.push({label:'Not yet.',action:()=>{}});root.showDialogue?.(c,ch.reckoning,options);return true;}
function nextChapterFor(name){for(const ch of BY_COMPANION.get(name)||[]){const q=quest(ch.id);if(q?.status==='active')return ch;if(!q&&canStart(ch))return ch;}return null;}
function companionQuestOption(name){const ch=nextChapterFor(name);if(!ch)return null;const q=quest(ch.id);if(!q)return{label:`[Personal quest] ${ch.title}`,action:()=>start(ch),__companionQuestChain:ch.id};if(!q.consulted)return{label:`[${ch.title}] We still need to speak with ${ch.actor}.`,action:()=>root.showMessage?.(`${ch.actor} can move ${ch.title} forward.`),__companionQuestChain:ch.id};return{label:`[${ch.title}] Decide what comes next.`,action:()=>openReckoning(ch),__companionQuestChain:ch.id};}
function actorQuestOption(npc){const name=String(npc?.name||'');for(const ch of CHAPTERS){const q=quest(ch.id);if(q?.status==='active'&&!q.consulted&&ch.actorAliases.includes(name))return{label:`[${ch.title}] ${ch.actorPrompt}`,action:()=>consult(ch,npc),__companionQuestChain:ch.id};}return null;}
function decorateOptions(npc,options){if(!Array.isArray(options))return options;let extra=BY_COMPANION.has(String(npc?.name||''))?companionQuestOption(npc.name):null;if(!extra)extra=actorQuestOption(npc);if(!extra||options.some(o=>o?.__companionQuestChain===extra.__companionQuestChain||o?.label===extra.label))return options;const next=[...options],exit=next.findIndex(o=>/never mind|goodbye|leave it|nothing right now|other business/i.test(String(o?.label||'')));if(exit>=0)next.splice(exit,0,extra);else next.push(extra);return next;}
function installDialogueHook(){const current=root.showDialogue;if(typeof current!=='function')return false;if(current.__companionQuestChains)return true;const wrapped=function(npc,text,options){const args=Array.from(arguments);args[2]=decorateOptions(npc,options);return current.apply(this,args);};wrapped.__companionQuestChains=true;wrapped.__previous=current;wrapped.__baseShowDialogue=current;root.showDialogue=wrapped;return true;}
function refresh(){installDialogueHook();return true;}
const api={build:BUILD,chapters:CHAPTERS,chapter:id=>BY_ID.get(id)||null,canStart,ensureQuest,start,consult,complete,openReckoning,nextChapterFor,companionQuestOption,actorQuestOption,decorateOptions,refresh};
root.companionQuestChains=api;root.COMPANION_QUEST_CHAINS_BUILD=BUILD;if(typeof module!=='undefined'&&module.exports)module.exports=api;
if(typeof document!=='undefined'){refresh();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh,{once:true});setInterval(refresh,1200);}
})();
