// companionTriadConversations.js
// Three-person party discussions: two companions develop an argument or joke,
// and the protagonist may take a side, mediate, or deliberately stay out of it.
(function(root){
'use strict';
const BUILD='20261001-companion-triad-conversations-v1',HOUR=3600,MINUTE=60,TOPIC='join_triad_conversation';
const CORE=['Wren Talbot','Ser Aldric Thorne','Mirabel Quill','Fenn Oakheart','Reyna Fletcher','Brother Alden'];
const RAW=[
 ['wren_aldric_authority','Wren Talbot','Ser Aldric Thorne','good rulers still need limits on powers we would fear in worse hands','authority can also fail by being denied enough room to act','Power needs limits even when we trust the person using it.','Sometimes responsibility means giving someone room to act.','Power needs room to work and scrutiny to stop becoming permanent.',['accountable_authority','restrained_power'],['pragmatic','security_first']],
 ['wren_mirabel_knowledge','Wren Talbot','Mirabel Quill','some knowledge is effectively instructions for ruining everyone’s day','destroying dangerous knowledge is still destroying knowledge','Some things are dangerous enough that preservation is not automatically virtuous.','If nobody preserves dangerous knowledge, nobody can learn how to counter it.','Preserve it, restrict access, and make sure no single person controls the lock forever.',['caution','pragmatic'],['preserve_knowledge','curiosity']],
 ['wren_fenn_ownership','Wren Talbot','Fenn Oakheart','people need secure homes even if ownership is a human invention','ownership becomes dangerous when people forget it is a useful invention','People still need secure homes and rights.','Ownership should come with obligations to the place and the people around it.','Ask what responsibilities come with claiming ownership instead of pretending the claim is absolute.',['individual_dignity','pragmatic'],['stewardship','shared_burden']],
 ['wren_reyna_privacy','Wren Talbot','Reyna Fletcher','quietly building dossiers on friends is where vigilance becomes intrusive','if a pattern might get us killed, she is going to keep noticing it','People deserve some privacy even from competent friends.','If Reyna is keeping us alive, I want her noticing patterns.','Notice what matters, but tell people when you are acting on information about them.',['privacy','restrained_power'],['security_first','pragmatic']],
 ['wren_alden_anger','Wren Talbot','Brother Alden','anger tells you something mattered enough to hurt','anger can be truthful without every action it demands being wise','Anger can be morally important; calmness is not automatically virtue.','Feeling anger and obeying anger are different things.','Keep the anger long enough to learn what it protects, then decide with more than anger in the room.',['engagement','justice'],['restraint','reflection']],
 ['aldric_mirabel_risk','Ser Aldric Thorne','Mirabel Quill','a discovery is not improved by killing its discoverer','safety is not improved by refusing to investigate everything dangerous','If the danger is poorly understood, caution is not cowardice.','Someone has to be willing to learn what the danger actually is.','Investigate, but decide the safeguards before curiosity has already won the argument.',['caution','procedural'],['curiosity','preserve_knowledge']],
 ['aldric_fenn_roads','Ser Aldric Thorne','Fenn Oakheart','roads mean faster food, medicine and reinforcement','roads also mean faster logging, hunting and intrusion','Infrastructure can save lives; we should not romanticise isolation.','A road changes a place permanently, and that cost should count first.','Build where the social benefit is real and design around the ecological cost.',['pragmatic','shared_burden'],['stewardship','caution']],
 ['aldric_reyna_orders','Ser Aldric Thorne','Reyna Fletcher','field decisions still need to serve the purpose of the order','if arrows are flying, someone planned badly if there is time to debate the order','Discretion is necessary, but people should still be accountable afterwards.','Field judgement exists because reality does not wait for perfect instructions.','Act first when you must; explain the deviation afterwards and let someone else review it.',['accountable_authority','procedural'],['pragmatic','discretion']],
 ['aldric_alden_duty','Ser Aldric Thorne','Brother Alden','necessary duties are often things nobody would freely choose','if every need becomes your duty, eventually there is no person left inside the tool','Duty sometimes requires doing what you would not choose for yourself.','A duty that destroys the person carrying it is badly designed.','Share necessary burdens so the work happens without making anyone expendable.',['duty','shared_burden'],['individual_dignity','stewardship']],
 ['mirabel_fenn_recording','Mirabel Quill','Fenn Oakheart','unrecorded practices can disappear in a generation','bad records can survive ten generations after understanding is gone','Imperfect records are usually better than letting knowledge vanish.','Some knowledge depends on context; a recipe can create false confidence.','Record the knowledge and its context, including what the writer does not know.',['preserve_knowledge','curiosity'],['stewardship','caution']],
 ['mirabel_reyna_magic','Mirabel Quill','Reyna Fletcher','magic can solve the problem elegantly','every time Mirabel says elegantly, Reyna checks the exits','A good magical solution is still a good solution.','Simple solutions have fewer ways to become catastrophic.','Try the simple approach first; keep the elegant one as the fallback if it earns its risk.',['curiosity','pragmatic'],['caution','pragmatic']],
 ['mirabel_alden_truth','Mirabel Quill','Brother Alden','truth does not become kinder because it is hidden','timing, consent and purpose still matter when placing truth in someone’s hands','People deserve the truth about things that affect their lives.','Disclosure without regard for timing can be cruelty wearing honesty.','Give people enough truth for agency without confusing maximum disclosure with maximum respect.',['transparency','agency'],['individual_dignity','restraint']],
 ['fenn_reyna_traps','Fenn Oakheart','Reyna Fletcher','a trap cannot decide not to injure the wrong person','a trap is a guard who does not need sleep','A defence that cannot distinguish friend, animal, child and enemy has a moral cost.','Defensive traps are reasonable when the threat is real.','Use traps where encounters can be controlled, and mark or remove them afterwards.',['stewardship','proportionality'],['security_first','pragmatic']],
 ['fenn_alden_intervention','Fenn Oakheart','Brother Alden','sometimes helping means leaving a system alone long enough to recover','non-interference can become a comfortable name for watching preventable suffering','Intervention can destroy systems we barely understand.','If suffering is clearly preventable, caution can become an excuse for doing nothing.','Stop immediate harm, then step back and see whether recovery can continue without us owning it.',['stewardship','caution'],['engagement','individual_dignity']],
 ['reyna_alden_trust','Reyna Fletcher','Brother Alden','trust should be earned from evidence','starting at negative trust makes strangers pay debts they never incurred','Caution with strangers is reasonable; trust can endanger other people too.','People deserve a genuine chance before being judged through someone else’s betrayal.','Start with limited trust, clear expectations, and let evidence move it in either direction.',['caution','security_first'],['individual_dignity','agency']]
];
const first=n=>String(n).replace(/^Ser /,'').split(' ')[0];
function buildScene(r){const[id,a,b,pa,pb,la,lb,lm,ta,tb]=r;return{id,a,b,minFamiliarity:12,opening:[[a,`“${pa[0].toUpperCase()+pa.slice(1)}.”`],[b,`“${pb[0].toUpperCase()+pb.slice(1)}.”`]],options:[
 ['a',la,ta,0],[ 'b',lb,tb,0],['mediate',lm,['mediating','pluralism','proportionality'],1],['leave','Keep going. I want to hear where this ends.',['open_to_dissent','delegates_judgement'],1]
]};}
const SCENES=Object.freeze(RAW.map(buildScene));
function party(){return Array.isArray(root.party)?root.party:[]} function player(){return party()[0]||root.player||null}
function companion(x){const n=typeof x==='string'?x:x?.name;return n?party().find((m,i)=>i>0&&m?.name===n)||null:null}
function now(){return Number(root.worldSeconds||0)} function camp(){return root.campSystem?.getCamp?.()||null} function moving(x){return!!x?.destination||!!x?.path?.length||!!x?.isMoving}
function memory(){const p=player();if(!p)return null;const m=p.companionTriadMemory&&typeof p.companionTriadMemory==='object'?p.companionTriadMemory:(p.companionTriadMemory={});m.version=1;m.pending=m.pending&&typeof m.pending==='object'?m.pending:null;m.lastOfferAt=Number(m.lastOfferAt||0);m.lastMinute=Number.isFinite(m.lastMinute)?m.lastMinute:null;m.lastCampAt=Number(m.lastCampAt||0);m.seen=m.seen&&typeof m.seen==='object'?m.seen:{};m.history=Array.isArray(m.history)?m.history:[];return m}
function pairState(a,b){const x=root.companionContextualBanter;if(x?.pairState)return x.pairState(a,b);const p=player();p.__triadPairFallback||={};const k=[typeof a==='string'?a:a?.name,typeof b==='string'?b:b?.name].sort().join('|');return p.__triadPairFallback[k]||={familiarity:20,warmth:0}}
function pairAffinity(a,b,d,reason){const x=root.companionContextualBanter;if(x?.pairAffinity)return x.pairAffinity(a,b,d,reason);const s=pairState(a,b);s.warmth=Math.max(-100,Math.min(100,Number(s.warmth||0)+Number(d||0)));return s}
function ready(s){return!!companion(s.a)&&!!companion(s.b)&&Number(pairState(s.a,s.b)?.familiarity||0)>=s.minFamiliarity}
function canTalk(s){if(root.isInCombat||!player()||!ready(s))return false;if(camp())return true;return party().every(x=>!moving(x))}
function pending(){const m=memory();if(!m?.pending)return null;if(now()-Number(m.pending.offeredAt||0)>HOUR*2){m.pending=null;return null}const s=SCENES.find(x=>x.id===m.pending.sceneId);if(!s||!ready(s)){m.pending=null;return null}return{...m.pending,scene:s}}
function eligibleScenes(){const m=memory();return m?SCENES.filter(s=>canTalk(s)&&!m.seen[s.id]):[]}
function chooseScene(){return eligibleScenes().sort((x,y)=>Number(pairState(y.a,y.b)?.familiarity||0)-Number(pairState(x.a,x.b)?.familiarity||0)||x.id.localeCompare(y.id))[0]||null}
function offer({force=false,fromCamp=false}={}){const m=memory();if(!m||root.isInCombat)return false;const old=pending();if(old)return old;if(!force&&now()-m.lastOfferAt<HOUR*6)return false;const s=chooseScene();if(!s)return false;m.pending={sceneId:s.id,a:s.a,b:s.b,offeredAt:now(),fromCamp:!!fromCamp};m.lastOfferAt=now();root.showMessage?.(`${first(s.a)} and ${first(s.b)} have drifted into a discussion. You can join them while the party is stopped.`);return{...m.pending,scene:s}}
function outcome(s,o){if(o[0]==='mediate')return`${s.a} and ${s.b} both pause. Neither looks wholly converted, but the argument has moved somewhere more useful.`;if(o[0]==='leave')return`${s.a} glances at ${first(s.b)}, then continues. The discussion carries on without requiring you to become its referee.`;const chosen=o[0]==='a'?s.a:s.b,other=o[0]==='a'?s.b:s.a;return`${chosen} nods at your answer. ${other} does not concede the point, but answers it rather than dismissing it.`}
function record(s,o){root.partyConversationDynamics?.recordPlayerChoice?.({sourceId:'triad_conversation',choiceId:`${s.id}:${o[0]}`,context:'party_social',tags:o[2]||[],strength:1,witnessedBy:[s.a,s.b]})}
function resolve(s,o){const m=memory();if(!m)return false;if(o[3])pairAffinity(s.a,s.b,o[3],`triad:${s.id}:${o[0]}`);record(s,o);m.seen[s.id]=1;m.pending=null;m.history.push({sceneId:s.id,choiceId:o[0],at:now(),a:s.a,b:s.b,pairDelta:o[3]||0});if(m.history.length>60)m.history.splice(0,m.history.length-60);root.showDialogue?.({name:`${s.a} & ${s.b}`},outcome(s,o),[{label:'Leave them to it.',action:()=>{}}]);return true}
function options(s){const base=s.options.map(o=>({label:o[1],action:()=>resolve(s,o),__triadChoice:o[0]})),d=root.partyConversationDynamics;if(!d?.shapePlayerOptions)return base;const variants=[{label:'“Enough. We are doing it my way.”',minBehaviour:{hierarchical:3},tags:['hierarchical','centralising'],__triadChoice:'take_over',action:()=>resolve(s,['take_over','',['hierarchical','centralising'],-1])},{label:'“You two can work this out without me.”',minBehaviour:{delegates_judgement:3},tags:['delegates_judgement','open_to_dissent'],__triadChoice:'delegate',action:()=>resolve(s,['delegate','',['delegates_judgement','open_to_dissent'],1])}];return d.shapePlayerOptions({baseOptions:base,variants,maxBehaviourExtras:1,character:player()})}
function render(){const p=pending();if(!p||!canTalk(p.scene))return null;const w=Number(pairState(p.a,p.b)?.warmth||0),tone=w>=25?'\n\nThe disagreement has the ease of people who know they can disagree safely.':w<=-10?'\n\nNeither sounds entirely relaxed; this subject has history between them.':'';return{subject:'a party discussion',text:p.scene.opening.map(([n,t])=>`${n}: ${t}`).join('\n\n')+tone,options:options(p.scene),noReturn:true}}
function topic(name){return{id:TOPIC,label:()=>{const p=pending();if(!p||!(p.a===name||p.b===name))return'Join the conversation.';return`Join ${first(name)} and ${first(p.a===name?p.b:p.a)}'s discussion.`},priority:70,condition:()=>{const p=pending();return!!p&&(p.a===name||p.b===name)&&canTalk(p.scene)},render:()=>render()||{}}}
let installed=false;function installTopics(){const m=root.companionConversationMemory;if(!m?.registerTopics)return false;CORE.forEach(n=>m.registerTopics(n,[topic(n)]));installed=true;return true}
function clearPending(){const m=memory();if(m)m.pending=null}
function handleCamp(c=camp()){const m=memory();if(!m||!c)return false;const stamp=Number(c.startedAt||c.establishedAt||0);if(stamp&&m.lastCampAt===stamp)return false;if(stamp)m.lastCampAt=stamp;return offer({force:true,fromCamp:true})||false}
function tick({force=false}={}){const m=memory();if(!m)return false;const minute=Math.floor(now()/MINUTE);if(!force&&m.lastMinute===minute)return false;m.lastMinute=minute;if(pending()||root.isInCombat||(!camp()&&party().some(moving)))return false;if(!force&&Math.floor(now()/HOUR)===Math.floor((now()-MINUTE)/HOUR))return false;return offer({force})}
function refresh(){if(!installed)installTopics();if(!root.__companionTriadCampHook&&typeof root.addEventListener==='function'){root.addEventListener('campDialogue',e=>handleCamp(e?.detail?.camp||camp()));root.__companionTriadCampHook=true}}
const api={build:BUILD,scenes:SCENES,memory,pairState,pairAffinity,eligibleScenes,chooseScene,offer,clearPending,pending,render,options,resolve,handleCamp,tick,installTopics,refresh};root.companionTriadConversations=api;root.COMPANION_TRIAD_CONVERSATIONS_BUILD=BUILD;if(typeof module!=='undefined'&&module.exports)module.exports=api;refresh();if(root.document?.readyState==='loading')root.document.addEventListener('DOMContentLoaded',refresh,{once:true});if(typeof root.setInterval==='function'&&root.document)root.setInterval(()=>tick(),1000);
})(typeof window!=='undefined'?window:globalThis);
