// companionConversationMemory.js
// Authored companion conversation memory, salience, cooldowns and personality clues.
(() => {
'use strict';
const BUILD='20261001-companion-conversation-memory-v6', DAY=86400, DEFAULT_LIMIT=4, registry=new Map();
const now=()=>Number(window.worldSeconds||0), party=()=>Array.isArray(window.party)?window.party:[], quest=id=>(window.questLog||[]).find(q=>q?.id===id)||null;
function canonical(x){const n=typeof x==='string'?x:x?.name;return n?party().find((m,i)=>i>0&&m?.name===n)||null:null;}
function ensureMemory(x){const c=canonical(x);if(!c)return null;window.getCompanionRelationship?.(c);c.playerRelationship ||= {familiarity:10,trust:10,history:[],knownConversationKeys:[]};const e=c.playerRelationship.conversationMemory||{};return c.playerRelationship.conversationMemory={version:3,topics:e.topics&&typeof e.topics==='object'?e.topics:{},history:Array.isArray(e.history)?e.history:[],lastMeaningful:e.lastMeaningful||null};}
function topicState(c,id){const m=ensureMemory(c);if(!m)return null;return m.topics[id] ||= {uses:0,lastAt:null,lastVariant:-1};}
function contextFor(x){const c=canonical(x);if(!c)return null;return {companion:c,player:party()[0]||null,party:party(),partyNames:new Set(party().map(m=>m?.name).filter(Boolean)),relationship:window.getCompanionRelationship?.(c)||{},affinity:window.getCompanionAffinity?.(c)||c.playerAffinity||{},romance:window.companionRomance?.interpretRelationship?.(c)||null,worldSeconds:now(),quest,memory:ensureMemory(c)};}
function registerTopics(name,topics){if(!name||!Array.isArray(topics))return false;const cur=registry.get(name)||new Map();for(const t of topics)if(t?.id&&typeof t.render==='function')cur.set(String(t.id),{...t,id:String(t.id)});registry.set(name,cur);return true;}
function num(v,c,s,f=0){try{const r=typeof v==='function'?v(c,s):v;return Number.isFinite(Number(r))?Number(r):f}catch{return f}}
function bool(v,c,s,f=true){if(v===undefined)return f;try{return typeof v==='function'?!!v(c,s):!!v}catch{return false}}
function available(t,c,s){if(!t||!c||!s||!bool(t.condition,c,s,true))return false;const max=t.maxUses==null?Infinity:Math.max(0,Number(t.maxUses));if(s.uses>=max)return false;if(s.uses>0&&s.lastAt!=null){const cd=num(t.cooldownSeconds,c,s,num(t.cooldownDays,c,s,0)*DAY);if(cd>0&&c.worldSeconds-Number(s.lastAt||0)<cd)return false;}return true;}
function score(t,c,s){let n=num(t.priority,c,s,20);if(!s.uses)n+=15;n-=Math.min(18,s.uses*3);if(t.reactive)n+=10;if(t.milestone)n+=18;return n;}
function availableTopics(x,limit=DEFAULT_LIMIT){const c=contextFor(x), map=registry.get(c?.companion?.name);if(!c||!map)return[];const out=[];for(const t of map.values()){const s=topicState(c.companion,t.id);if(available(t,c,s))out.push({topic:t,state:s,ctx:c,score:score(t,c,s)});}return out.sort((a,b)=>b.score-a.score||a.topic.id.localeCompare(b.topic.id)).slice(0,Math.max(1,Number(limit)||DEFAULT_LIMIT));}
function label(t,c,s){try{return String((typeof t.label==='function'?t.label(c,s):t.label)||'Talk about something.')}catch{return'Talk about something.'}}
function recordUse(c,t,s,r,ctx){const m=ensureMemory(c);if(!m)return;s.uses=Number(s.uses||0)+1;s.lastAt=now();s.lastVariant=Number(r?.variantIndex??s.lastVariant??-1);const e={topicId:t.id,subject:String(r?.subject||t.subject||t.id),at:s.lastAt,use:s.uses};m.lastMeaningful=e;m.history.push(e);if(m.history.length>40)m.history.splice(0,m.history.length-40);const clues=r?.personalityClues??t.personalityClues;for(const clue of(Array.isArray(clues)?clues:(clues?[clues]:[]))){if(typeof clue==='string')window.learnCompanionPersonality?.(c.name,clue,1,t.id);else if(clue?.trait)window.learnCompanionPersonality?.(c.name,clue.trait,clue.amount||1,t.id);}window.companionPersonalityKnowledge?.syncFromConversationHistory?.(c.name);try{t.onDiscuss?.(ctx,s,r)}catch{}}
function knownPersonality(x){const c=canonical(x);if(!c)return[];try{window.companionEvergreenPersonalityClues?.sync?.(c.name);return window.companionPersonalityKnowledge?.known?.(c.name)||[]}catch{return[]}}
function showKnownPersonality(x){const c=canonical(x),clues=knownPersonality(c);if(!c||!clues.length)return false;const text=`From your conversations with ${c.name}, you’ve learned:\n\n${clues.map(k=>`• ${k.text}`).join('\n\n')}`;window.showDialogue?.({name:`Your notes — ${c.name}`},text,[{label:'Back to the conversation.',action:()=>openHub(c)},{label:'Close notes.',action:()=>{}}]);return true;}
function openHub(x,limit=DEFAULT_LIMIT){const c=canonical(x);if(!c)return false;const subjects=availableTopics(c,limit),clues=knownPersonality(c);if(!subjects.length&&!clues.length){window.showDialogue?.(c,'Nothing urgent comes to mind. Quiet company is all right too.',[{label:'Stay a while.',action:()=>{}}]);return true;}const opts=subjects.map(({topic,state,ctx})=>({label:label(topic,ctx,state),action:()=>playTopic(c,topic.id)}));if(clues.length)opts.push({label:`Review what you’ve learned about ${c.name}.`,action:()=>showKnownPersonality(c)});opts.push({label:'Never mind.',action:()=>{}});window.showDialogue?.(c,subjects.length?'What do you want to talk about?':'There’s nothing new to ask about right now.',opts);return true;}
function playTopic(x,id){const ctx=contextFor(x),c=ctx?.companion,t=registry.get(c?.name)?.get(String(id));if(!ctx||!c||!t)return false;const s=topicState(c,t.id);if(!available(t,ctx,s))return false;let r;try{r=t.render(ctx,s)||{}}catch{return false}if(!r.text)return false;recordUse(c,t,s,r,ctx);const opts=Array.isArray(r.options)&&r.options.length?[...r.options,...(r.noReturn?[]:[{label:'Talk about something else.',action:()=>openHub(c)}])]:[{label:'Talk about something else.',action:()=>openHub(c)},{label:'That’s enough for now.',action:()=>{}}];window.showDialogue?.(c,r.text,opts);return true;}
function lastMeaningful(x){return ensureMemory(x)?.lastMeaningful||null;}
function installDialogueEntry(id,name){const trees=window.npcDialogueTrees,orig=trees?.[id];if(typeof orig!=='function')return false;const marker=`__conversationMemory_${id}`;if(orig[marker])return true;const wrapped=function(npc){if(typeof window.showDialogue!=='function')return orig.apply(this,arguments);const base=window.showDialogue;let first=true;window.showDialogue=function(speaker,text,options){if(first&&speaker?.name===name&&Array.isArray(options)){first=false;if((availableTopics(name).length||knownPersonality(name).length)&&!options.some(o=>o?.__conversationMemoryEntry)){const add={label:'Talk for a while.',__conversationMemoryEntry:true,action:()=>openHub(name)},next=[...options],exit=next.findIndex(o=>/never mind|goodbye|leave/i.test(String(o?.label||'')));if(exit>=0)next.splice(exit,0,add);else next.push(add);return base.call(this,speaker,text,next);}}return base.apply(this,arguments)};try{return orig.apply(this,arguments)}finally{window.showDialogue=base}};wrapped[marker]=true;wrapped.__previous=orig;trees[id]=wrapped;return true;}
const api={build:BUILD,daySeconds:DAY,registerTopics,ensureMemory,topicState,contextFor,availableTopics,knownPersonality,showKnownPersonality,playTopic,openHub,lastMeaningful,installDialogueEntry};window.companionConversationMemory=api;window.COMPANION_CONVERSATION_MEMORY_BUILD=BUILD;if(typeof module!=='undefined'&&module.exports)module.exports=api;

// Keep the personality-learning layer beside the conversation system so the
// feature cannot silently exist in the repository without being loaded. These
// scripts are authored data/knowledge only; they do not grant approval points.
if(typeof document!=='undefined'&&!window.__companionPersonalityKnowledgeModuleLoaded){
 window.__companionPersonalityKnowledgeModuleLoaded=true;
 const load=src=>{const s=document.createElement('script');s.src=src;s.async=false;(document.head||document.documentElement).appendChild(s);};
 load('companionPersonalityKnowledge.js?build=20261001-personality-knowledge-v4');
 load('companionPersonalityConversations.js?build=20260930-companion-personality-conversations-v1');
 load('companionEvergreenPersonalityClues.js?build=20260930-evergreen-personality-clues-v2');
}
})();
