// disguiseSelfRoster.js
// Persistent roster of humanoid characters the player has actually encountered.
// Stores a visual snapshot so the target remains available after the NPC leaves
// the map or is later regenerated by world streaming.
(() => {
    'use strict';

    const BUILD = '20261008-disguise-self-roster-v1';
    const STATE_KEY = 'disguiseSelfKnownCharacters';

    const HUMANOID_RACES = new Set([
        'human', 'elf', 'dwarf', 'orc', 'goblin', 'half-elf', 'halfling',
        'gnome', 'tiefling', 'dragonborn'
    ]);

    function protagonist() {
        return window.party?.[0] || window.player || null;
    }

    function store() {
        const pc = protagonist();
        if (!pc) return null;
        if (!Array.isArray(pc[STATE_KEY])) pc[STATE_KEY] = [];
        return pc[STATE_KEY];
    }

    function appearanceOf(entity) {
        const a = entity?.appearance || {};
        return {
            gender: entity?.gender || a.gender || 'female',
            bodyType: entity?.bodyType || a.bodyType || 'average',
            hairStyle: entity?.hairStyle || a.hairStyle || 'brown_1',
            hairHue: Number(entity?.hairHue ?? a.hairHue ?? 25),
            hairSaturation: Number(entity?.hairSaturation ?? a.hairSaturation ?? 70),
            hairValue: Number(entity?.hairValue ?? a.hairValue ?? 55),
            skinToneSlider: Number(entity?.skinToneSlider ?? a.skinToneSlider ?? 45)
        };
    }

    function isHumanoid(entity) {
        if (!entity || !entity.name) return false;
        if (entity === protagonist()) return false;
        if (Array.isArray(entity.tags) && entity.tags.some(tag => ['animal', 'beast', 'creature'].includes(String(tag).toLowerCase()))) return false;

        const race = String(entity.race || entity.appearance?.race || '').toLowerCase();
        if (HUMANOID_RACES.has(race)) return true;

        // Generic authored humanoid NPCs may carry only a human-style appearance
        // without a race field. Do not mistake creature sprites for people.
        return !!(
            entity.appearance &&
            (entity.appearance.gender || entity.appearance.bodyType || entity.appearance.hairStyle) &&
            !entity.baseType?.includes('creature') &&
            !entity.baseType?.includes('wolf') &&
            !entity.baseType?.includes('spider') &&
            !entity.baseType?.includes('skeleton') &&
            !entity.baseType?.includes('zombie') &&
            !entity.baseType?.includes('dragon')
        );
    }

    function equipmentOf(entity) {
        if (!entity?.equipped || typeof entity.equipped !== 'object') return null;
        return Object.fromEntries(
            Object.entries(entity.equipped)
                .filter(([, value]) => typeof value === 'string' && value)
        );
    }

    function record(entity) {
        if (!isHumanoid(entity)) return false;
        const list = store();
        if (!list) return false;

        const entry = {
            id: String(entity.name),
            name: String(entity.name),
            race: entity.race || entity.appearance?.race || null,
            gender: entity.gender || entity.appearance?.gender || null,
            appearance: appearanceOf(entity),
            visualEquipment: equipmentOf(entity),
            encounteredAt: Date.now()
        };

        const existing = list.findIndex(item => item?.id === entry.id);
        if (existing >= 0) list[existing] = entry;
        else list.push(entry);

        // Keep the protagonist's own party members available even when they
        // are benched and therefore absent from window.entities.
        return true;
    }

    function syncParty() {
        (window.party || []).forEach(member => record(member));
        (window.benchedCompanions || []).forEach(member => record(member));
    }

    function list(caster) {
        syncParty();
        const currentName = caster?.name || protagonist()?.name;
        return (store() || [])
            .filter(entry => entry?.name && entry.name !== currentName)
            .map(entry => ({ ...entry, appearance: { ...(entry.appearance || {}) } }));
    }

    function find(name, caster) {
        return list(caster).find(entry => entry.name === name) || null;
    }

    function profileFor(name, caster) {
        const entry = find(name, caster);
        if (!entry) return null;
        return {
            appearance: { ...(entry.appearance || {}) },
            visualEquipment: entry.visualEquipment ? { ...entry.visualEquipment } : null
        };
    }

    window.disguiseSelfRoster = {
        BUILD,
        record,
        syncParty,
        list,
        find,
        profileFor,
        isHumanoid
    };
    window.recordDisguiseSelfEncounter = record;
    window.getDisguiseSelfKnownCharacters = list;
    window.getDisguiseSelfProfile = profileFor;
    window.DISGUISE_SELF_ROSTER_BUILD = BUILD;
})();
