// entityRenderInstrumentation.js
// Directional humanoid composite cache + deterministic post-construction art gate.
(() => {
'use strict';
if(window.__entityRenderInstrumentationInstalled)return;
window.__entityRenderInstrumentationInstalled=true;
const cache=new WeakMap(),partySourceCache=new WeakMap(),PAD=4;
const stats=window.entityRenderInstrumentationStats={installed:false,calls:0,totalMs:0,maxMs:0,humanoidCalls:0,humanoidMs:0,humanoidMaxMs:0,customCalls:0,customMs:0,customMaxMs:0,creatureCalls:0,creatureMs:0,creatureMaxMs:0,otherCalls:0,otherMs:0,otherMaxMs:0,cacheHits:0,cacheMisses:0,cacheBuilds:0,cacheFailed:0,cacheBuildMs:0,cacheMaxBuildMs:0,directionHits:0,appearanceInvalidations:0,sideMirrorHits:0,readinessBypasses:0,partyAppearanceSyncs:0,postStartAssets:0,postStartFailures:0,postStartGateMs:0,manifestEntities:0,manifestPaths:0,samples:[],installs:0};
let ready=false;
function publish(v){ready=!!v;const s=window.__assetLoadScheduler;if(s){try{Object.defineProperty(s,'compositeCacheReady',{configurable:true,get:()=>ready});}catch(_){}}}
publish(false);
function classify(e){if(!e)return'other';if(e.customImage)return'custom';if(e.race&&e.gender)return'humanoid';if(e.image||e.sprite||e.type)return'creature';return'other';}
function combat(){try{return typeof window.isInCombat==='function'?!!window.isInCombat():!!window.isInCombat;}catch(_){return true;}}
function safe(v){try{return JSON.stringify(v)||'';}catch(_){return String(v??'');}}
function partySource(e){if(!e||e.side!=='player'||!e.name)return null;const cached=partySourceCache.get(e);if(cached&&cached.name===e.name&&(window.party||[]).includes(cached))return cached;const found=(window.party||[]).find(p=>p&&p.name===e.name)||null;if(found)partySourceCache.set(e,found);return found;}
function syncPartyAppearance(e){const p=partySource(e);if(!p||p===e)return e;let changed=false;if(p.equipped&&e.equipped!==p.equipped){e.equipped=p.equipped;changed=true;}if(p.clothingColors&&e.clothingColors!==p.clothingColors){e.clothingColors=p.clothingColors;changed=true;}if(p.equipmentVisibility&&e.equipmentVisibility!==p.equipmentVisibility){e.equipmentVisibility=p.equipmentVisibility;changed=true;}for(const k of ['displayArmour','displayClothes','bodyType','hairStyle','facialHairStyle','hairHue','hairLightMult','hairSatMult','skinHue','skinSaturation','skinLightness','goldGear','tattoos','scars'])if(p[k]!==undefined&&e[k]!==p[k]){e[k]=p[k];changed=true;}if(changed){stats.partyAppearanceSyncs++;cache.delete(e);}return e;}
window.syncPartyAppearanceForRender=syncPartyAppearance;
function appearanceKey(e,z,f){return[e.race||'',e.gender||'',e.bodyType||'',e.hairStyle||'',e.facialHairStyle||'',e.hairHue??'',e.skinHue??'',e.displayArmour===false?0:1,e.displayClothes===false?0:1,e.goldGear?1:0,Number(z||1).toFixed(3),Number(f||0).toFixed(3),Number(window.hexSize||30).toFixed(2),safe(e.equipped),safe(e.clothingColors),safe(e.equipmentVisibility),safe(e.tattoos),safe(e.scars)].join('|');}
function facing(e){return['up','down','left','right'].includes(e?.facing)?e.facing:'down';}
function shielded(e){const q=e?.equipped||{};return!!(q.shield||String(q.offHand||q.offhand||'').toLowerCase().includes('shield')||String(q.mainHand||q.mainhand||'').toLowerCase().includes('shield'));}
function mirrorSafe(e){return!shielded(e)&&!e?.shieldAppearance&&!e?.quiver&&!e?.quiverAppearance&&!(e?.tattoos?.length)&&!(e?.scars?.length)&&!e?.asymmetricAppearance&&!e?.asymmetricHair&&!e?.forceFourFacingSprites;}
function opposite(f){return f==='left'?'right':f==='right'?'left':null;}
function record(kind,ms,e){stats.calls++;stats.totalMs+=ms;stats.maxMs=Math.max(stats.maxMs,ms);stats[`${kind}Calls`]++;stats[`${kind}Ms`]+=ms;stats[`${kind}MaxMs`]=Math.max(stats[`${kind}MaxMs`],ms);if(ms>=1){stats.samples.push({ms,kind,name:e?.name||e?.id||e?.type||'unknown',race:e?.race||'',gender:e?.gender||'',side:e?.side||''});stats.samples.sort((a,b)=>b.ms-a.ms);if(stats.samples.length>30)stats.samples.length=30;}}
function build(original,e,z,fly){const hs=Math.max(1,Number(window.hexSize||30)),scale=Math.max(.1,Number(z||1)),size=Math.max(64,Math.ceil(hs*scale*PAD*2)),c=document.createElement('canvas');c.width=size;c.height=size;const x=c.getContext('2d');if(!x)return null;const cx=size/2,cy=size/2,t=performance.now();original(x,e,cx,cy,z,fly);const ms=performance.now()-t;stats.cacheBuildMs+=ms;stats.cacheMaxBuildMs=Math.max(stats.cacheMaxBuildMs,ms);stats.cacheBuilds++;return{canvas:c,cx,cy};}
function chain(fn,mark){const seen=new Set();while(typeof fn==='function'&&!seen.has(fn)){seen.add(fn);if(fn[mark])return true;fn=fn.__original;}return false;}
function installDraw(){const current=window.drawPlayerCharacter;if(typeof current!=='function')return false;if(chain(current,'__directionalHumanoidCompositeCache'))return true;const wrapped=function(ctx,e,...rest){syncPartyAppearance(e);const kind=classify(e),x=rest[0],y=rest[1],z=rest[2]??1,fly=rest[3]??0,t=performance.now();try{const humanoid=kind==='humanoid'&&!e.customImage&&!combat()&&ctx;if(humanoid&&!ready){stats.readinessBypasses++;cache.delete(e);return current.call(this,ctx,e,...rest);}if(humanoid){const key=appearanceKey(e,z,fly),f=facing(e);let b=cache.get(e);if(!b||b.key!==key){if(b)stats.appearanceInvalidations++;b={key,views:new Map()};cache.set(e,b);}let entry=b.views.get(f);if(entry){stats.cacheHits++;stats.directionHits++;ctx.drawImage(entry.canvas,x-entry.cx,y-entry.cy);return;}const o=opposite(f);if(o&&mirrorSafe(e)&&(entry=b.views.get(o))){stats.cacheHits++;stats.directionHits++;stats.sideMirrorHits++;ctx.save();ctx.translate(x,0);ctx.scale(-1,1);ctx.translate(-x,0);ctx.drawImage(entry.canvas,x-entry.cx,y-entry.cy);ctx.restore();return;}stats.cacheMisses++;try{entry=build(current,e,z,fly);}catch(err){entry=null;console.warn('[humanoid-cache] build failed',e?.name,f,err);}if(entry){b.views.set(f,entry);ctx.drawImage(entry.canvas,x-entry.cx,y-entry.cy);return;}stats.cacheFailed++;}return current.call(this,ctx,e,...rest);}finally{record(kind,performance.now()-t,e);}};wrapped.__directionalHumanoidCompositeCache=true;wrapped.__liveHumanoidCompositeCache=true;wrapped.__entityRenderInstrumentation=true;wrapped.__original=current;if(chain(current,'__directHumanoidCompositor'))wrapped.__directHumanoidCompositor=true;window.drawPlayerCharacter=wrapped;window.__hexInstrumentedDrawPlayerCharacter=wrapped;try{(0,eval)('drawPlayerCharacter = window.__hexInstrumentedDrawPlayerCharacter');}catch(_){}window.clearHumanoidSpriteCache=e=>{if(e)cache.delete(e);};stats.installs++;stats.installed=true;return true;}
function add(set,p){if(typeof p!=='string')return;const s=p.replace(/^\.\//,'').split('?')[0];if(s.startsWith('images/'))set.add(window.assetManager?.canonicalPathFor?.(s)||s);}
function viewPaths(obj,set){if(!obj)return;for(const v of ['front','side','back'])add(set,obj[v]);}
function genericItemAssets(e,set){for(const id of Object.values(e?.equipped||{})){if(typeof id!=='string')continue;const item=window.items?.[id];if(!item)continue;viewPaths(item.clothingViews,set);for(const l of item.clothingLayers||[])viewPaths(l.views,set);add(set,item.image);add(set,item.sprite);}}
function humanoidAssets(e,set){syncPartyAppearance(e);const key=`${e.race}_${e.gender}`,body=e.bodyType==='broad'?'body_broad':'body';if(key==='human_female'||key==='human_male'){for(const v of ['front','side','back'])add(set,`images/characters/${key}/${body}_${v}.png`);}else if(key==='elf_female'){for(const v of ['front','side','back'])add(set,`images/characters/elf_female/body_${v}.png`);}else if(key==='elf_male'||key==='dwarf_female'||key==='dwarf_male'){add(set,`images/characters/${key}/body.png`);}else if(key==='goblin_female'||key==='goblin_male'||key==='orc_female'||key==='orc_male'){for(const v of ['front','side','back'])add(set,`images/characters/${key}/body_${v}.png`);}const hair=e.hairStyle||'brown_1';for(const v of ['front','side','back'])add(set,`images/characters/human_female/hair_${hair}_${v}.png`);for(const p of window.clothingSystem?.resolveOutfitAssetPaths?.(e,['front','side','back'])||[])add(set,p);genericItemAssets(e,set);if(e.displayArmour!==false&&e.equipped?.armor){const item=window.items?.[e.equipped.armor],r=Number(item?.reduction||0),tier=r>=3?'heavy':r>=2?'medium':'light';add(set,`images/equipment/armour/human/${tier}.png`);add(set,`images/equipment/armour/human/${tier}_back.webp`);}if(e.equipped?.helmet){add(set,'images/equipment/helmets/nasal_helm.png');add(set,'images/equipment/helmets/nasal_helm_back.svg');}const eq=Object.values(e.equipped||{}).filter(v=>typeof v==='string');for(const id of eq){const l=id.toLowerCase();if(l.includes('shield')){const kite=l.includes('kite');add(set,kite?'images/equipment/shields/kite.png':'images/equipment/shields/round.png');add(set,kite?'images/equipment/shields/kite_back.png':'images/equipment/shields/round_back.svg');}else if(l.includes('bow'))add(set,'images/equipment/weapons/bow.svg');else if(l.includes('spear'))add(set,'images/equipment/weapons/spear.png');else if(l.includes('axe')||l.includes('pickaxe'))add(set,'images/equipment/weapons/axe.png');else if(l.includes('club'))add(set,'images/equipment/weapons/club.svg');else if(l.includes('dagger')||l.includes('sword'))add(set,'images/equipment/weapons/sword.png');}if(e.facialHairStyle==='moustache'){add(set,'images/characters/facial_hair/moustache_front.svg');add(set,'images/characters/facial_hair/moustache_side.svg');}if(e.facialHairStyle==='beard_full'){add(set,'images/characters/facial_hair/beard_full_front.png');add(set,'images/characters/facial_hair/beard_full_side.png');}}
function campaignManifest(){const set=new Set(),entities=[],seen=new Set();for(const e of [...(window.party||[]),...(window.entities||[]),window.player]){if(!e||seen.has(e))continue;seen.add(e);entities.push(e);}for(const e of entities){if(e.race&&e.gender&&!e.customImage)humanoidAssets(e,set);else{add(set,e.customImage);add(set,e.image);add(set,e.sprite);genericItemAssets(e,set);}}stats.manifestEntities=entities.length;stats.manifestPaths=set.size;stats.postStartAssets=set.size;return[...set];}
function overlay(){let el=document.getElementById('hex-post-start-asset-gate');if(el)return el;el=document.createElement('div');el.id='hex-post-start-asset-gate';el.style.cssText='position:fixed;inset:0;z-index:2147483647;background:linear-gradient(180deg,#151515,#090909);display:none;align-items:center;justify-content:center;color:#f4ead2;font-family:Georgia,serif;padding:24px;box-sizing:border-box';el.innerHTML='<div style="width:min(560px,92vw);padding:28px;border:1px solid #8f7445;border-radius:10px;background:#201d19;text-align:center"><h2 data-title>Preparing campaign…</h2><p data-count>Constructing campaign…</p><div style="height:12px;border-radius:999px;overflow:hidden;background:#0d0c0a;border:1px solid #5f5037"><div data-bar style="height:100%;width:4%;background:#b89a5c"></div></div><p data-error style="color:#efb0a8;word-break:break-word" hidden></p><div><button data-retry hidden>Retry failed assets</button> <button data-danger hidden>⚠ Proceed anyway — danger</button> <button data-start hidden style="padding:11px 22px;background:#2e7d32;color:white;font-weight:bold">Start game</button></div></div>';document.body.appendChild(el);return el;}
function progress(el,n,total,label='Loading campaign art…'){el.querySelector('[data-title]').textContent=label;el.querySelector('[data-count]').textContent=`Loaded ${n} / ${total} required campaign art assets`;el.querySelector('[data-bar]').style.width=`${total?Math.max(4,Math.round(n*100/total)):4}%`;}
async function loadManifest(el,paths){let n=0;const failed=[];progress(el,0,paths.length);const workers=Math.min(4,paths.length);let cursor=0;await Promise.all(Array.from({length:workers},async()=>{while(cursor<paths.length){const p=paths[cursor++];try{await window.assetManager.load(p,{priority:-100,immediate:true});}catch(_){failed.push(p);}finally{progress(el,++n,paths.length);}}}));return failed;}
async function startButton(el,count){el.querySelector('[data-title]').textContent='Ready to start';el.querySelector('[data-count]').textContent=`${count} required campaign art assets loaded. Tap Start game when ready.`;el.querySelector('[data-bar]').style.width='100%';const b=el.querySelector('[data-start]');b.hidden=false;await new Promise(r=>b.onclick=r);b.onclick=null;b.hidden=true;}
async function runGate(el,started){await new Promise(r=>setTimeout(r,0));const paths=campaignManifest();let failed=await loadManifest(el,paths);while(failed.length){stats.postStartFailures=failed.length;const er=el.querySelector('[data-error]'),re=el.querySelector('[data-retry]'),da=el.querySelector('[data-danger]');er.textContent=`${failed.length} required art asset${failed.length===1?'':'s'} failed: ${failed.slice(0,5).map(p=>p.split('/').pop()).join(', ')}. Retry is safest.`;er.hidden=false;re.hidden=false;da.hidden=false;const action=await new Promise(r=>{re.onclick=()=>r('retry');da.onclick=()=>r('danger');});re.onclick=da.onclick=null;re.hidden=da.hidden=true;er.hidden=true;if(action==='danger'){publish(false);stats.postStartGateMs=performance.now()-started;await startButton(el,paths.length-failed.length);el.style.display='none';return;}failed=await loadManifest(el,failed);}stats.postStartFailures=0;publish(true);stats.postStartGateMs=performance.now()-started;await startButton(el,paths.length);el.style.display='none';try{window.drawMap?.();}catch(_){}}
function installStart(){const current=window.startGame;if(typeof current!=='function'||current.__postStartAssetGate)return false;const wrapped=function(...args){publish(false);stats.postStartAssets=stats.postStartFailures=0;const el=overlay();el.style.display='flex';el.querySelector('[data-title]').textContent='Initialising campaign…';el.querySelector('[data-count]').textContent='Constructing characters before loading their art…';el.querySelector('[data-bar]').style.width='4%';const started=performance.now();let result;try{result=current.apply(this,args);}catch(err){el.querySelector('[data-title]').textContent='Campaign initialisation failed';const er=el.querySelector('[data-error]');er.textContent=String(err?.message||err);er.hidden=false;throw err;}queueMicrotask(()=>runGate(el,started).catch(err=>{console.error('[asset-gate]',err);publish(false);const er=el.querySelector('[data-error]');er.textContent=String(err?.message||err);er.hidden=false;}));return result;};wrapped.__postStartAssetGate=true;wrapped.__original=current;window.startGame=wrapped;try{(0,eval)('startGame = window.startGame');}catch(_){}return true;}
let tries=0;const timer=setInterval(()=>{installDraw();installStart();if(++tries>400||(stats.installed&&window.startGame?.__postStartAssetGate))clearInterval(timer);},25);
})();