// Slot-first equipment UI: body layout + click-to-equip picker + sortable/filterable backpack.
(()=>{'use strict';
const BUILD=window.PRESENTATION_BUILD||'20260930-equipment-ui-v1';
const SLOT_DEFS=[
 {key:'helmet',label:'Helmet',area:'helmet'},
 {key:'shirt',label:'Shirt / Dress',area:'shirt'},
 {key:'armor',label:'Armour',area:'armor'},
 {key:'weapon',label:'Main hand',area:'weapon'},
 {key:'offhand',label:'Off hand',area:'offhand'},
 {key:'pants',label:'Pants',area:'pants'},
 {key:'bra',label:'Bra',area:'bra'},
 {key:'underwear',label:'Underwear',area:'underwear'},
 {key:'accessory',label:'Accessory',area:'accessory'},
];
let state={filter:'all',sort:'name',picker:null};
const base=v=>window.getEquipmentBaseId?.(v)||v;
const def=v=>window.items?.[base(v)]||null;
function slotFor(raw){const id=base(raw),d=def(raw);if(!d)return null;if(d.type==='helmet')return'helmet';if(d.type==='armor')return d.subType==='barding'?null:'armor';if(d.type==='accessory')return'accessory';if(d.type==='shield')return'offhand';if(d.type==='weapon')return'weapon';if(d.type==='clothes')return window.clothingSystem?.getItemSpec?.(id)?.slot||d.clothingSlot||'shirt';return null;}
function compatible(raw,slot,p){const id=base(raw),d=def(raw);if(!d)return false;if(slot==='offhand'){if(d.type==='shield')return true;if(d.type!=='weapon'||!d.canOffhand)return false;const main=def(p?.equipped?.weapon);return !main||main.hands===1;}if(slot==='weapon')return d.type==='weapon';return slotFor(raw)===slot;}
function weight(raw){const d=def(raw);if(Number.isFinite(Number(d?.weight)))return Number(d.weight);const id=base(raw);if(d?.type==='helmet')return 2;if(d?.type==='shield')return id==='bulwark_shield'?7:5;if(d?.type==='armor'){const r=Number(d.reduction||0);return r>=3?18:r>=2?11:6;}if(d?.type==='weapon')return d.hands===2?4:2;if(d?.type==='clothes')return 1;if(d?.type==='accessory')return .2;return Number(d?.weight||0);}
function value(raw){const d=def(raw);return Number(d?.buyPrice??d?.sellPrice??0);}
function label(raw){return window.inventoryDisplayName?.(raw)||window.describeEquipment?.(raw)||def(raw)?.name||String(base(raw));}
function imagePath(raw,slot){const id=base(raw),d=def(raw);if(!id)return null;if(d?.type==='shield')return id==='bulwark_shield'?'images/kiteshield.png':'images/shield.png';if(d?.type==='helmet')return'id'&&`images/equipment/helmet/${id}.png`;if(d?.type==='weapon'){const map={sword:'images/sword.png',dagger:'images/dagger.png',axe:'images/axe.png',club:'images/club.png',spear:'images/spear.png',bow:'images/bow.png',torch:'images/torch.png',pickaxe:'images/pickaxe.png'};return map[id]||null;}if(d?.type==='armor'){const tier=Number(d.reduction||0)>=3?'heavy':Number(d.reduction||0)>=2?'medium':'light';return `images/equipment/armour/human/${tier}_front.webp`;}const sp=window.clothingSystem?.getItemSpec?.(id),src=sp?.layers?.[0]?.views?.front;return src||null;}
function physicalFor(p,id,slot){return p?.equippedInstances?.[slot]||window.physicalEquipment?.current?.(p,id)||null;}
function entries(p){window.physicalEquipment?.reconcile?.(p);const out=[],physical=p.physicalEquipment||[],used=new Set();for(const x of physical){out.push(x);used.add(x.instanceId);}const counts={};for(const raw of p.inventory||[]){const id=base(raw);if(!def(id))continue;counts[id]=(counts[id]||0)+1;}for(const [id,n] of Object.entries(counts)){const have=physical.filter(x=>x.itemId===id).length;for(let i=have;i<n;i++)out.push(id);}return out;}
function equip(raw,slot){const p=window.player,id=base(raw);if(!p||!id)return;if(window.equipmentIdentity?.isInstance(raw)&&window.physicalEquipment){window.physicalEquipment.reconcile(p);const normal=slotFor(raw);if(slot===normal){window.physicalEquipment.equip(raw.instanceId);state.picker=null;return;}}
 window.equipItem?.(id,slot==='offhand'&&def(raw)?.type==='weapon');if(window.equipmentIdentity?.isInstance(raw)){p.equippedInstances=p.equippedInstances||{};p.equippedInstances[slot]=raw;window.syncPlayerEntity?.();}state.picker=null;render();}
function itemImage(raw,slot){const path=imagePath(raw,slot),wrap=document.createElement('div');wrap.style.cssText='height:54px;display:flex;align-items:center;justify-content:center;';if(path){const img=document.createElement('img');img.src=`${path}?build=${encodeURIComponent(BUILD)}`;img.alt='';img.style.cssText='max-width:52px;max-height:52px;object-fit:contain;';img.onerror=()=>img.remove();wrap.appendChild(img);}else{const mark=document.createElement('span');mark.textContent='◇';mark.style.cssText='font-size:30px;color:#777;';wrap.appendChild(mark);}return wrap;}
function slotBox(p,s){const id=p.equipped?.[s.key],inst=id?physicalFor(p,id,s.key):null,raw=inst||id,b=document.createElement('button');b.type='button';b.style.cssText=`grid-area:${s.area};min-height:92px;padding:6px;border:1px solid #666;border-radius:7px;background:#262626;color:#eee;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;overflow:hidden;`;b.title=`Choose ${s.label.toLowerCase()}`;b.appendChild(itemImage(raw,s.key));const sl=document.createElement('span');sl.textContent=s.label;sl.style.cssText='font-size:.68em;color:#aaa;';const nm=document.createElement('span');nm.textContent=raw?label(raw):'Empty';nm.style.cssText='font-size:.76em;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;';b.append(sl,nm);b.onclick=()=>{state.picker=s.key;render();};return b;}
function picker(p,slot){const modal=document.createElement('div');modal.style.cssText='position:fixed;inset:0;background:#000b;z-index:10020;display:flex;align-items:flex-end;justify-content:center;';const panel=document.createElement('div');panel.style.cssText='background:#202020;border:1px solid #666;border-radius:12px 12px 0 0;width:min(680px,100%);max-height:72vh;overflow:auto;padding:12px;';const s=SLOT_DEFS.find(x=>x.key===slot);const head=document.createElement('div');head.style.cssText='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;';head.innerHTML=`<strong>${s?.label||slot}</strong>`;const close=document.createElement('button');close.textContent='Close';close.style.cssText='width:auto;padding:5px 9px;';close.onclick=()=>{state.picker=null;render();};head.appendChild(close);panel.appendChild(head);const none=document.createElement('button');none.textContent='Unequip / empty slot';none.style.cssText='width:100%;margin-bottom:8px;padding:9px;';none.onclick=()=>{window.unequipItem?.(slot);state.picker=null;};panel.appendChild(none);const choices=entries(p).filter(x=>compatible(x,slot,p));if(!choices.length){const e=document.createElement('p');e.textContent='Nothing compatible in the shared inventory.';panel.appendChild(e);}for(const raw of choices){const row=document.createElement('button');row.type='button';row.style.cssText='width:100%;display:grid;grid-template-columns:54px 1fr auto;gap:8px;align-items:center;text-align:left;padding:7px;margin:4px 0;background:#2d2d2d;color:#eee;border:1px solid #444;border-radius:6px;';row.appendChild(itemImage(raw,slot));const txt=document.createElement('span');txt.innerHTML=`<strong>${label(raw)}</strong><br><small>${weight(raw).toFixed(1)} wt · ${value(raw)}g</small>`;row.appendChild(txt);const use=document.createElement('span');use.textContent='Equip';row.appendChild(use);row.onclick=()=>equip(raw,slot);panel.appendChild(row);}modal.appendChild(panel);modal.onclick=e=>{if(e.target===modal){state.picker=null;render();}};document.body.appendChild(modal);}
function backpack(p,host){const section=document.createElement('section');section.style.cssText='margin-top:12px;border-top:1px solid #555;padding-top:10px;';const top=document.createElement('div');top.style.cssText='display:flex;gap:6px;flex-wrap:wrap;align-items:center;';const h=document.createElement('strong');h.textContent='Backpack';h.style.marginRight='auto';top.appendChild(h);const f=document.createElement('select');for(const [v,t] of [['all','All'],['weapon','Weapons'],['offhand','Off hand / shields'],['armor','Armour'],['helmet','Helmets'],['shirt','Tops'],['pants','Pants'],['accessory','Accessories']]){const o=document.createElement('option');o.value=v;o.textContent=t;f.appendChild(o);}f.value=state.filter;f.onchange=()=>{state.filter=f.value;render();};const sort=document.createElement('select');for(const [v,t] of [['name','Name'],['slot','Slot'],['weight','Weight'],['value','Value']]){const o=document.createElement('option');o.value=v;o.textContent=`Sort: ${t}`;sort.appendChild(o);}sort.value=state.sort;sort.onchange=()=>{state.sort=sort.value;render();};top.append(f,sort);section.appendChild(top);let xs=entries(p);if(state.filter!=='all')xs=xs.filter(x=>state.filter==='offhand'?compatible(x,'offhand',p):slotFor(x)===state.filter);const cmp={name:(a,b)=>label(a).localeCompare(label(b)),slot:(a,b)=>(slotFor(a)||'z').localeCompare(slotFor(b)||'z')||label(a).localeCompare(label(b)),weight:(a,b)=>weight(a)-weight(b)||label(a).localeCompare(label(b)),value:(a,b)=>value(b)-value(a)||label(a).localeCompare(label(b))}[state.sort];xs.sort(cmp);for(const raw of xs){const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:minmax(0,1fr) 58px 58px;gap:7px;padding:7px 2px;border-bottom:1px solid #383838;align-items:center;';const n=document.createElement('span');n.textContent=label(raw);const w=document.createElement('span');w.textContent=`${weight(raw).toFixed(1)} wt`;w.style.cssText='font-size:.78em;color:#aaa;text-align:right;';const v=document.createElement('span');v.textContent=`${value(raw)}g`;v.style.cssText='font-size:.78em;color:#aaa;text-align:right;';row.append(n,w,v);section.appendChild(row);}host.appendChild(section);}
function render(){document.querySelector('[data-equipment-slot-picker]')?.remove();const host=document.getElementById('inventory-content'),p=window.player;if(!host||!p)return;window.clothingSystem?.migrateLegacyEquipment?.(p);window.physicalEquipment?.reconcile?.(p);host.innerHTML='';host.dataset.equipmentRedesign='true';const gold=document.createElement('div');gold.textContent=`Gold: ${p.gold||0}`;gold.style.cssText='font-weight:bold;margin-bottom:8px;';host.appendChild(gold);const layout=document.createElement('div');layout.style.cssText='display:grid;grid-template-columns:1fr 1fr 1fr;grid-template-areas:". helmet ." "weapon armor offhand" "shirt shirt accessory" "pants pants pants" "bra bra bra" "underwear underwear underwear";gap:7px;';for(const s of SLOT_DEFS)layout.appendChild(slotBox(p,s));host.appendChild(layout);backpack(p,host);if(state.picker){picker(p,state.picker);const m=document.body.lastElementChild;if(m)m.dataset.equipmentSlotPicker='true';}}
function install(){if(typeof window.showInventoryScreen!=='function'||window.showInventoryScreen.__slotEquipmentUI)return false;window.showInventoryScreen=function(){render();};window.showInventoryScreen.__slotEquipmentUI=true;window.renderEquipmentInterface=render;return true;}
const timer=setInterval(()=>{if(install())clearInterval(timer);},50);window.addEventListener('load',install,{once:true});
})();
