// Per-equipped-item rendering visibility and weapon material colours.
(() => {
  'use strict';
  const BUILD='20260928-equipment-appearance-v1';
  const renderSlots=['weapon','offhand','armor','helmet','shirt','pants','bra','underwear'];
  const slotLabels={weapon:'Main hand',offhand:'Off hand',armor:'Armour',helmet:'Helmet',shirt:'Shirt / Dress',pants:'Pants',bra:'Bra',underwear:'Underwear'};
  const tintCache=new WeakMap();
  function ensure(e){if(!e)return;if(!e.equipmentVisibility||typeof e.equipmentVisibility!=='object')e.equipmentVisibility={};if(!e.equipmentColors||typeof e.equipmentColors!=='object')e.equipmentColors={};e.displayArmour=true;e.displayClothes=true;}
  function isSlotVisible(e,slot){ensure(e);return e?.equipmentVisibility?.[slot]!==false;}
  function setSlotVisible(e,slot,visible){if(!e||!renderSlots.includes(slot))return;ensure(e);e.equipmentVisibility[slot]=!!visible;}
  function weaponParts(itemId){const item=window.items?.[itemId];if(!item||item.type!=='weapon')return[];const id=String(itemId).toLowerCase();if(id.includes('bow')||id.includes('club')||id.includes('chair')||id.includes('torch'))return['wood'];if(id.includes('axe')||id.includes('pickaxe')||id.includes('spear')||id.includes('sword')||id.includes('dagger'))return['metal','wood'];return['metal'];}
  function defaultMaterial(part){return part==='wood'?{hue:30,saturation:68,value:55,opacity:1,unlocked:false}:{hue:210,saturation:8,value:72,opacity:1,unlocked:false};}
  function getWeaponMaterial(e,itemId,part){ensure(e);const item=e.equipmentColors[itemId]||(e.equipmentColors[itemId]={});const c=item[part]||(item[part]=defaultMaterial(part));if(c.opacity===undefined)c.opacity=1;if(c.unlocked===undefined)c.unlocked=false;return c;}
  function setWeaponMaterial(e,itemId,part,next){const prev=getWeaponMaterial(e,itemId,part);e.equipmentColors[itemId][part]={hue:Number(next.hue??prev.hue),saturation:Number(next.saturation??prev.saturation),value:Number(next.value??prev.value),opacity:Math.max(0,Math.min(1,Number(next.opacity??prev.opacity??1))),unlocked:!!(next.unlocked??prev.unlocked)};}
  function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4);}if(h<0)h+=360;return{h,s:max?d/max:0,v:max};}
  function hsvToRgb(h,s,v){h=((h%360)+360)%360;const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let a=[0,0,0];if(h<60)a=[c,x,0];else if(h<120)a=[x,c,0];else if(h<180)a=[0,c,x];else if(h<240)a=[0,x,c];else if(h<300)a=[x,0,c];else a=[c,0,x];return a.map(n=>Math.round((n+m)*255));}
  function woodPixel(r,g,b,a){if(!a)return false;const hsv=rgbToHsv(r,g,b);return hsv.s>.16&&hsv.h>=8&&hsv.h<=75&&r>=b*1.05;}
  function resolveWeaponImage(e,itemId,image){if(!image||!itemId||!weaponParts(itemId).length)return image;const w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;if(!w||!h)return image;const parts=weaponParts(itemId),settings=parts.map(p=>[p,getWeaponMaterial(e,itemId,p)]),key=settings.map(([p,c])=>`${p}:${c.hue}:${c.saturation}:${c.value}:${c.opacity}:${c.unlocked?1:0}`).join('|');let per=tintCache.get(image);if(!per){per=new Map();tintCache.set(image,per);}if(per.has(key))return per.get(key);const out=document.createElement('canvas');out.width=w;out.height=h;const ctx=out.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,w,h);const d=ctx.getImageData(0,0,w,h),px=d.data;for(let i=0;i<px.length;i+=4){if(!px[i+3])continue;let part=parts[0];if(parts.includes('metal')&&parts.includes('wood'))part=woodPixel(px[i],px[i+1],px[i+2],px[i+3])?'wood':'metal';const c=getWeaponMaterial(e,itemId,part),src=rgbToHsv(px[i],px[i+1],px[i+2]),hue=c.unlocked?c.hue:(part==='wood'?Math.max(15,Math.min(60,c.hue)):210),sat=c.unlocked?Math.max(.10,Math.min(.95,c.saturation/100)):(part==='wood'?.68:.08),baseV=Math.max(.04,Math.min(1,c.value/100)),v=Math.max(.03,Math.min(1,baseV+(src.v-.5)*.58)),rgb=hsvToRgb(hue,sat,v);px[i]=rgb[0];px[i+1]=rgb[1];px[i+2]=rgb[2];px[i+3]=Math.round(px[i+3]*Math.max(0,Math.min(1,c.opacity??1)));}ctx.putImageData(d,0,0);per.set(key,out);return out;}
  function syncCharacter(source){if(!source)return;ensure(source);for(const target of [...(window.party||[]),...(window.entities||[])]){if(!target||target===source||target.name!==source.name)continue;target.equipmentVisibility=JSON.parse(JSON.stringify(source.equipmentVisibility||{}));target.equipmentColors=JSON.parse(JSON.stringify(source.equipmentColors||{}));target.displayArmour=true;target.displayClothes=true;}}
  function redraw(e){syncCharacter(e);window.drawMap?.();window.renderEntities?.();window.refreshDirectionalTurnPortraits?.();}
  window.equipmentAppearanceSystem={build:BUILD,renderSlots,slotLabels,ensure,isSlotVisible,setSlotVisible,weaponParts,getWeaponMaterial,setWeaponMaterial,resolveWeaponImage,syncCharacter,redraw};
})();
