// expeditionSystem.js — shared expedition logistics, ammunition, weather and camping.
(function(root){
'use strict';
const C={baseCarry:40,treeCarry:2,strongBack:15,mountCarry:40,companionCarry:20,bedrollWarmth:8,tentWarmth:3,tentSpaces:4,arrowCraft:20,starterArrows:30};
let installed=false,lastCombat=false,lastSleep=false,lastShotMs=0,lastEncumbranceSignature=null,pendingShots=Object.create(null);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const inv=()=>Array.isArray(root.partyInventory)?root.partyInventory:(Array.isArray(root.player?.inventory)?root.player.inventory:(root.partyInventory=[]));
const count=(id,a=inv())=>Array.isArray(a)?a.reduce((n,x)=>n+(x===id),0):0;
function add(id,n=1,a=inv()){n=Math.max(0,Math.floor(Number(n)||0));for(let i=0;i<n;i++)a.push(id);return n;}
function remove(id,n=1,a=inv()){n=Math.max(0,Math.floor(Number(n)||0));let r=0;for(let i=a.length-1;i>=0&&r<n;i--)if(a[i]===id){a.splice(i,1);r++;}return r;}
function weight(id){const x=root.items?.[id];if(!x)return 1;if(x.weight!==undefined)return Number(x.weight)||0;if(x.type==='quest_item')return 0;if(x.type==='ammo')return .05;if(x.type==='camping')return 3;if(['armor','shield','helmet'].includes(x.type))return(x.reduction||1)*6;if(x.type==='weapon')return x.subType==='ranged'?2:x.subType==='tool'?1:3;if(['food','consumable'].includes(x.type))return .5;if(x.type==='resource')return 2;return 1;}
const recordFor=e=>(root.party||[]).find(p=>p===e||(p.name&&p.name===e?.name))||null;
const equippedIds=e=>Object.values(e?.equipped||{}).filter(id=>typeof id==='string'&&root.items?.[id]);
const equippedWeight=e=>equippedIds(e).reduce((s,id)=>s+weight(id),0);
function treeRanks(e,tree){let n=0;for(const[id,r]of Object.entries(e?.skills||{}))if(root.skills?.[id]?.tree===tree)n+=Math.max(0,Number(r)||0);return n;}
function memberCapacity(e){const p=recordFor(e)||e;let n=C.baseCarry+(treeRanks(p,'strength')+treeRanks(p,'endurance'))*C.treeCarry+(Number(p?.skills?.strong_back)||0)*C.strongBack;for(const id of equippedIds(p))n+=Number(root.items?.[id]?.carryBonus)||0;return n;}
function carriers(){const out=[],seen=new Set(),es=root.entities||[];for(const p of root.party||[]){const re=es.find(e=>e.side==='player'&&e.name===p.name);if(re&&!re.alive)continue;const e=re||p,key=e.id||e.name||`party-${out.length}`;if(seen.has(key))continue;seen.add(key);out.push({key,entity:e,source:p,name:e.name||'Party member',capacity:memberCapacity(p),equippedWeight:equippedWeight(p)});}for(let i=0;i<es.length;i++){const e=es[i];if(!e?.alive||e.side!=='player')continue;const mount=(Number(e.mountSize)||0)>0,comp=!!e.isCompanion;if(!mount&&!comp)continue;const key=e.id||`animal-${i}`;if(seen.has(key))continue;seen.add(key);out.push({key,entity:e,source:e,name:e.name||(mount?'Mount':'Companion'),capacity:mount?C.mountCarry:C.companionCarry,equippedWeight:equippedWeight(e)});}return out.filter(x=>x.capacity>0);}
function cargoWeight(cs){const a=[...inv()];for(const c of cs)for(const id of equippedIds(c.source)){const i=a.indexOf(id);if(i>=0)a.splice(i,1);}return a.reduce((s,id)=>s+weight(id),0);}
function allocate(cs,cargo){const a=(cs||[]).map(x=>({...x,allocatedSharedWeight:0}));cargo=Math.max(0,Number(cargo)||0);if(!a.length)return a;const need=r=>a.reduce((s,x)=>s+Math.max(0,r*x.capacity-x.equippedWeight),0);let lo=0,hi=Math.max(1,...a.map(x=>x.equippedWeight/Math.max(.001,x.capacity)));while(need(hi)<cargo)hi*=2;for(let i=0;i<48;i++){const m=(lo+hi)/2;if(need(m)<cargo)lo=m;else hi=m;}for(const x of a){x.allocatedSharedWeight=Math.max(0,hi*x.capacity-x.equippedWeight);x.totalWeight=x.equippedWeight+x.allocatedSharedWeight;x.burden=x.totalWeight/Math.max(.001,x.capacity);}return a;}
function carryState(){const cs=carriers(),cargo=cargoWeight(cs),rows=allocate(cs,cargo);return{carriers:rows,cargoWeight:cargo,totalWeight:rows.length?rows.reduce((s,x)=>s+x.totalWeight,0):cargo,totalCapacity:rows.reduce((s,x)=>s+x.capacity,0)};}
function carrierFor(e,s=carryState()){if(!e)return null;const rider=e.rider||null;return s.carriers.find(c=>c.entity===e||c.source===e||c.entity===rider||c.source===rider||(c.entity?.id&&c.entity.id===e.id)||c.name===e.name)||null;}
function rawBurden(b){b=Math.max(0,Number(b)||0);if(b<=1)return 1;if(b<=1.15)return 1+(b-1);if(b<=1.35)return 1.15+(b-1.15)*1.5;if(b<=1.6)return 1.45+(b-1.35)*2.2;if(b<=2)return 2+(b-1.6)*2.5;return Math.min(5,3+(b-2)*1.5);}
function quartermasterFactor(){const q=Math.max(0,...(root.party||[]).map(p=>Number(p.skills?.quartermaster)||0));return 1-Math.min(2,q)*.25;}
function burdenMoveMult(b){return 1+(rawBurden(b)-1)*quartermasterFactor();}
function encumbranceState(b){b=Math.max(0,Number(b)||0);const moveMult=burdenMoveMult(b),slowerPct=Math.max(0,Math.round((1-1/Math.max(1,moveMult))*100));let key='unencumbered',label='Unencumbered';if(b>1.6){key='overloaded';label='Overloaded';}else if(b>1.35){key='severely_encumbered';label='Severely encumbered';}else if(b>1.15){key='heavily_encumbered';label='Heavily encumbered';}else if(b>1.000001){key='encumbered';label='Encumbered';}return{key,label,burden:b,burdenPct:Math.round(b*100),moveMult,slowerPct};}
function encumbranceMult(e){const s=carryState(),c=carrierFor(e,s),b=c?c.burden:Math.max(0,...s.carriers.map(x=>x.burden));return burdenMoveMult(b);}
function fatigue(e){const h=(Math.max(0,Number(e?.awakeSeconds)||0))/3600;if(h<16)return{key:'rested',label:'Rested',moveMult:1};if(h<20)return{key:'tired',label:'Tired',moveMult:1.05};if(h<28)return{key:'exhausted',label:'Exhausted',moveMult:1.15};return{key:'severely_exhausted',label:'Severely exhausted',moveMult:1.30};}
const hash01=(a,b,c)=>{const x=Math.sin(a*12.9898+b*78.233+c*37.719)*43758.5453;return x-Math.floor(x);};
function elevation(q,r){q=Number(q)||0;r=Number(r)||0;const broad=(Math.sin(q*.035)+Math.cos(r*.031)+Math.sin((q+r)*.018))/3;let m=Math.max(0,220+broad*320),t=root.getTerrainAt?.(q,r);if(t?.name==='Mountain')m+=650;if(t?.elevated)m+=120;return m;}
function indoors(hex){if(root.findInteriorRegion?.(hex))return true;const n=root.getTerrainAt?.(hex?.q,hex?.r)?.name;return n==='Wood Floor'||n==='Cave Floor';}
function ambient(hex){hex=hex||root.player?.hex||{q:0,r:0};const ws=Number(root.worldSeconds)||0,day=Math.floor(ws/86400)%360,hour=((ws%86400)+86400)%86400/3600;const seasonal=13+8*Math.cos(2*Math.PI*(day-165)/360),diurnal=5*Math.cos(2*Math.PI*(hour-15)/24),variation=(hash01(Math.floor(hex.q/6),Math.floor(hex.r/6),Math.floor(ws/86400))-.5)*6;const tn=root.getTerrainAt?.(hex.q,hex.r)?.name||'';const biome=tn==='Mountain'?-2:tn==='Forest'?-1:tn==='Sand'?3:tn==='Swamp'?1:0;let t=seasonal+diurnal+variation+biome-elevation(hex.q,hex.r)*.0065;if(indoors(hex))t=18+(t-18)*.35;return t;}
function sun(){const l=Number(root.getLightLevel?.())||0;return clamp((l-.2)/.8,0,1);}
function shaded(hex){const n=root.getTerrainAt?.(hex.q,hex.r)?.name;if(n==='Forest'||n==='Foliage')return true;const o=root.tileObjects?.[`${hex.q},${hex.r}`];return !!o&&['tree','timber_tree','fruit_tree'].includes(o.type);}
function fireHeat(hex){let h=0;for(const[k,o]of Object.entries(root.tileObjects||{})){if(!o||o.lit===false||!['fireplace','campfire','fire'].includes(o.type))continue;const[q,r]=k.split(',').map(Number),d=root.distance?root.distance(hex,{q,r}):Math.hypot(hex.q-q,hex.r-r);if(d<=4)h=Math.max(h,12/Math.max(1,d*d));}for(const e of root.entities||[]){if(!e?.alive||!e.hex)continue;const ids=equippedIds(e);if(ids.some(id=>root.items?.[id]?.lightRadius&&/torch/i.test(root.items[id].name||id))){const d=root.distance?root.distance(hex,e.hex):Math.hypot(hex.q-e.hex.q,hex.r-e.hex.r);if(d<=2)h=Math.max(h,2/Math.max(1,d));}}return h;}
function effectiveTemp(e){const hex=e?.hex||root.player?.hex||{q:0,r:0};let t=ambient(hex);if(!indoors(hex)){let solar=6*sun();if(shaded(hex))solar*=.2;t+=solar;}t+=fireHeat(hex);if(root.isSleeping&&e){if(e._sleepBedroll)t+=C.bedrollWarmth;if(e._sleepTent)t+=C.tentWarmth;}return t;}
function gearThermal(e){let ins=.4,hot=0;for(const id of equippedIds(e)){const x=root.items?.[id];ins+=Number(x?.insulation)||0;hot+=Number(x?.hotWeatherPenalty)||0;}return{ins,hot};}
function instantThermal(e){const t=effectiveTemp(e),g=gearThermal(e);return{temp:t,cold:Math.max(0,16-t-g.ins*4),hot:Math.max(0,t-27+g.hot+g.ins*.7)};}
function thermalState(e){const s=Number(e?.thermalStress)||0,x=instantThermal(e);if(s<=-80||x.cold>=14)return{key:'dangerously_cold',label:'Dangerously cold',moveMult:1.25};if(s<=-45||x.cold>=8)return{key:'cold',label:'Cold',moveMult:1.12};if(s<=-15||x.cold>=3)return{key:'chilly',label:'Chilly',moveMult:1.04};if(s>=80||x.hot>=14)return{key:'dangerously_hot',label:'Dangerously hot',moveMult:1.25};if(s>=45||x.hot>=8)return{key:'hot',label:'Hot',moveMult:1.12};if(s>=15||x.hot>=3)return{key:'warm',label:'Warm',moveMult:1.04};return{key:'comfortable',label:'Comfortable',moveMult:1};}
function tickThermal(dt){dt=Math.max(0,Number(dt)||0);if(!dt)return;for(const e of root.entities||[]){if(!e?.alive||e.side!=='player'||e.rider||!e.hex)continue;const x=instantThermal(e);let s=Number(e.thermalStress)||0;if(x.cold>0)s-=x.cold/8*dt/60;else if(x.hot>0)s+=x.hot/8*dt/60;else{s>0?s=Math.max(0,s-1.5*dt/60):s=Math.min(0,s+1.5*dt/60);}e.thermalStress=clamp(s,-100,100);if(Math.abs(e.thermalStress)>=90){e._thermalDamageSeconds=(e._thermalDamageSeconds||0)+dt;while(e._thermalDamageSeconds>=300){e._thermalDamageSeconds-=300;e.hp=Math.max(-Math.ceil((e.maxHp||1)*.5),(Number(e.hp)||0)-1);root.showMessage?.(`${e.name} is suffering from ${e.thermalStress<0?'severe cold':'severe heat'}.`);}}else e._thermalDamageSeconds=Math.max(0,(e._thermalDamageSeconds||0)-dt*.5);}}
function sleepers(){return(root.entities||[]).filter(e=>e.alive&&e.side==='player'&&!e.rider&&!['Wolf','Horse'].includes(e.name));}
function prepareSleep(){const a=sleepers();if(!a.length)return;const outdoor=!indoors(a[0].hex),beds=count('bedroll'),spaces=outdoor?count('tent')*C.tentSpaces:0,order=[...a].sort((x,y)=>effectiveTemp(x)-effectiveTemp(y));for(const e of a){e._sleepBedroll=false;e._sleepTent=false;e._watchShareSeconds=0;}order.slice(0,beds).forEach(e=>e._sleepBedroll=true);order.slice(0,spaces).forEach(e=>e._sleepTent=true);root._expeditionSleepStartedAt=Number(root.worldSeconds)||0;root._expeditionWatchRotation=a.length>=3;const first=a.find(e=>e.onGuard);root._expeditionWatchOrder=first?[first,...a.filter(e=>e!==first)]:a;if(root.showMessage){const p=[];if(beds)p.push(`${Math.min(beds,a.length)}/${a.length} bedrolls`);if(outdoor&&spaces)p.push(`tent shelter for ${Math.min(spaces,a.length)}/${a.length}`);if(root._expeditionWatchRotation)p.push('a rotating watch');if(p.length)root.showMessage(`Camp: ${p.join(', ')}.`);}}
function tickWatch(dt){if(!root.isSleeping||!root._expeditionWatchRotation)return;const a=sleepers();if(a.length<3)return;const order=(root._expeditionWatchOrder||[]).filter(e=>a.includes(e));for(const e of a)if(!order.includes(e))order.push(e);const elapsed=Math.max(0,(Number(root.worldSeconds)||0)-(Number(root._expeditionSleepStartedAt)||0)),len=10*3600/a.length,guard=order[Math.floor(elapsed/Math.max(1,len))%a.length];for(const e of a){e.onGuard=e===guard;if(e===guard)e._watchShareSeconds=(e._watchShareSeconds||0)+Math.max(0,Number(dt)||0);}}
function finishSleep(natural){const a=sleepers();if(natural)for(const e of a){const wd=Math.min(7200,(e._watchShareSeconds||0)*.25),ts=Math.abs(Number(e.thermalStress)||0),td=ts>=45?7200:ts>=20?3600:0;e.awakeSeconds=Math.max(Number(e.awakeSeconds)||0,wd+td);}for(const e of a){delete e._sleepBedroll;delete e._sleepTent;delete e._watchShareSeconds;e.onGuard=false;}root._expeditionWatchRotation=false;root._expeditionWatchOrder=null;}
function configure(){if(!root.items)return;root.items.basic_arrow??={id:'basic_arrow',name:'Basic Arrow',type:'ammo',ammoClass:'arrow',weight:.05,buyPrice:1,recoveryChance:.8,description:'A plain wood-and-iron arrow. Archers draw from the party\'s shared supply.'};root.items.bedroll??={id:'bedroll',name:'Bedroll',type:'camping',weight:3,buyPrice:12,sleepWarmth:C.bedrollWarmth,description:'Blankets and bedding rolled for travel. One keeps one sleeper off the cold ground.'};root.items.tent??={id:'tent',name:'Tent',type:'camping',weight:9,buyPrice:30,shelterCapacity:C.tentSpaces,description:'A practical travelling tent with room for four sleepers.'};for(const x of Object.values(root.items)){if(x?.type==='weapon'&&x.subType==='ranged'&&/bow/i.test(x.name||x.id||''))x.ammoClass='arrow';if(x?.type==='clothes'&&x.insulation===undefined)x.insulation=Math.max(.2,(Number(x.weight)||1)*.45);}Object.assign(root.items.light_armor||{},{insulation:.6,hotWeatherPenalty:1});Object.assign(root.items.medium_armor||{},{insulation:.9,hotWeatherPenalty:2.4});Object.assign(root.items.heavy_armor||{},{insulation:1,hotWeatherPenalty:4});Object.assign(root.items.moonlit_armor||{},{insulation:.9,hotWeatherPenalty:2.4});if(root.skills?.strong_back)root.skills.strong_back.description='Adds 15 to this character\'s carrying capacity per rank. Every rank spent in Strength or Endurance also adds a small amount of capacity.';if(root.skills?.quartermaster)root.skills.quartermaster.description='Packs the party efficiently: reduces overload movement penalties by 25% per rank, without making extreme overloading free.';}
const weapon=(e,off=false)=>root.items?.[e?.equipped?.[off?'offhand':'weapon']]||null;
function ammoArray(e){return e?.side==='player'?inv():(e.inventory||(e.inventory=[]));}
function ammoTypes(e,cls){const c={};for(const id of ammoArray(e)){const x=root.items?.[id];if(x?.type==='ammo'&&x.ammoClass===cls)c[id]=(c[id]||0)+1;}return Object.keys(c).sort((a,b)=>(root.items[a]?.buyPrice||0)-(root.items[b]?.buyPrice||0)||String(root.items[a]?.name||a).localeCompare(String(root.items[b]?.name||b)));}
function setAmmo(e,id){if(!e)return;e.preferredAmmoId=id||null;const p=recordFor(e);if(p&&p!==e)p.preferredAmmoId=e.preferredAmmoId;}
function seedEnemyAmmo(e){if(!e||e.side==='player'||e._expeditionAmmoSeeded)return;const cls=weapon(e)?.ammoClass;if(!cls)return;e._expeditionAmmoSeeded=true;if(ammoTypes(e,cls).length)return;if(cls==='arrow')add('basic_arrow',12+Math.floor(hash01(e.hex?.q||0,e.hex?.r||0,(e.name||'').length)*9),ammoArray(e));}
function chooseAmmo(e,cls){const a=ammoTypes(e,cls);if(!a.length)return null;const p=recordFor(e)||e;if(p.preferredAmmoId&&a.includes(p.preferredAmmoId))return p.preferredAmmoId;if(p.preferredAmmoId)setAmmo(e,null);return a[0];}
function ensureAmmo(e,off=false,quiet=false){const cls=weapon(e,off)?.ammoClass;if(!cls)return{required:false,ammoId:null};seedEnemyAmmo(e);const id=chooseAmmo(e,cls);if(!id&&!quiet&&e?.side==='player')root.showMessage?.(`${e.name} has no ${cls==='arrow'?'arrows':'ammunition'}.`);return{required:true,ammoId:id};}
function recordShot(e,id){if(!id)return;const k=`${e?.side==='player'?'player':'enemy'}:${id}`;pendingShots[k]=(pendingShots[k]||0)+1;lastShotMs=Date.now();}
function recoverShots(){const entries=Object.entries(pendingShots);if(!entries.length)return;pendingShots=Object.create(null);const msg=[];for(const[k,n]of entries){const i=k.indexOf(':'),side=k.slice(0,i),id=k.slice(i+1),x=root.items?.[id],chance=clamp((Number(x?.recoveryChance)||0)*(side==='player'?1:.5),0,1);let r=0;for(let j=0;j<n;j++)if(Math.random()<chance)r++;if(r){add(id,r);msg.push(`${r} ${x.name}${r===1?'':'s'}`);}}if(msg.length)root.showMessage?.(`Recovered after the fight: ${msg.join(', ')}.`);}
function craftArrows(){if(count('wood')<1||count('ore_iron')<1){root.showMessage?.('You need 1 Timber and 1 Iron Ore to make 20 Basic Arrows.');return false;}remove('wood');remove('ore_iron');add('basic_arrow',C.arrowCraft);root.showMessage?.(`You make ${C.arrowCraft} Basic Arrows.`);if(root.document?.getElementById('inventory-modal')?.style.display==='block')root.showInventoryScreen?.();return true;}
function encumbranceRows(s){return(s?.carriers||[]).map(x=>({carrier:x,status:encumbranceState(x.burden)}));}
function reportEncumbrance(s){const over=encumbranceRows(s).filter(x=>x.status.key!=='unencumbered'),sig=over.map(x=>`${x.carrier.key}:${x.status.key}`).join('|');if(sig===lastEncumbranceSignature)return;if(over.length){const details=over.map(x=>`${x.carrier.name} ${x.status.label.toLowerCase()} (${x.status.burdenPct}% load, ~${x.status.slowerPct}% slower)`).join('; ');root.showMessage?.(`Encumbrance: ${details}. Reduce carried weight to move normally.`);}else if(lastEncumbranceSignature)root.showMessage?.('Encumbrance cleared: everyone is within carrying capacity.');lastEncumbranceSignature=sig;}
function panel(){const d=root.document,c=d?.getElementById('inventory-content');if(!c||d.getElementById('expedition-inventory-panel'))return;const s=carryState(),rows=encumbranceRows(s),over=rows.filter(x=>x.status.key!=='unencumbered'),max=Math.max(0,...s.carriers.map(x=>x.burden)),e=(root.entities||[]).find(x=>x.alive&&x.side==='player'&&x.name===root.player?.name)||root.player,t=e?thermalState(e):null,temp=e?effectiveTemp(e):null,f=e?fatigue(e):null,p=d.createElement('div'),warning=over.length?`<div id="encumbrance-warning" style="margin:8px 0;padding:8px;border:1px solid #ffb74d;background:rgba(255,183,77,.12);color:#ffe0b2"><strong>⚠ ENCUMBERED</strong><br>${over.map(x=>x.carrier.name).join(', ')} ${over.length===1?'is':'are'} over carrying capacity. Movement is slowed until the load is reduced.</div>`:'';p.id='expedition-inventory-panel';p.style.cssText='margin-top:16px;padding-top:12px;border-top:1px solid #555;';p.innerHTML=`<h3 style="margin-bottom:6px">Expedition</h3>${warning}<div><strong>Carried:</strong> ${s.totalWeight.toFixed(1)} / ${s.totalCapacity.toFixed(0)} capacity · highest burden ${Math.round(max*100)}%</div>${rows.map(({carrier:x,status})=>`<div style="font-size:.82em;color:${status.key==='unencumbered'?'#bbb':'#ffcc80'};font-weight:${status.key==='unencumbered'?'normal':'700'}">${status.key==='unencumbered'?'✓':'⚠'} ${x.name}: ${x.totalWeight.toFixed(1)}/${x.capacity.toFixed(0)} (${status.burdenPct}%) — ${status.label}${status.slowerPct?` · ~${status.slowerPct}% slower`:''}</div>`).join('')}<div style="margin-top:8px"><strong>Basic Arrows:</strong> ${count('basic_arrow')} · <strong>Bedrolls:</strong> ${count('bedroll')} · <strong>Tents:</strong> ${count('tent')}</div>${t?`<div><strong>Conditions:</strong> ${temp.toFixed(1)}°C effective · ${t.label} · ${f.label}</div>`:''}<button id="craft-basic-arrows-btn" style="margin-top:8px">Craft 20 Basic Arrows (1 Timber + 1 Iron Ore)</button><div id="ammo-preference-row" style="margin-top:8px"></div>`;c.appendChild(p);d.getElementById('craft-basic-arrows-btn').onclick=craftArrows;const row=d.getElementById('ammo-preference-row');if(e&&row){const types=Object.values(root.items||{}).filter(x=>x?.type==='ammo'&&x.ammoClass==='arrow'&&count(x.id)>0).sort((a,b)=>(a.buyPrice||0)-(b.buyPrice||0));if(types.length){const sel=d.createElement('select');sel.innerHTML='<option value="">Arrows: Auto (cheapest available)</option>'+types.map(x=>`<option value="${x.id}">${x.name} × ${count(x.id)}</option>`).join('');const pref=(recordFor(e)||e).preferredAmmoId;sel.value=pref&&types.some(x=>x.id===pref)?pref:'';sel.onchange=()=>setAmmo(e,sel.value||null);row.appendChild(sel);}}}
function hud(){const d=root.document,a=d?.getElementById('world-time-display');if(!a||!root.player)return;let h=d.getElementById('expedition-status');if(!h){h=d.createElement('div');h.id='expedition-status';h.style.cssText='font-size:.68em;color:#bbb;white-space:nowrap;';a.insertAdjacentElement('afterend',h);}const s=carryState(),rows=encumbranceRows(s),over=rows.filter(x=>x.status.key!=='unencumbered'),e=(root.entities||[]).find(x=>x.alive&&x.side==='player'&&x.name===root.player?.name)||root.player,t=thermalState(e);reportEncumbrance(s);if(over.length){const worst=over.reduce((a,b)=>a.status.burden>=b.status.burden?a:b),label=over.length===1?`${worst.carrier.name}: ${worst.status.label}`:`PARTY ENCUMBERED (${over.length}) · worst ${worst.carrier.name}`;h.style.color='#ffb74d';h.style.fontWeight='700';h.textContent=`⚠ ${label} · ${worst.status.burdenPct}% load · ~${worst.status.slowerPct}% slower · ${effectiveTemp(e).toFixed(0)}°C ${t.label} · ${fatigue(e).label}`;}else{const max=Math.max(0,...s.carriers.map(x=>x.burden));h.style.color='#bbb';h.style.fontWeight='normal';h.textContent=`Load ${Math.round(max*100)}% · ${effectiveTemp(e).toFixed(0)}°C ${t.label} · ${fatigue(e).label}`;}}
function wrap(){if(root.getMoveCostMult&&!root.getMoveCostMult._expedition){const old=root.getMoveCostMult,w=function(q,r,e){const prev=root._encumbranceEntityContext;root._encumbranceEntityContext=e;let m;try{m=old(q,r,e);}finally{root._encumbranceEntityContext=prev;}if(e&&(e.side==='player'||e.rider?.side==='player'))m*=fatigue(e.rider||e).moveMult*thermalState(e.rider||e).moveMult;return m;};w._expedition=true;root.getMoveCostMult=w;}
if(root.tryAttack&&!root.tryAttack._expedition){const old=root.tryAttack,w=function(a,t,feint=false,off=false,...rest){if(!feint){const x=ensureAmmo(a,off);if(x.required&&!x.ammoId){if(a?.side!=='player'){const melee=(a.inventory||[]).find(id=>root.items?.[id]?.type==='weapon'&&root.items[id].subType!=='ranged');if(melee){a.equipped.weapon=melee;return false;}}return false;}}return old(a,t,feint,off,...rest);};w._expedition=true;root.tryAttack=w;}
if(root.resolveAttack&&!root.resolveAttack._expedition){const old=root.resolveAttack,w=function(a,t,feint,off=false,...rest){if(!feint){const x=ensureAmmo(a,off,true);if(x.required){if(!x.ammoId||remove(x.ammoId,1,ammoArray(a))!==1)return false;recordShot(a,x.ammoId);}}return old(a,t,feint,off,...rest);};w._expedition=true;root.resolveAttack=w;}
if(root.updateTime&&!root.updateTime._expedition){const old=root.updateTime,w=function(dt){const r=old(dt);tickWatch(dt);tickThermal(dt);for(const e of root.entities||[])seedEnemyAmmo(e);return r;};w._expedition=true;root.updateTime=w;}
if(root.toggleSleep&&!root.toggleSleep._expedition){const old=root.toggleSleep,w=function(...a){const was=!!root.isSleeping,r=old(...a);if(!was&&root.isSleeping)prepareSleep();else if(was&&!root.isSleeping)finishSleep(false);return r;};w._expedition=true;root.toggleSleep=w;}
if(root.triggerSleepAmbush&&!root.triggerSleepAmbush._expedition){const old=root.triggerSleepAmbush,w=function(...a){tickWatch(0);return old(...a);};w._expedition=true;root.triggerSleepAmbush=w;}
if(root.updateSleepButton&&!root.updateSleepButton._expedition){const old=root.updateSleepButton,w=function(...a){const r=old(...a);if(lastSleep&&!root.isSleeping&&!root._resumeSleepAfterCombat){const a2=sleepers(),natural=a2.length>0&&a2.every(e=>!e.sleepRemainingSeconds||e.sleepRemainingSeconds<=0);finishSleep(natural);}lastSleep=!!root.isSleeping;return r;};w._expedition=true;root.updateSleepButton=w;}
if(root.showInventoryScreen&&!root.showInventoryScreen._expedition){const old=root.showInventoryScreen,w=function(...a){const r=old(...a);panel();return r;};w._expedition=true;root.showInventoryScreen=w;}
if(root.wireSharedInventory&&!root.wireSharedInventory._expedition){const old=root.wireSharedInventory,w=function(e,o={}){const own=Array.isArray(e?.inventory)?[...e.inventory]:[],r=old(e,o);if(o.merge!==false&&e&&!e._starterAmmoGranted&&own.some(id=>root.items?.[id]?.ammoClass==='arrow')){add('basic_arrow',C.starterArrows);e._starterAmmoGranted=true;}return r;};w._expedition=true;root.wireSharedInventory=w;}}
function install(){if(installed)return;installed=true;configure();root.getItemWeight=weight;root.getPartyCarryWeight=()=>carryState().totalWeight;root.getPartyCarryCapacity=()=>carryState().totalCapacity;root.isPartyOverencumbered=()=>carryState().carriers.some(x=>x.burden>1.000001);root.getEncumbranceMoveMult=()=>encumbranceMult(root._encumbranceEntityContext);root.getEncumbranceState=encumbranceState;root.countPartyItem=count;root.addPartyItem=add;root.removePartyItem=remove;root.getPartyCarryState=carryState;root.getClimateElevation=elevation;root.getAmbientTemperature=ambient;root.getEffectiveTemperature=effectiveTemp;root.getThermalState=thermalState;root.getFatigueState=fatigue;root.setPreferredAmmo=setAmmo;root.craftBasicArrows=craftArrows;wrap();lastCombat=!!root.isInCombat;lastSleep=!!root.isSleeping;root.setInterval?.(()=>{wrap();configure();const now=!!root.isInCombat;if(lastCombat&&!now)recoverShots();lastCombat=now;if(!now&&Object.keys(pendingShots).length&&Date.now()-lastShotMs>2000)recoverShots();hud();},750);}
const api={install,configureStaticData:configure,countPartyItem:count,addPartyItem:add,removePartyItem:remove,getItemWeight:weight,allocateSharedCargo:allocate,rawBurdenMoveMultiplier:rawBurden,getEncumbranceState:encumbranceState,getCarryState:carryState,getClimateElevation:elevation,getAmbientTemperature:ambient,getEffectiveTemperature:effectiveTemp,getFatigueState:fatigue,craftBasicArrows:craftArrows};
root.expeditionSystem=api;configure();if(root.document){if(root.document.readyState==='loading')root.document.addEventListener('DOMContentLoaded',install,{once:true});else install();}if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);