// Player voice, party expertise, companion interjections and deferred private conversations.
(() => {
'use strict';
const root=typeof window!=='undefined'?window:globalThis, BUILD='20261001-party-conversation-dynamics-v1', MINUTE=60;
const PROFILES={
 'Wren Talbot':{public:.68,whisper:.14,defer:.18},'Ser Aldric Thorne':{public:.56,whisper:.12,defer:.32},
 'Mirabel Quill':{public:.38,whisper:.43,defer:.19},'Fenn Oakheart':{public:.14,whisper:.20,defer:.66},
 'Reyna Fletcher':{public:.14,whisper:.68,defer:.18},'Brother Alden':{public:.10,whisper:.16,defer:.74}
};
const QUEEN_TAGS={public_audit:['accountable_authority','procedural','transparency'],emergency_seizure:['centralising','expedient','security_first'],brokered_limits:['pluralism','pragmatic','restrained_power'],equal_law:['individual_responsibility','proportionality','restrained_power'],security_zones:['pragmatic','security_first','discretion'],collective_penalties:['collective_punishment','hierarchical','security_first'],charter_review:['accountable_authority','transparency','restrained_power'],narrow_seals:['discretion','pragmatic','procedural'],royal_secrets:['secrecy','centralising','hierarchical'],queen_decides:['delegates_judgement']};
const QUEEN_REACTIONS={
 emergency_seizure:[
  {companion:'Ser Aldric Thorne',mergeKey:'seraphine:emergency_power',urgency:2,publicText:'Your Majesty, emergency authority should still answer to law. If the seizures are necessary, record what was taken and why.',deferredText:'Aldric lowers his voice. “The seizure may work. What worries me is how easily necessity becomes precedent.”'},
  {companion:'Reyna Fletcher',mergeKey:'seraphine:emergency_power',urgency:1,whisperText:'Fast and effective. Also exactly the sort of power nobody gives back willingly.',deferredText:'Reyna glances back toward the palace. “That was efficient. Efficiency is not the same thing as safety.”'}],
 collective_penalties:[
  {companion:'Wren Talbot',mergeKey:'seraphine:collective_punishment',urgency:3,publicText:'No. Punish the people who hid raiders. Do not make everyone nearby guilty because finding the right person is harder.',deferredText:'Wren waits until nobody else is close. “If guilt belongs to a village instead of a person, power never has to prove anything.”'},
  {companion:'Reyna Fletcher',mergeKey:'seraphine:collective_punishment',urgency:2,whisperText:'This will buy quiet and destroy informants. Frightened communities stop telling patrols what they know.',deferredText:'Reyna says quietly, “Collective penalties make intelligence worse. Everyone learns that speaking to us can punish their neighbours.”'},
  {companion:'Brother Alden',mergeKey:'seraphine:collective_punishment',urgency:1,privacyThreshold:2,deferredText:'Alden says, “There is a difference between accepting collateral harm and declaring innocent people part of the punishment.”'}],
 royal_secrets:[
  {companion:'Mirabel Quill',mergeKey:'seraphine:unreviewable_secrecy',urgency:2,whisperText:'Dangerous knowledge sometimes needs a locked door. It does not need a door whose existence cannot be questioned.',deferredText:'Mirabel folds her arms. “I believe in restricted knowledge. I do not believe the person hiding it should be the only person allowed to decide whether hiding it was justified.”'},
  {companion:'Reyna Fletcher',mergeKey:'seraphine:unreviewable_secrecy',urgency:2,whisperText:'A secret council with no outside review is an intelligence service that gets to grade its own mistakes.',deferredText:'Reyna says, “Secrets are tools. Making secrecy permanent turns the tool into the institution.”'},
  {companion:'Brother Alden',mergeKey:'seraphine:unreviewable_secrecy',urgency:1,deferredText:'Alden says, “Some things must be done quietly. I am less comfortable with deciding that nobody living later may ask what was done.”'}],
 public_audit:[{companion:'Mirabel Quill',mergeKey:'seraphine:accountability',defer:true,deferredText:'Mirabel smiles faintly. “An institution voluntarily leaving evidence for people who may disagree with it later. Rarer than it should be.”'}],
 equal_law:[{companion:'Wren Talbot',mergeKey:'seraphine:equal_law',defer:true,deferredText:'Wren says, “I noticed what you did in there. You made them prove who actually did something before reaching for punishment.”'}],
 charter_review:[{companion:'Reyna Fletcher',mergeKey:'seraphine:accountability',defer:true,deferredText:'Reyna nods once. “Keep secrets when you must. Keep records so somebody can tell later whether you really had to.”'}]
};
const party=()=>Array.isArray(root.party)?root.party:[], player=()=>party()[0]||root.player||null, now=()=>Number(root.worldSeconds||0)||0;
const norm=s=>String(s||'').toLowerCase().replace(/[\s_-]+/g,''), companion=n=>party().find((m,i)=>i>0&&m?.name===n)||null;
function ensureState(){const p=player();if(!p)return null;const o=p.playerDialogueBehaviour||{};return p.playerDialogueBehaviour={version:1,tags:o.tags&&typeof o.tags==='object'?o.tags:{},observations:Array.isArray(o.observations)?o.observations:[],pendingConversations:Array.isArray(o.pendingConversations)?o.pendingConversations:[],lastPrivacyMinute:Number.isFinite(o.lastPrivacyMinute)?o.lastPrivacyMinute:null};}
function recordPlayerChoice({sourceId='unknown',choiceId='choice',context='general',tags=[],strength=1,witnessedBy=[]}={}){const s=ensureState();if(!s)return false;const key=[sourceId,choiceId,context].join('|');if(s.observations.some(o=>o.key===key))return false;const a=Math.max(.25,Math.min(3,Number(strength)||1)),clean=[...new Set(tags.map(String))];for(const t of clean){const r=s.tags[t]||{weight:0,contexts:0,lastSeenAt:0};r.weight=Math.max(-20,Math.min(20,Number(r.weight||0)+a));r.contexts=Number(r.contexts||0)+1;r.lastSeenAt=now();s.tags[t]=r;}s.observations.push({key,sourceId,choiceId,context,tags:clean,strength:a,witnessedBy,at:now()});if(s.observations.length>160)s.observations.splice(0,s.observations.length-160);return true;}
const behaviourWeight=t=>Number(ensureState()?.tags?.[t]?.weight||0);
const raceOf=m=>m?.race?.name||m?.race||m?.ancestry?.name||m?.ancestry||'';
function classLevel(m,name){const want=norm(name);for(const c of[m?.classLevels,m?.classes,m?.levelsByClass]){if(Array.isArray(c)){const h=c.find(v=>norm(v?.name||v?.className||v?.id)===want);if(h)return Number(h.level??h.levels??h.rank??1)||0;}else if(c&&typeof c==='object')for(const[k,v]of Object.entries(c))if(norm(k)===want)return Number(typeof v==='object'?(v.level??v.levels??v.rank):v)||0;}return norm(m?.className||m?.class)===want?Number(m?.level||1):0;}
function skillValue(m,skill){const want=norm(skill);for(const bag of[m?.skills,m?.skillRanks,m?.skillValues,m?.stats,m?.abilities])if(bag&&typeof bag==='object')for(const[k,v]of Object.entries(bag))if(norm(k)===want){const n=Number(typeof v==='object'?(v.total??v.value??v.rank??v.modifier):v);if(Number.isFinite(n))return n;}return 0;}
function qualifiesPerspective(m,p={}){return !(typeof p.qualifies==='function'&&!p.qualifies(m))&&(!p.race||norm(raceOf(m))===norm(p.race))&&(!p.className||classLevel(m,p.className)>=Number(p.minLevel||1))&&(!p.skill||skillValue(m,p.skill)>=Number(p.minSkill||1));}
function shapePlayerOptions({baseOptions=[],variants=[],maxBehaviourExtras=2,character=player()}={}){const extra=variants.filter(v=>!v.perspective||qualifiesPerspective(character,v.perspective)).filter(v=>!v.minBehaviour||Object.entries(v.minBehaviour).every(([t,n])=>behaviourWeight(t)>=Number(n||0))).filter(v=>v.perspective||v.minBehaviour||!(v.tags?.length)||Math.max(...v.tags.map(behaviourWeight))>0).sort((a,b)=>Math.max(0,...(b.tags||[]).map(behaviourWeight))-Math.max(0,...(a.tags||[]).map(behaviourWeight))).slice(0,Math.max(0,Number(maxBehaviourExtras)||0));return [...baseOptions,...extra];}
function findContributors({skill,minSkill=1,className,minLevel=1,race,includePlayer=true,qualifies}={}){return party().filter((m,i)=>(i>0||includePlayer)&&qualifiesPerspective(m,{skill,minSkill,className,minLevel,race,qualifies})).sort((a,b)=>skill?skillValue(b,skill)-skillValue(a,skill):0);}
function pos(e){const q=Number(e?.q??e?.hex?.q),r=Number(e?.r??e?.hex?.r);if(Number.isFinite(q)&&Number.isFinite(r))return['hex',q,r];const x=Number(e?.x??e?.position?.x),y=Number(e?.y??e?.position?.y);return Number.isFinite(x)&&Number.isFinite(y)?['xy',x,y]:null;}
function dist(a,b){if(!a||!b||a[0]!==b[0])return Infinity;if(a[0]==='hex'){const dq=a[1]-b[1],dr=a[2]-b[2];return(Math.abs(dq)+Math.abs(dr)+Math.abs(dq+dr))/2;}return Math.hypot(a[1]-b[1],a[2]-b[2]);}
function listeners(){const names=new Set(party().map(m=>m?.name));return(Array.isArray(root.entities)?root.entities:[]).filter(e=>e&&!e.dead&&!e.isDead&&!names.has(e.name)&&e.type!=='item'&&e.type!=='projectile');}
function privacyLevel(){if(typeof root.getPartyPrivacyLevel==='function'){const n=Number(root.getPartyPrivacyLevel());if(Number.isFinite(n))return Math.max(0,Math.min(3,n));}const p=pos(player()),ls=listeners();if(!p)return ls.length?1:3;let near=Infinity;for(const e of ls)near=Math.min(near,dist(p,pos(e)));return near<=3?0:near<=7?1:near<=12?2:3;}
function chooseChannel(r={}){const allowed=(r.channels||['public','whisper','defer']).filter(x=>['public','whisper','defer'].includes(x));if(r.defer&&allowed.includes('defer'))return'defer';const p=PROFILES[r.companion]||{public:.33,whisper:.33,defer:.34},s={...p},u=Number(r.urgency||0);s.public+=u*.08;s.defer-=u*.05;if(r.criticismOfPlayer){s.public-=.18;s.defer+=.16;}if(r.sensitive){s.public-=.2;s.whisper+=.18;}if(r.publicText)s.public+=.08;if(r.whisperText)s.whisper+=.08;if(r.preferredChannel)s[r.preferredChannel]=(s[r.preferredChannel]||0)+.5;return allowed.sort((a,b)=>s[b]-s[a])[0]||'defer';}
function say(name,text,channel){if(!text)return;const line=`${channel==='whisper'?`${name}, quietly`:`${name}`}: ${text}`;if(root.showMessage)root.showMessage(line);else root.addToLog?.(line);}
function queuePending(r={}){const s=ensureState();if(!s)return null;const key=String(r.mergeKey||r.eventId||r.topic||'party_issue');let p=s.pendingConversations.find(x=>!['resolved','expired'].includes(x.status)&&x.companion===r.companion&&x.mergeKey===key);if(p){p.urgency=Math.max(Number(p.urgency||0),Number(r.urgency||0));p.privacyThreshold=Math.max(Number(p.privacyThreshold||1),Number(r.privacyThreshold||1));p.lastUpdatedAt=now();if(r.deferredText)p.deferredText=r.deferredText;p.tags=[...new Set([...(p.tags||[]),...(r.tags||[])])];return p;}p={id:`pcd_${Math.round(now())}_${s.pendingConversations.length}_${key.replace(/\W+/g,'_')}`,mergeKey:key,eventId:String(r.eventId||key),companion:String(r.companion||''),topic:String(r.topic||'what happened earlier'),urgency:Number(r.urgency||0),privacyThreshold:Number(r.privacyThreshold??1),createdAt:now(),lastUpdatedAt:now(),deferredText:String(r.deferredText||r.whisperText||r.publicText||'I wanted to talk about what happened earlier.'),status:'pending',barkShown:false,expiresAfterMinutes:Number(r.expiresAfterMinutes??(Number(r.urgency||0)>0?720:240)),tags:[...(r.tags||[])]};s.pendingConversations.push(p);if(s.pendingConversations.length>40)s.pendingConversations.splice(0,s.pendingConversations.length-40);return p;}
function raiseReaction(r={}){if(!companion(r.companion))return null;const c=chooseChannel(r);if(c==='public'&&r.publicText){say(r.companion,r.publicText,c);return r.alsoFollowUp?queuePending(r):{channel:c};}if(c==='whisper'&&r.whisperText){say(r.companion,r.whisperText,c);return r.alsoFollowUp?queuePending(r):{channel:c};}return{channel:'defer',pending:queuePending(r)};}
function processPendingPrivacy({force=false}={}){const s=ensureState();if(!s||!s.pendingConversations.some(p=>p.status==='pending'))return{checked:false,reason:'empty'};const minute=Math.floor(now()/MINUTE);if(!force&&s.lastPrivacyMinute===minute)return{checked:false,reason:'same_minute'};s.lastPrivacyMinute=minute;const privacy=privacyLevel();let available=0,expired=0;for(const p of s.pendingConversations)if(p.status==='pending'){if((now()-p.createdAt)/MINUTE>p.expiresAfterMinutes){p.status='expired';expired++;}else if(privacy>=p.privacyThreshold){p.status='available';available++;if(!p.barkShown){p.barkShown=true;say(p.companion,p.urgency>=2?'We need to talk about what just happened when you have a moment.':'When you have a moment, I would like a word.','whisper');}}}return{checked:true,privacy,available,expired};}
const availableFor=n=>(ensureState()?.pendingConversations||[]).filter(p=>p.status==='available'&&p.companion===n);
function resolvePending(p,response){if(!p||p.status==='resolved')return false;p.status='resolved';p.resolvedAt=now();p.responseTag=response;recordPlayerChoice({sourceId:p.eventId,choiceId:`private_response:${response}`,context:p.mergeKey,tags:response==='listen'?['open_to_dissent']:response==='later'?['discretion']:['hierarchical','closed_to_dissent'],witnessedBy:[p.companion]});return true;}
function openPrivate(name,p){p.status='in_conversation';const opts=[{label:'Speak freely.',action:()=>resolvePending(p,'listen')},{label:'Not here. We will discuss it when it is safer.',action:()=>{p.status='pending';p.barkShown=false;p.privacyThreshold=Math.min(3,p.privacyThreshold+1);recordPlayerChoice({sourceId:p.eventId,choiceId:'private_response:later',context:p.mergeKey,tags:['discretion'],witnessedBy:[p.companion]});}},{label:'I have made my decision.',action:()=>resolvePending(p,'closed')}];root.showDialogue?.(companion(name)||{name},p.deferredText,opts);if(p.status==='in_conversation')p.status='available';}
function recordQueenChoice(outcome){const tags=QUEEN_TAGS[outcome];return tags?recordPlayerChoice({sourceId:'seraphine_governance_arc',choiceId:outcome,context:'royal_policy',tags,witnessedBy:party().slice(1).map(c=>c?.name).filter(Boolean)}):false;}
function queenReaction(outcome){const list=(QUEEN_REACTIONS[outcome]||[]).filter(r=>companion(r.companion));let immediate=false,deferred=false;for(const raw of list){const r={...raw,eventId:`seraphine:${outcome}`,context:`Queen Seraphine chose ${outcome}`},c=chooseChannel(r);if(c!=='defer'&&!immediate){raiseReaction({...r,preferredChannel:c});immediate=true;}else if(!deferred){queuePending(r);deferred=true;}}}
function decorateDialogue(npc,text,options){let out=Array.isArray(options)?options.map(o=>({...o})):[];out=out.map(o=>{if(!o?.decisionOutcome||o.__partyConversationDynamics)return o;const original=o.action,id=String(o.decisionOutcome);return{...o,__partyConversationDynamics:true,action:()=>{recordQueenChoice(id);const r=original?.();if(id!=='queen_decides')queenReaction(id);return r;}};});const name=npc?.name;if(name){const add=availableFor(name).slice(0,2).filter(p=>!out.some(o=>o.__partyPrivateId===p.id)).map(p=>({label:`[Private] About ${p.topic}...`,__partyConversationDynamics:true,__partyPrivateId:p.id,action:()=>openPrivate(name,p)}));if(add.length){const i=out.findIndex(o=>/leave|goodbye|farewell|nothing else|that is all|never mind/i.test(String(o?.label||'')));i>=0?out.splice(i,0,...add):out.push(...add);}}return out;}
function installDialogueHook(){const cur=root.showDialogue;if(typeof cur!=='function')return false;if(cur.__partyConversationDynamics)return true;const wrapped=function(n,t,o,...rest){return cur.call(this,n,t,decorateDialogue(n,t,o),...rest)};wrapped.__partyConversationDynamics=true;wrapped.__partyConversationDynamicsBase=cur;root.showDialogue=wrapped;return true;}
const tick=()=>{installDialogueHook();return processPendingPrivacy();};
const api={BUILD,COMPANION_PROFILES:PROFILES,ensureState,recordPlayerChoice,behaviourWeight,classLevel,skillValue,qualifiesPerspective,shapePlayerOptions,findContributors,privacyLevel,chooseChannel,raiseReaction,queuePending,processPendingPrivacy,availableFor,resolvePending,recordQueenChoice,queenReaction,decorateDialogue,installDialogueHook,tick};
root.partyConversationDynamics=api;installDialogueHook();if(typeof document!=='undefined'&&typeof setInterval==='function'){const t=setInterval(tick,1000);t?.unref?.();}if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
