// Physical identities for clothes and armour without destabilising the legacy string inventory.
(()=>{'use strict';
const BUILD=window.PRESENTATION_BUILD||'20260930-wearable-instances-v1';
const SLOTS=['armor','shirt','pants','bra','underwear'];
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const base=v=>window.getEquipmentBaseId?.(v)||v;
function wearable(id){const d=window.items?.[base(id)];return !!d&&(d.type==='armor'||d.type==='clothes');}
function slotFor(id){id=base(id);const d=window.items?.[id];if(d?.type==='armor')return'armor';return window.clothingSystem?.getItemSpec?.(id)?.slot||d?.clothingSlot||'shirt';}
function list(e){if(!e.physicalEquipment||!Array.isArray(e.physicalEquipment))e.physicalEquipment=[];return e.physicalEquipment;}
function make(id,e){const appearance={};if(e?.clothingColors?.[id])appearance.clothing=clone(e.clothingColors[id]);if(e?.equipmentColors?.[id])appearance.armour=clone(e.equipmentColors[id]);return window.equipmentIdentity?.make(id,{appearance:Object.keys(appearance).length?appearance:null,provenance:'legacy'})||{instanceId:`wear-${Date.now()}-${Math.random()}`,itemId:id,appearance:null};}
function reconcile(e){if(!e||!Array.isArray(e.inventory))return;const physical=list(e),need={};for(const raw of e.inventory){const id=base(raw);if(wearable(id))need[id]=(need[id]||0)+1;}const have={};for(const x of physical){if(wearable(x))have[x.itemId]=(have[x.itemId]||0)+1;}for(const [id,n] of Object.entries(need))for(let i=have[id]||0;i<n;i++)physical.push(make(id,e));for(let i=physical.length-1;i>=0;i--){const x=physical[i],id=x?.itemId;if(!need[id]){physical.splice(i,1);continue;}const same=physical.filter(y=>y.itemId===id);if(same.length>need[id]){const equipped=Object.values(e.equippedInstances||{}).includes(x);if(!equipped)physical.splice(i,1);}}
 e.equippedInstances=e.equippedInstances||{};for(const slot of SLOTS){const id=base(e.equipped?.[slot]);if(!id){delete e.equippedInstances[slot];continue;}if(!wearable(id))continue;let inst=e.equippedInstances[slot];if(!inst||inst.itemId!==id||!physical.includes(inst)){inst=physical.find(x=>x.itemId===id&&!Object.values(e.equippedInstances).includes(x))||physical.find(x=>x.itemId===id)||make(id,e);if(!physical.includes(inst))physical.push(inst);e.equippedInstances[slot]=inst;}}
}
function current(e,id){reconcile(e);id=base(id);for(const slot of SLOTS)if(base(e?.equipped?.[slot])===id&&e.equippedInstances?.[slot])return e.equippedInstances[slot];return null;}
function appearanceBucket(e,id,key){const inst=current(e,id);if(!inst)return null;inst.appearance=inst.appearance||{};inst.appearance[key]=inst.appearance[key]||{};return inst.appearance[key];}
function installAppearanceHooks(){const cs=window.clothingSystem,ea=window.equipmentAppearanceSystem;if(!cs||!ea||cs.__physicalWearables)return false;
 const oldGetC=cs.getLayerColour,oldSetC=cs.setLayerColour;cs.getLayerColour=function(e,id,part){const b=appearanceBucket(e,id,'clothing');if(b){if(!b[part.id])b[part.id]=clone(oldGetC.call(this,e,id,part));return b[part.id];}return oldGetC.call(this,e,id,part);};cs.setLayerColour=function(e,id,partId,next){const inst=current(e,id);if(inst){const spec=cs.getItemSpec(id),part=spec?.layers?.find(x=>x.id===partId);if(!part)return;const b=appearanceBucket(e,id,'clothing'),prev=b[partId]||clone(oldGetC.call(this,e,id,part));b[partId]={...prev,...next};return;}return oldSetC.call(this,e,id,partId,next);};
 const oldGetA=ea.getArmourMaterial,oldSetA=ea.setArmourMaterial;ea.getArmourMaterial=function(e,id,part){const b=appearanceBucket(e,id,'armour');if(b){if(!b[part])b[part]=clone(oldGetA.call(this,e,id,part));return b[part];}return oldGetA.call(this,e,id,part);};ea.setArmourMaterial=function(e,id,part,next){const inst=current(e,id);if(inst){const b=appearanceBucket(e,id,'armour'),prev=b[part]||clone(oldGetA.call(this,e,id,part));b[part]={...prev,...next};return;}return oldSetA.call(this,e,id,part,next);};cs.__physicalWearables=true;return true;}
function equip(instanceId){const p=window.player;if(!p)return;reconcile(p);const inst=list(p).find(x=>x.instanceId===instanceId);if(!inst)return;const id=inst.itemId,slot=slotFor(id);window.equipItem?.(id);if(base(p.equipped?.[slot])===id){p.equippedInstances=p.equippedInstances||{};p.equippedInstances[slot]=inst;window.syncPlayerEntity?.();window.showInventoryScreen?.();window.renderEntities?.();}}
function inject(){const host=document.getElementById('inventory-content'),p=window.player;if(!host||!p||host.querySelector('[data-physical-wearables]'))return;reconcile(p);const xs=list(p);if(!xs.length)return;const box=document.createElement('div');box.dataset.physicalWearables='true';box.style.cssText='border:1px solid #555;border-radius:5px;padding:8px;margin:8px 0 12px;';const h=document.createElement('strong');h.textContent='Individual clothes & armour';box.appendChild(h);const note=document.createElement('div');note.textContent='Each copy is now a separate physical item. Colour changes belong to the equipped copy, not every item of that type.';note.style.cssText='font-size:.78em;color:#aaa;margin:4px 0 7px;';box.appendChild(note);for(const x of xs){const id=x.itemId,d=window.items?.[id];if(!d)continue;const row=document.createElement('div');row.style.cssText='display:flex;justify-content:space-between;gap:8px;align-items:center;border-top:1px solid #3f3f3f;padding:6px 0;';const slot=slotFor(id),on=p.equippedInstances?.[slot]===x&&base(p.equipped?.[slot])===id;const name=document.createElement('span');name.textContent=`${window.describeEquipment?.(x)||d.name}${on?' (equipped)':''}`;row.appendChild(name);const b=document.createElement('button');b.type='button';b.textContent=on?'Equipped':'Equip this';b.disabled=on;b.style.cssText='width:auto;padding:4px 8px;font-size:.78em;';b.onclick=()=>equip(x.instanceId);row.appendChild(b);box.appendChild(row);}host.prepend(box);}
function installUI(){if(window.showInventoryScreen&&!window.showInventoryScreen.__physicalWearables){const old=window.showInventoryScreen;const wrapped=function(){reconcile(window.player);const r=old.apply(this,arguments);inject();return r;};wrapped.__physicalWearables=true;window.showInventoryScreen=wrapped;}if(window.unequipItem&&!window.unequipItem.__physicalWearables){const old=window.unequipItem;const wrapped=function(slot){const r=old.apply(this,arguments);if(window.player&&!window.player.equipped?.[slot]&&window.player.equippedInstances)delete window.player.equippedInstances[slot];return r;};wrapped.__physicalWearables=true;window.unequipItem=wrapped;}}
function sync(){for(const e of [...(window.party||[]),...(window.entities||[])])reconcile(e);installAppearanceHooks();installUI();}
window.physicalWearables={reconcile,list,current,equip};const timer=setInterval(sync,100);window.addEventListener('load',sync,{once:true});
})();
