// Queen Seraphine Corrin: recurring governance arc.
(() => {
'use strict';
const root=typeof window!=='undefined'?window:globalThis, BUILD='20261001-seraphine-arc-v1', QUEEN='Queen Seraphine Corrin', DELAY=43200;
const Q={company:'seraphine_crown_and_company',border:'seraphine_border_decree',secrets:'seraphine_what_crown_may_hide'};
const party=()=>Array.isArray(root.party)?root.party:[], player=()=>party()[0]||root.player||null, quest=id=>(root.questLog||[]).find(q=>q?.id===id)||null, now=()=>Number(root.worldSeconds||0), clamp=n=>Math.max(-100,Math.min(100,Math.round(Number(n)||0)));
function ensureState(){const p=player();if(!p)return null;const o=p.seraphineArc||{};return p.seraphineArc={version:1,restraint:clamp(o.restraint??10),centralisation:clamp(o.centralisation??5),confidence:clamp(o.confidence??0),alignment:o.alignment||'independent',knownKeys:Array.isArray(o.knownKeys)?o.knownKeys:[],history:Array.isArray(o.history)?o.history:[],policies:o.policies&&typeof o.policies==='object'?o.policies:{}};}
function record(key,d={},reason=key){const s=ensureState();key=String(key||'');if(!s||!key||s.knownKeys.includes(key))return false;s.knownKeys.push(key);if(s.knownKeys.length>160)s.knownKeys.splice(0,s.knownKeys.length-160);s.restraint=clamp(s.restraint+Number(d.restraint||0));s.centralisation=clamp(s.centralisation+Number(d.centralisation||0));s.confidence=clamp(s.confidence+Number(d.confidence||0));if(d.policy)Object.assign(s.policies,d.policy);s.history.push({key,reason:String(reason),at:now(),restraint:s.restraint,centralisation:s.centralisation,confidence:s.confidence});if(s.history.length>100)s.history.splice(0,s.history.length-100);return true;}
function posture(s=ensureState()){if(!s)return'pragmatic';if(s.restraint<=-20&&s.centralisation>=30)return'ruthless';if(s.restraint>=30&&s.centralisation<=35)return'restrained';if(s.centralisation>=40)return'hard_crown';if(s.restraint>=20)return'rule_bound';return'pragmatic';}
const POSTURE={ruthless:'Seraphine now treats hesitation itself as a danger. She still distinguishes enemies from subjects, but she is increasingly willing to decide who belongs in which category before a court ever does.',hard_crown:'Seraphine has become a strong centraliser. She will use law where she can, but increasingly believes the Crown must be able to move faster than ordinary institutions when the kingdom is threatened.',restrained:'Seraphine has become unusually deliberate about limits on her own power. She still acts decisively, but increasingly insists that emergency authority must leave a record, a review and a way back to ordinary law.',rule_bound:'Seraphine increasingly treats procedure as part of state strength rather than an inconvenience, though she still keeps considerable discretion in reserve.',pragmatic:'Seraphine remains pragmatic: willing to bend institutions when pressed, but not yet committed to either concentrated royal power or strong limits on it.'};
const postureText=s=>POSTURE[posture(s)];
function confidenceText(s=ensureState()){const v=Number(s?.confidence||0);return v>=45?'She trusts your judgement enough to ask what you think before her council has agreed what it thinks.':v>=20?'She regards you as a useful and unusually credible adviser, not merely a successful adventurer.':v<=-35?'Whatever the kingdom may owe you, Seraphine now treats your political judgement as something to guard against.':v<=-15?'She respects some of what you have done, but no longer assumes your advice serves the Crown.':'She listens to you, but has not yet decided whether your judgement is something she can rely on.';}
const surface=()=>typeof root.getSurfacePower==='function'?Number(root.getSurfacePower()||0):Number(root.ironbondArc?.surfacePower||0), influence=()=>Number(root.factions?.ironbond_company?.merchantInfluence?.silverhart_kingdom??30);
function rep(id,d,k=10){const f=root.factions?.[id];if(!f||!d)return false;if(root.adjustReputation)root.adjustReputation(f,d,k);else f.standing=clamp(Number(f.standing||0)+d);return true;}
function ironPower(d){if(!d)return;if(root.adjustSurfacePower)root.adjustSurfacePower(d);else if(root.ironbondArc)root.ironbondArc.surfacePower=Math.max(0,Math.min(100,Number(root.ironbondArc.surfacePower||0)+d));const m=root.factions?.ironbond_company?.merchantInfluence;if(m&&Number.isFinite(Number(m.silverhart_kingdom)))m.silverhart_kingdom=Math.max(0,Math.min(100,Number(m.silverhart_kingdom)+Math.round(d*.7)));}
function wrenResolution(){const q=quest('wren_crown_quiet_hand');if(q?.status!=='completed')return null;return q.resolution==='wren_decides'?(q.effectiveResolution||q.wrenDecision||'wren_decides'):q.resolution;}
function syncExistingConsequences(){ensureState();const w=quest('wizard_vendetta');if(w?.status==='completed'&&w.resolution==='queen')record('existing:wizard_evidence',{confidence:7,centralisation:2},'trusted the Crown with evidence against its own Court Wizard');if(root.chancellorTunnelReportedToQueen)record('existing:tunnel',{confidence:9,centralisation:5,restraint:-2},'reported the thieves’ tunnel beneath the council chamber');if(root.phylacteryReturned)record('existing:phylactery',{confidence:9,centralisation:3},'entrusted dangerous necromantic evidence to the Crown');const r=wrenResolution();if(r==='public_inquiry')record('existing:wren_inquiry',{restraint:10,centralisation:-2},'the Crown survived public scrutiny of an old cover-up');else if(r==='restore_names')record('existing:wren_names',{restraint:7},'the Crown accepted public repair for people its own offices erased');else if(r==='bury_for_stability')record('existing:wren_bury',{restraint:-13,centralisation:8},'an old Crown scandal was buried again for stability');return ensureState();}
const CH={
 [Q.company]:{chapter:1,title:'The Crown and the Company',consult:['chancellor','petra'],intro:'Ironbond now sits inside enough contracts, roads and credit arrangements that simply ordering it away would tear holes in the same economy Seraphine is trying to protect. She wants options before dependence becomes obedience.',decision:'The Crown has enough evidence and leverage to act. What kind of precedent is Seraphine willing to create to weaken Ironbond?'},
 [Q.border]:{chapter:2,title:'The Border Decree',consult:['hart','marta'],intro:'Raids, reprisals and the possibility of peace have produced the same demand: make the border predictable. Seraphine is considering powers to search, restrict and punish whole frontier communities when raiders are sheltered.',decision:'Hart has described what emergency powers could achieve. Marta has described what collective suspicion would destroy. Seraphine must decide what security permits.'},
 [Q.secrets]:{chapter:3,title:'What the Crown May Hide',consult:['thessaly','adelram'],intro:'Sealed murder records, dangerous magic, infiltration and wartime intelligence have accumulated behind palace doors. Seraphine wants a durable rule for secrets before emergency practice quietly becomes the constitution.',decision:'The question is whether anyone outside the Crown must be able to review what is hidden, why, and for how long.'}
};
const prev=id=>id===Q.border?quest(Q.company):id===Q.secrets?quest(Q.border):null;
function canStart(id){if(!CH[id]||quest(id))return false;if(id===Q.company)return influence()>=25||surface()>=25||!!root.ironbondArc?.playerSide;const p=prev(id);return !!p&&p.status==='completed'&&now()-Number(p.completedAt||0)>=DELAY;}
function ensureQuest(id,{announce=true}={}){const spec=CH[id];if(!spec)return null;root.questLog=root.questLog||[];let q=quest(id);if(q){q.consultations=q.consultations||{};q.choiceKeys=Array.isArray(q.choiceKeys)?q.choiceKeys:[];return q;}if(!canStart(id))return null;q={id,title:spec.title,giver:QUEEN,status:'active',stage:'consult',chapter:spec.chapter,resolution:null,effectiveResolution:null,consultations:{},choiceKeys:[],offeredAt:now(),description:spec.intro};root.questLog.push(q);if(announce)root.showMessage?.(`Royal arc added: ${spec.title}.`);return q;}
const ready=q=>!!(q&&q.status==='active'&&CH[q.id]?.consult.every(k=>q.consultations?.[k])), activeQuest=()=>Object.keys(CH).map(quest).find(q=>q?.status==='active')||null;
const COUNSEL={
 chancellor:{tree:'palace_chancellor',label:'The Queen asked what breaking Ironbond’s leverage would cost.',text:'Merric spreads treasury schedules across the table. “We can audit every Crown contract and survive the disruption. We can freeze Company assets immediately and discover afterward which grain wagons, payrolls and bridge crews were attached to them. Or force divestment over time and leave Ironbond strong enough to remain a counterweight. None is free. The emergency option merely sends the invoice later.”'},
 petra:{tree:'reddale_guildmaster',label:'What happens if the Queen freezes Ironbond’s assets?',text:'Petra Voss does not threaten you. “For a week? Chaos. For a month? The Crown learns how many things it thought were public services are actually Company contracts. Perhaps she wins. Perhaps every merchant learns property exists until the palace dislikes its owner. I sell influence. I have never pretended otherwise. Ask what she is selling.”'},
 hart:{tree:'northwatch_commander',label:'The Queen is considering emergency border powers.',text:'Commander Hart reads the draft. “Checkpoints catch weapons. Curfews reduce night movement. Collective penalties also give every frightened farmer a reason to lie before we ask a question. Give me authority to arrest people I can identify. Do not make an entire valley guilty because my scouts are tired.”'},
 marta:{tree:'elder_marta',label:'What would collective Crown penalties do to the border?',text:'Marta answers immediately. “Teach every goblin, farmer and smuggler that the Crown punishes categories instead of deeds. Perhaps fear buys quiet. But if peace is to survive a bad season, people must believe one neighbour’s crime does not automatically become theirs.”'},
 thessaly:{tree:'royal_wizard',label:'The Queen wants a rule for dangerous secrets.',text:'Thessaly glances toward the locked shelves. “Some knowledge genuinely becomes more dangerous when broadcast. That does not mean the person holding the key should also be the only person allowed to decide whether the lock was justified.”'},
 adelram:{tree:'high_cleric',label:'Does a Crown need powers nobody can review?',text:'Adelram considers it. “A ruler may need to act before everyone can be consulted. That is different from saying nobody may later ask what was done. Power that can never be reviewed eventually starts calling embarrassment an emergency.”'}
};
function markConsultation(key,npc){const q=activeQuest(),s=CH[q?.id];if(!q||!s||!s.consult.includes(key)||q.consultations?.[key])return false;q.consultations[key]={at:now(),npc:npc?.name||key};if(ready(q)){q.stage='reckoning';q.description=`${s.decision} Return to Queen Seraphine.`;root.showMessage?.(`${s.title}: return to the Queen.`);}return true;}
function consult(key,npc){if(!COUNSEL[key]||!markConsultation(key,npc))return false;root.showDialogue?.(npc||{name:key},COUNSEL[key].text,[{label:'I’ll take that back to the Queen.',action:()=>{}}]);return true;}
const REACTIONS={public_audit:{'Wren Talbot':3,'Ser Aldric Thorne':3,'Reyna Fletcher':2},emergency_seizure:{'Wren Talbot':-2,'Ser Aldric Thorne':-2,'Mirabel Quill':-2,'Reyna Fletcher':-3},brokered_limits:{'Mirabel Quill':1,'Fenn Oakheart':1,'Reyna Fletcher':1},equal_law:{'Wren Talbot':3,'Ser Aldric Thorne':3,'Fenn Oakheart':2,'Reyna Fletcher':3,'Brother Alden':2},security_zones:{'Wren Talbot':-1,'Fenn Oakheart':-1,'Brother Alden':-1},collective_penalties:{'Wren Talbot':-5,'Ser Aldric Thorne':-4,'Fenn Oakheart':-4,'Reyna Fletcher':-4,'Brother Alden':-5},charter_review:{'Wren Talbot':3,'Ser Aldric Thorne':3,'Mirabel Quill':3,'Reyna Fletcher':3},narrow_seals:{'Mirabel Quill':1,'Reyna Fletcher':1},royal_secrets:{'Wren Talbot':-4,'Ser Aldric Thorne':-3,'Mirabel Quill':-5,'Reyna Fletcher':-5,'Brother Alden':-2}};
function react(outcome,qid){for(const [name,d]of Object.entries(REACTIONS[outcome]||{})){const c=party().find((m,i)=>i>0&&m?.name===name);if(c)root.adjustCompanionRelationship?.(c,{approval:d},`reacted to Queen Seraphine’s decision in ${CH[qid].title}`);}}
const OUT={
 [Q.company]:{
  public_audit:{label:'Put every Crown–Ironbond contract through a public audit. Use ordinary warrants for crimes you can prove.',d:{restraint:18,centralisation:5,confidence:4,policy:{ironbondPolicy:'public_audit'}},power:-12,irep:-10,crep:4,line:'Seraphine orders the contracts opened, names independent auditors and tells the Chancellor to prosecute identifiable fraud rather than treating every Company asset as guilty by association. “Slow enough for everyone to complain,” she says. “Good. They can complain on the record.”'},
  emergency_seizure:{label:'Freeze Company assets, seize its Crown-facing ledgers and break its leverage before it can move the money.',d:{restraint:-24,centralisation:27,confidence:7,policy:{ironbondPolicy:'emergency_seizure'}},power:-25,irep:-25,crep:6,line:'Before dawn, royal officers freeze Company accounts tied to Crown contracts and occupy key counting houses. Grain still moves, barely. “If private leverage can veto the state,” Seraphine says, “it is already a rival government.”'},
  brokered_limits:{label:'Force divestment and conflict-of-interest rules, but leave Ironbond strong enough to remain outside Crown control.',d:{restraint:9,centralisation:-8,confidence:3,policy:{ironbondPolicy:'brokered_limits'}},power:-6,irep:3,crep:2,line:'The settlement costs Ironbond monopolies and privileged contracts without destroying the Company. Petra calls it robbery with stationery; Merric calls it survivable. Seraphine calls both descriptions evidence the balance may be about right.'}},
 [Q.border]:{
  equal_law:{label:'Keep ordinary law. Investigate and punish identifiable offenders, not whole communities.',d:{restraint:21,centralisation:-6,confidence:5,policy:{borderPolicy:'equal_law'}},grep:6,crep:3,sec:2,line:'Seraphine tears the collective-penalty clauses from the decree. Hart gets more scouts, magistrates and authority to pursue named suspects. “If ordinary law cannot survive frightened people, it was only ever ceremony.”'},
  security_zones:{label:'Create temporary security zones: checkpoints, night restrictions and search powers, with written expiry dates.',d:{restraint:-10,centralisation:18,confidence:5,policy:{borderPolicy:'security_zones'}},grep:-8,crep:2,sec:8,line:'The decree creates controlled zones along the most raided roads, with warrants relaxed and movement restricted after dark. Seraphine accepts sunset clauses only after Hart insists on them.'},
  collective_penalties:{label:'Make sheltering raiders a community liability. Seize goods and restrict movement where attacks are repeatedly concealed.',d:{restraint:-27,centralisation:29,confidence:8,policy:{borderPolicy:'collective_penalties'}},grep:-24,crep:4,sec:13,line:'Seraphine signs the harsher decree. Villages that repeatedly conceal raiders can lose trade privileges, livestock and freedom of movement until they produce offenders. Raids fall quickly. So does the number willing to speak freely to Crown patrols.'}},
 [Q.secrets]:{
  charter_review:{label:'Create a standing review charter: emergency secrets remain secret when necessary, but never beyond later independent scrutiny.',d:{restraint:29,centralisation:-15,confidence:5,policy:{secrecyPolicy:'charter_review'}},crep:4,line:'Seraphine creates a review bench outside her ordinary council, sworn to secrecy but empowered to inspect sealed orders after immediate danger passes. “A lock can be necessary. The person holding the key should still know someone will count the rooms later.”'},
  narrow_seals:{label:'Keep secrecy case-by-case. Require written reasons and expiry dates, but leave final authority with the Crown.',d:{restraint:7,centralisation:4,confidence:3,policy:{secrecyPolicy:'narrow_seals'}},crep:2,line:'Seraphine keeps final authority but orders every sealed matter to carry a reason, an owner and a review date.'},
  royal_secrets:{label:'Formalise a secret Crown council empowered to act without public review when the Queen judges the realm threatened.',d:{restraint:-31,centralisation:28,confidence:9,policy:{secrecyPolicy:'royal_secrets'}},crep:5,line:'Seraphine creates a permanent inner council able to seal investigations, redirect funds and detain suspected agents during declared threats. Its records answer to the monarch alone. “Enemies adapt to rules they can see. Then some of our rules will not be visible.”'}}
};
function autonomousOutcome(q){const s=ensureState();if(q.id===Q.company)return s.centralisation>=25&&s.restraint<=10||surface()>=70&&s.restraint<25?'emergency_seizure':s.restraint>=22?'public_audit':'brokered_limits';if(q.id===Q.border)return s.centralisation>=45&&s.restraint<=-10?'collective_penalties':s.restraint>=28?'equal_law':'security_zones';return s.centralisation>=45&&s.restraint<=-10?'royal_secrets':s.restraint>=30?'charter_review':'narrow_seals';}
function mechanics(q,id,spec,chosen){const d={...spec.d};if(!chosen)delete d.confidence;record(`resolution:${q.id}:${id}`,d,`Queen Seraphine resolved ${q.title}: ${id}`);if(spec.power)ironPower(spec.power);if(spec.irep)rep('ironbond_company',spec.irep,15);if(spec.crep)rep('silverhart_kingdom',spec.crep);if(spec.grep)rep('goblin_tribe',spec.grep,15);if(spec.sec&&root.adjustRegionStat)root.adjustRegionStat('aldervale','security',spec.sec);react(id,q.id);}
function completeQuest(outcome,{queenDecides=false}={}){const q=activeQuest();if(!q||!ready(q))return false;const id=queenDecides||outcome==='queen_decides'?autonomousOutcome(q):outcome,spec=OUT[q.id]?.[id];if(!spec)return false;q.status='completed';q.resolution=queenDecides||outcome==='queen_decides'?'queen_decides':id;q.effectiveResolution=id;q.completedAt=now();q.stage='completed';q.description=spec.line;mechanics(q,id,spec,q.resolution!=='queen_decides');if(q.resolution==='queen_decides')record(`trusted:${q.id}`,{confidence:10},`trusted Seraphine to decide ${q.title}`);root.gainExp?.(q.id===Q.secrets?400:300);root.showMessage?.(`Royal arc complete: ${q.title}.`);root.showDialogue?.({name:QUEEN},spec.line,[{label:'“Then it is decided.”',action:()=>{}}]);return true;}
const THEMES={
 [Q.company]:{public_audit:['accountable_authority','institutional_process','scrutiny'],emergency_seizure:['practical_protection','expendable_people','private_solution'],brokered_limits:['correctable_institution','proportionality','shared_cost'],queen_decides:['agency']},
 [Q.border]:{equal_law:['institutional_process','proportionality','accountable_authority'],security_zones:['practical_protection','contextual_limits','trust_gamble'],collective_penalties:['practical_protection','expendable_people','externalised_cost'],queen_decides:['agency']},
 [Q.secrets]:{charter_review:['scrutiny','accountable_authority','correctable_institution','contextual_limits'],narrow_seals:['contextual_limits','practical_protection'],royal_secrets:['institutional_coverup','practical_protection','private_solution'],queen_decides:['agency']}
};
function impressions(q,id){const a=root.companionDecisionAnticipation,choices=THEMES[q?.id];if(!a?.analyseChoice||!a?.impressionText||!choices?.[id])return[];return a.analyseChoice({spec:{companion:null,choices}},id).map(a.impressionText);}
function companionReview(q,opts,npc){const choices=opts.filter(o=>o?.decisionOutcome),menu=()=>{const r=choices.map(o=>({label:String(o.label).slice(0,78),action:()=>{const i=impressions(q,o.decisionOutcome),body=i.length?i.join('\n\n'):'You have not learned enough relevant information about your companions to read much into this choice yet.';root.showDialogue?.({name:'Your judgement'},`${o.label}\n\n${body}\n\nThese are inferences from what you have actually learned, not guarantees of how anyone will react.`,[{label:'Consider another choice.',action:menu},{label:'Back to the Queen.',action:()=>root.showDialogue?.(npc,CH[q.id].decision,opts)}]);}}));r.push({label:'Back to the Queen.',action:()=>root.showDialogue?.(npc,CH[q.id].decision,opts)});root.showDialogue?.({name:'Your judgement'},'Which royal policy do you want to think through? These notes use only personality clues you have actually learned from your companions.',r);};menu();}
function resolutionOptions(q,npc){const o=Object.entries(OUT[q.id]).map(([id,s])=>({label:s.label,decisionOutcome:id,action:()=>completeQuest(id)}));o.push({label:'“You have heard everyone. Make the decision you think the Crown can live with.”',decisionOutcome:'queen_decides',action:()=>completeQuest('queen_decides',{queenDecides:true})});const all=[...o,{label:'Not yet.',action:()=>{}}];all.splice(all.length-1,0,{label:'Consider your companions.',__seraphineCompanionReview:true,action:()=>companionReview(q,all,npc)});return all;}
function openQuestHub(npc={name:QUEEN}){syncExistingConsequences();let q=activeQuest();if(!q){const id=[Q.company,Q.border,Q.secrets].find(canStart);if(!id)return false;q=ensureQuest(id);if(!q)return false;root.showDialogue?.(npc,CH[id].intro,[{label:'“I’ll hear the people who have to live with the decision.”',action:()=>openQuestHub(npc)},{label:'“Tell me when you have enough to decide.”',action:()=>{}}]);return true;}const s=CH[q.id];if(ready(q)){root.showDialogue?.(npc,s.decision,resolutionOptions(q,npc));return true;}const names={chancellor:'Chancellor Merric Vane',petra:'Petra Voss',hart:'Commander Elira Hart',marta:'Elder Marta',thessaly:'Court Wizard Thessaly',adelram:'High Cleric Adelram'},missing=s.consult.filter(k=>!q.consultations?.[k]).map(k=>names[k]);root.showDialogue?.(npc,`${s.intro}\n\nYou still need to hear: ${missing.join(' and ')}.`,[{label:'“I’ll bring you their counsel.”',action:()=>{}}]);return true;}
const finalQuest=()=>quest(Q.secrets), finalAlignmentAvailable=()=>finalQuest()?.status==='completed'&&ensureState()?.alignment==='independent';
function chooseAlignment(c){const s=ensureState();if(!s||s.alignment!=='independent')return false;if(c==='crown_loyalist'){s.alignment=c;record('alignment:loyal',{confidence:20},'stood with Seraphine as royal power hardened');rep('silverhart_kingdom',10);if(['ruthless','hard_crown'].includes(posture(s)))rep('ironbond_company',-10);root.seraphineRoyalAgent=true;return true;}if(c==='crown_reformer'){s.alignment=c;record('alignment:reformer',{confidence:14,restraint:4},'remained close to the Crown while defending restraints');rep('silverhart_kingdom',7);return true;}if(c==='crown_opponent'){s.alignment=c;record('alignment:opponent',{confidence:-28},'openly opposed Seraphine’s direction');rep('silverhart_kingdom',-10,15);return true;}if(c==='ironbond_counterweight'){s.alignment=c;record('alignment:counterweight',{confidence:-38,centralisation:2},'decided Ironbond was a necessary counterweight to royal power');rep('ironbond_company',18,20);ironPower(10);if(!root.ironbondArc?.playerSide&&root.setIronbondArcSide)root.setIronbondArcSide('ironbond');root.seraphineIronbondCounterweight=true;return true;}return false;}
function openAlignment(npc={name:QUEEN}){const s=ensureState();if(!s||finalQuest()?.status!=='completed')return false;if(s.alignment!=='independent'){root.showDialogue?.(npc,`${postureText(s)}\n\n${confidenceText(s)}`,[{label:'Understood.',action:()=>{}}]);return true;}const hard=['ruthless','hard_crown'].includes(posture(s)),o=[];if(hard){o.push({label:'“You did what weaker rulers would not. I’m with you.”',action:()=>{chooseAlignment('crown_loyalist');root.showDialogue?.(npc,'Seraphine nods. “Good. I need people who understand the cost and still do not flinch from it.”',[{label:'“Then give me work worth doing.”',action:()=>{}}]);}},{label:'“This has gone too far. I won’t help make emergency rule permanent.”',action:()=>{chooseAlignment('crown_opponent');root.showDialogue?.(npc,'The Queen goes still. “Then oppose me openly. I respect that more than loyalty performed in public and withdrawn in private.”',[{label:'“I intend to.”',action:()=>{}}]);}},{label:'“Ironbond may be greedy, but it may be the only power you cannot simply command.”',action:()=>{chooseAlignment('ironbond_counterweight');root.showDialogue?.(npc,'Seraphine’s voice cools. “Preserve a private power because you fear public power more. Petra Voss will be delighted. I am not.”',[{label:'“I didn’t expect you to be.”',action:()=>{}}]);}});}else{o.push({label:'“A Crown strong enough to accept limits is one I can stand beside.”',action:()=>{chooseAlignment('crown_reformer');root.showDialogue?.(npc,'Seraphine smiles tiredly. “Then remind me a limit is not the same as a weakness, especially when I least want to hear it.”',[{label:'“I can do that.”',action:()=>{}}]);}},{label:'“I’ll serve the kingdom, but I won’t become part of the court.”',action:()=>{s.alignment='independent_ally';record('alignment:independent',{confidence:5},'remained an independent ally');}});}o.push({label:'“I haven’t decided where I stand.”',action:()=>{}});root.showDialogue?.(npc,`${postureText(s)}\n\nSeraphine meets your eyes. “You have had more influence on this Crown than most councillors. I would rather know what that has made us to each other.”`,o);return true;}
function arcLabel(){const a=activeQuest();if(a)return`About ${a.title}…`;if(canStart(Q.company))return'There’s the question of Ironbond’s leverage over the Crown.';if(canStart(Q.border))return'About the border powers you were considering…';if(canStart(Q.secrets))return'You said the Crown needed a rule for its secrets.';return null;}
function decorateQueenOptions(npc,options){if(!Array.isArray(options)||root.isPlayerGreenskin?.()&&!root.goblinVouchedByMarta)return options;syncExistingConsequences();const o=[...options],labels=new Set(o.map(x=>String(x?.label||''))),l=arcLabel(),s=ensureState();if(l&&!labels.has(l))o.push({label:l,__seraphineArc:true,action:()=>openQuestHub(npc)});if(s?.history?.length&&!labels.has('How do you mean to rule through all this?'))o.push({label:'How do you mean to rule through all this?',__seraphineArc:true,action:()=>root.showDialogue?.(npc,`${postureText(s)}\n\n${confidenceText(s)}`,[{label:'“That answers me.”',action:()=>{}}])});if(finalAlignmentAvailable())o.push({label:'“Where does this leave us, Your Majesty?”',__seraphineArc:true,action:()=>openAlignment(npc)});else if(finalQuest()?.status==='completed'&&s?.alignment!=='independent')o.push({label:'“Where do we stand now?”',__seraphineArc:true,action:()=>openAlignment(npc)});return o;}
function counselOption(key,npc,options){const q=activeQuest(),s=CH[q?.id],c=COUNSEL[key];if(!q||!s||!c||!s.consult.includes(key)||q.consultations?.[key]||!Array.isArray(options))return options;const e={label:c.label,__seraphineArc:true,action:()=>consult(key,npc)};if(options.some(o=>o?.label===e.label))return options;const o=[...options],i=o.findIndex(x=>/nothing|never mind|leave|goodbye|later|passing through/i.test(String(x?.label||'')));if(i>=0)o.splice(i,0,e);else o.push(e);return o;}
function chainHas(fn,flag){for(let i=0;i<30&&typeof fn==='function';i++,fn=fn.__previous||fn.__baseShowDialogue||fn.__base)if(fn[flag])return true;return false;}
function hook(id,decorate){const t=root.npcDialogueTrees,orig=t?.[id];if(typeof orig!=='function'||chainHas(orig,'__seraphineArcAware'))return false;const w=function(npc){syncExistingConsequences();const base=root.showDialogue;if(typeof base!=='function')return orig.apply(this,arguments);let first=true;root.showDialogue=function(speaker,text,options){if(first&&Array.isArray(options)){first=false;return base.call(this,speaker,text,decorate(npc||speaker,options));}return base.apply(this,arguments);};try{return orig.apply(this,arguments);}finally{root.showDialogue=base;}};w.__seraphineArcAware=true;w.__previous=orig;t[id]=w;return true;}
function refresh(){syncExistingConsequences();if(!root.npcDialogueTrees)return false;hook('silverhart_queen',decorateQueenOptions);for(const [id,key]of Object.entries({palace_chancellor:'chancellor',reddale_guildmaster:'petra',northwatch_commander:'hart',elder_marta:'marta',royal_wizard:'thessaly',high_cleric:'adelram'}))hook(id,(npc,o)=>counselOption(key,npc,o));return true;}
const api={build:BUILD,questIds:Q,chapterDelay:DELAY,ensureState,getState:ensureState,record,posture,postureText,confidenceText,syncExistingConsequences,canStart,ensureQuest,readyToResolve:ready,activeQuest,markConsultation,consult,autonomousOutcome,completeQuest,openQuestHub,chooseAlignment,openAlignment,finalAlignmentAvailable,decorateQueenOptions,refresh};
root.seraphineArc=api;root.SERAPHINE_ARC_BUILD=BUILD;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(typeof document!=='undefined'){refresh();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',refresh,{once:true});setInterval(refresh,1250);}
})();
