// Shield appearance bootstrap. Physical identity is loaded before the renderer module.
(()=>{
'use strict';
const BUILD=window.PRESENTATION_BUILD||'20260930-equipment-instance-v2';
function load(src,done){if(document.querySelector(`script[src^="${src}"]`)){done?.();return;}const s=document.createElement('script');s.src=`${src}?build=${encodeURIComponent(BUILD)}`;s.onload=()=>done?.();document.head.appendChild(s);}
function start(){load('equipmentIdentity.js',()=>load('equipmentInstanceBridge.js',()=>load('shieldInventoryInstances.js',()=>load('factionEquipmentAppearance.js',install))));}
function install(){
 const cache=new WeakMap();let activeEntity=null,clearQueued=false,installed=false;const extra={kite:null};
 const baseId=v=>window.getEquipmentBaseId?.(v)||(typeof v==='string'?v:null);
 function patch(){if(!window.items)return false;if(items.wooden_shield&&!items.wooden_shield.shieldVisual)items.wooden_shield.shieldVisual={shape:'round',material:'wood',scale:.73};if(items.bulwark_shield&&!items.bulwark_shield.shieldVisual)items.bulwark_shield.shieldVisual={shape:'kite',material:'metal',scale:.82};return true;}
 const defaults=id=>({pattern:'solid',primary:{hue:215,saturation:68,value:58},secondary:{hue:42,saturation:78,value:72},paintOpacity:items?.[id]?.shieldVisual?.material==='metal'?.62:.72});
 function held(e,id){for(const slot of ['offhand','weapon']){const direct=e?.equipped?.[slot],physical=e?.equippedInstances?.[slot];if(physical&&baseId(physical)===id)return physical;if(baseId(direct)===id&&window.equipmentIdentity?.isInstance(direct))return direct;}return null;}
 function getAppearance(e,id){return held(e,id)?.appearance?.shield||defaults(id);}function setAppearance(e,id,next={}){const inst=held(e,id);if(!inst)return false;const prev=getAppearance(e,id),colour=(b,n={})=>({hue:Number(n.hue??b.hue),saturation:Number(n.saturation??b.saturation),value:Number(n.value??b.value)});inst.appearance=inst.appearance||{};inst.appearance.shield={pattern:['solid','per_pale','per_fess','quarterly'].includes(next.pattern)?next.pattern:prev.pattern,primary:colour(prev.primary,next.primary),secondary:colour(prev.secondary,next.secondary),paintOpacity:Math.max(0,Math.min(1,Number(next.paintOpacity??prev.paintOpacity)))};redraw();return true;}
 function rgb(h,s,v){h=((h%360)+360)%360;s=Math.max(0,Math.min(1,s/100));v=Math.max(0,Math.min(1,v/100));const c=v*s,x=c*(1-Math.abs((h/60)%2-1)),m=v-c;let a;if(h<60)a=[c,x,0];else if(h<120)a=[x,c,0];else if(h<180)a=[0,c,x];else if(h<240)a=[0,x,c];else if(h<300)a=[x,0,c];else a=[c,0,x];return a.map(n=>Math.round((n+m)*255));}const css=c=>`rgb(${rgb(c.hue,c.saturation,c.value).join(',')})`;
 function paint(ctx,w,h,a){ctx.fillStyle=css(a.primary);ctx.fillRect(0,0,w,h);if(a.pattern==='solid')return;ctx.fillStyle=css(a.secondary);if(a.pattern==='per_pale')ctx.fillRect(w/2,0,w/2,h);else if(a.pattern==='per_fess')ctx.fillRect(0,h/2,w,h/2);else if(a.pattern==='quarterly'){ctx.fillRect(w/2,0,w/2,h/2);ctx.fillRect(0,h/2,w/2,h/2);}}
 function compose(e,id,image){const inst=held(e,id),a=inst?.appearance?.shield;if(!a||!image)return image;const w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;if(!w||!h)return image;const key=[inst.instanceId,a.pattern,a.primary.hue,a.primary.saturation,a.primary.value,a.secondary.hue,a.secondary.saturation,a.secondary.value,a.paintOpacity].join('|');let per=cache.get(image);if(!per){per=new Map();cache.set(image,per);}if(per.has(key))return per.get(key);const out=document.createElement('canvas'),ctx=out.getContext('2d');out.width=w;out.height=h;ctx.drawImage(image,0,0,w,h);ctx.save();ctx.globalCompositeOperation='source-atop';ctx.globalAlpha=a.paintOpacity;ctx.globalCompositeOperation='multiply';paint(ctx,w,h,a);ctx.restore();ctx.save();ctx.globalCompositeOperation='source-atop';ctx.globalAlpha=.28;ctx.drawImage(image,0,0,w,h);ctx.restore();per.set(key,out);return out;}
 function spec(e){for(const slot of ['offhand','weapon']){const direct=e?.equipped?.[slot],physical=e?.equippedInstances?.[slot],id=baseId(physical||direct);if(id&&items?.[id]?.type==='shield')return{id,held:physical||direct,visual:items[id].shieldVisual||{shape:'round',material:'wood',scale:.73}};}return null;}function note(e){activeEntity=e;if(!clearQueued){clearQueued=true;queueMicrotask(()=>{activeEntity=null;clearQueued=false;});}}function source(raw){const s=spec(activeEntity);if(!s)return raw;const img=s.visual.shape==='kite'&&extra.kite?.complete&&extra.kite.naturalWidth?extra.kite:raw;return compose(activeEntity,s.id,img);}function redraw(){window.drawMap?.();window.renderEntities?.();window.refreshDirectionalTurnPortraits?.();}
 function wire(){patch();const v=window.gameVisuals;if(!v?.shield)return false;if(!extra.kite){extra.kite=new Image();extra.kite.addEventListener('load',redraw);extra.kite.src=`images/kiteshield.png?build=${encodeURIComponent(BUILD)}`;}if(!installed){let raw=v.shield;Object.defineProperty(v,'shield',{configurable:true,enumerable:true,get(){return source(raw);},set(n){raw=n;}});installed=true;}const sys=window.equipmentAppearanceSystem;if(sys&&!sys.__shieldHooked){const old=sys.isSlotVisible;sys.isSlotVisible=function(e,slot){if(slot==='offhand'||slot==='weapon')note(e);return old.call(this,e,slot);};sys.__shieldHooked=true;}return installed&&!!sys;}
 window.shieldAppearanceSystem={build:BUILD,patterns:['solid','per_pale','per_fess','quarterly'],getAppearance,setAppearance,compose,shieldSpec:spec,redraw,noteEntity:note};const timer=setInterval(()=>{if(wire())clearInterval(timer);},50);wire();
}
start();
})();
