// weaponReadiness.js - equipped (hands), readied (body), stored (shared inventory)
(()=>{'use strict';
const BODY=['leftHip','rightHip','back'];
const RIG={human_female:[1.60,1.92,-.16],human_male:[1.70,2.06,-.17],elf_female:[1.60,1.92,-.16],elf_male:[2,2.4,-.20],dwarf_female:[1.6,1.92,-.07],dwarf_male:[1.6,1.92,-.07],goblin_female:[1.45,1.7,-.12],goblin_male:[1.5,1.75,-.12],orc_female:[1.85,2.05,-.15],orc_male:[1.9,2.1,-.15]};
const base=x=>window.getEquipmentBaseId?.(x)||(typeof x==='string'?x:x?.baseId||x?.itemId||x?.id)||null;
function kind(x){const id=base(x),d=id&&window.items?.[id];if(!id||d?.type!=='weapon')return null;const s=(id+' '+(d.name||'')).toLowerCase();if(s.includes('dagger'))return'dagger';if(s.includes('sword')||id==='starforged_blade')return'sword';if(s.includes('axe')&&!s.includes('pickaxe'))return'axe';if(s.includes('bow'))return'bow';return null;}
function ensure(c){if(!c)return{leftHip:null,rightHip:null,back:null,extraDaggers:[]};let r=c.weaponReadiness;if(!r||typeof r!=='object'||Array.isArray(r))r=c.weaponReadiness={leftHip:null,rightHip:null,back:null,extraDaggers:[]};for(const s of BODY)if(!(s in r)||r[s]&&!kind(r[s]))r[s]=null;if(!Array.isArray(r.extraDaggers))r.extraDaggers=[];r.extraDaggers=r.extraDaggers.filter(x=>kind(x)==='dagger');return r;}
function assigns(c){const r=ensure(c),a=[];for(const s of BODY)if(r[s])a.push({location:s,itemId:base(r[s]),kind:kind(r[s])});r.extraDaggers.forEach((x,i)=>a.push({location:`dagger:${i}`,itemId:base(x),kind:'dagger'}));return a;}
function active(c){const e=c?.equipped||{};return[base(e.weapon),base(e.offhand)].filter(id=>id&&window.items?.[id]?.type==='weapon');}
const count=(arr,id)=>arr.filter(x=>(typeof x==='string'?x:x.itemId)===id).length;
const party=()=>Array.isArray(window.party)?window.party.filter(Boolean):[];
function owned(id){id=base(id);return(window.partyInventory||window.player?.inventory||[]).reduce((n,x)=>n+(base(x)===id),0);}
function assigned(c,id){return count(assigns(c),base(id));}
function activeCount(c,id){return count(active(c),base(id));}
function committed(id){id=base(id);return party().reduce((n,c)=>n+Math.max(assigned(c,id),activeCount(c,id)),0);}
const stored=id=>Math.max(0,owned(id)-committed(id));
const label=id=>window.items?.[base(id)]?.name||base(id)||'Weapon';
function sync(c){if(!c)return;const e=(window.entities||[]).find(x=>x?.name===c.name&&x.side==='player');if(e&&e!==c)e.weaponReadiness=ensure(c);}
function msg(s){window.showMessage?window.showMessage(s):console.info(s);}
function place(c,id,{evict=false,free=true}={}){id=base(id);const k=kind(id),r=ensure(c);if(!k)return{ok:false,reason:'That weapon has no body carry point yet.'};if(free&&stored(id)<=0)return{ok:false,reason:'No uncommitted copy is available in shared storage.'};if(k==='axe'||k==='bow'){if(!r.back||evict){const old=r.back;r.back=id;sync(c);return{ok:true,location:'back',old};}return{ok:false,reason:`${label(r.back)} already occupies the back position.`};}const order=k==='dagger'?['rightHip','leftHip']:['leftHip','rightHip'];for(const s of order)if(!r[s]){r[s]=id;sync(c);return{ok:true,location:s};}if(k==='dagger'){r.extraDaggers.push(id);sync(c);return{ok:true,location:`dagger:${r.extraDaggers.length-1}`};}if(evict){const s=order[0],old=r[s];r[s]=id;sync(c);return{ok:true,location:s,old};}return{ok:false,reason:'Both hip positions are occupied.'};}
function ensureEquipped(c){if(!c)return;const need={};active(c).filter(kind).forEach(id=>need[id]=(need[id]||0)+1);for(const[id,n]of Object.entries(need))while(assigned(c,id)<n){if(!place(c,id,{evict:true,free:false}).ok)break;}sync(c);}
function ready(c,id){const r=place(c,id);if(!r.ok){msg(`Cannot ready ${label(id)}: ${r.reason}`);return false;}msg(`${label(id)} readied.`);refresh();return true;}
function unready(c,loc){const r=ensure(c);let id=BODY.includes(loc)?r[loc]:r.extraDaggers[+loc.split(':')[1]];if(!id)return false;if(assigned(c,id)<=activeCount(c,id)){msg(`${label(id)} is currently in hand, so its carry point stays reserved.`);return false;}if(BODY.includes(loc))r[loc]=null;else r.extraDaggers.splice(+loc.split(':')[1],1);sync(c);msg(`${label(id)} moved to stored party inventory.`);refresh();return true;}
function projected(c,id,off){id=base(id);const cur=base(off?c?.equipped?.offhand:c?.equipped?.weapon);return activeCount(c,id)+(cur===id?0:1);}
function combatReady(c,id,off=false){id=base(id);const cur=base(off?c?.equipped?.offhand:c?.equipped?.weapon);return cur===id||assigned(c,id)>=projected(c,id,off);}
function canTake(c,id,off=false){id=base(id);const cur=base(off?c?.equipped?.offhand:c?.equipped?.weapon);return cur===id||assigned(c,id)>=projected(c,id,off)||stored(id)>0;}
function refresh(){try{window.syncPlayerEntity?.();window.renderEntities?.();}catch(_){}if(document.getElementById('inventory-modal')?.style.display==='block')setTimeout(()=>window.showInventoryScreen?.(),0);}
function installEquip(){const f=window.equipItem;if(typeof f!=='function')return false;if(f.__weaponReadiness)return true;const w=function(id,off=false){const c=window.player,b=base(id),d=b&&window.items?.[b];if(!c||d?.type!=='weapon')return f.apply(this,arguments);if(window.isInCombat&&!combatReady(c,b,off)){msg(`${label(b)} is stored, not readied. You cannot swap to it during combat.`);return false;}if(!window.isInCombat&&!canTake(c,b,off)){msg(`${label(b)} is committed to another party member. Unready it there first.`);return false;}const before=[base(c.equipped?.weapon),base(c.equipped?.offhand)];const out=f.apply(this,arguments),after=[base(c.equipped?.weapon),base(c.equipped?.offhand)];if(!window.isInCombat&&(before[0]!==after[0]||before[1]!==after[1]||after.includes(b)))ensureEquipped(c);return out;};w.__weaponReadiness=true;w.__unwrappedEquipItem=f;window.equipItem=w;return true;}
function activeLocs(c){const n={};active(c).forEach(id=>n[id]=(n[id]||0)+1);const set=new Set;for(const a of assigns(c))if(n[a.itemId]>0){set.add(a.location);n[a.itemId]--;}return set;}
const locName=l=>l==='leftHip'?'Left hip':l==='rightHip'?'Right hip':l==='back'?'Back':'Small sheath';
function panel(){const c=window.player;if(!c)return null;ensureEquipped(c);const live=activeLocs(c),p=document.createElement('section');p.dataset.weaponReadinessPanel='true';p.style.cssText='border:1px solid #59636b;border-radius:6px;padding:9px;margin:0 0 12px;background:#24292d';p.innerHTML='<strong>Readied weapons</strong><div style="font-size:.8em;color:#aaa">In hand or attached to your body = reachable in combat. Everything else is stored with party gear.</div>';for(const a of assigns(c)){const row=document.createElement('div'),on=live.has(a.location);row.style.cssText='display:flex;justify-content:space-between;gap:8px;margin-top:5px;padding:4px;background:#30363b';row.innerHTML=`<span>${locName(a.location)}: ${label(a.itemId)}${on?' — in hand':''}</span>`;const b=document.createElement('button');b.textContent=on?'In hand':'Store';b.disabled=on;b.style.width='auto';if(!on)b.onclick=()=>unready(c,a.location);row.appendChild(b);p.appendChild(row);}const ids=[...new Set((window.partyInventory||c.inventory||[]).map(base).filter(Boolean))].filter(id=>kind(id)&&stored(id)>0);if(ids.length){const h=document.createElement('div');h.textContent='Stored but ready-compatible:';h.style.cssText='margin-top:8px;font-size:.82em;color:#bbb';p.appendChild(h);const box=document.createElement('div');box.style.cssText='display:flex;flex-wrap:wrap;gap:5px;margin-top:5px';ids.forEach(id=>{const b=document.createElement('button');b.textContent=`Ready ${label(id)}`;b.style.width='auto';b.onclick=()=>ready(c,id);box.appendChild(b);});p.appendChild(box);}const note=document.createElement('div');note.style.cssText='font-size:.76em;color:#888;margin-top:7px';note.textContent='Swords use a hip; bows and axes use the back. Daggers use a hip first, but spare daggers can always fit in another small sheath. Spears, clubs and tools have no alternate carry point yet.';p.appendChild(note);return p;}
function installUI(){const f=window.showInventoryScreen;if(typeof f!=='function'||!f.__slotEquipmentUI)return false;if(f.__weaponReadiness)return true;const w=function(...a){const x=f.apply(this,a),host=document.getElementById('inventory-content');if(host&&!host.querySelector('[data-weapon-readiness-panel]')){const p=panel();if(p)host.prepend(p);}return x;};w.__slotEquipmentUI=true;w.__weaponReadiness=true;w.__unwrappedInventoryUI=f;window.showInventoryScreen=w;return true;}
function bounds(e,x,y,z=1,fly=0){const q=RIG[e?.race&&e?.gender?`${e.race}_${e.gender}`:''];if(!q)return null;const h=window.hexSize||1,w=q[0]*h*z,hh=q[1]*h*z,top=y-w/2+q[2]*h*z+fly,vw=hh*.48;return{left:x-vw/2,top,width:vw,height:hh};}
function alternatePlan(e){const n={};active(e).forEach(id=>n[id]=(n[id]||0)+1);const out=[];let bi=0;for(const a of assigns(e)){if(n[a.itemId]>0){n[a.itemId]--;continue;}if(a.location.startsWith('dagger:'))continue;if(a.location==='back')out.push({itemId:a.itemId,kind:a.kind,placement:'back',hip:null,backIndex:bi++});else out.push({itemId:a.itemId,kind:a.kind,placement:'hip',hip:a.location==='leftHip'?'left':'right'});}return out;}
function installRender(){const f=window.drawHumanoidCharacter,c=window.realtimeWeaponSheathing;if(typeof f!=='function'||!f.__realtimeSheathedWeaponPresentation||!c?.drawLayer||!c?.drawBackLayer)return false;if(f.__weaponReadiness)return true;const w=function(ctx,e,x,y,z,fly){const p=alternatePlan(e),face=['up','down','left','right'].includes(e?.facing)?e.facing:'down',b=bounds(e,x,y,z,fly);if(p.length&&face!=='up'&&b)c.drawBackLayer(ctx,e,b,p);const ok=f.apply(this,arguments);if(ok&&p.length){const rb=window.__humanoidRendererLastDraw?.entity===e?window.__humanoidRendererLastDraw.bounds:b;if(face==='up'&&rb)c.drawBackLayer(ctx,e,rb,p);c.drawLayer(ctx,e,p);}return ok;};w.__realtimeSheathedWeaponPresentation=true;w.__weaponReadiness=true;w.__underlyingReadinessDraw=f;window.drawHumanoidCharacter=w;return true;}
function settle(){party().forEach(c=>{ensure(c);ensureEquipped(c);sync(c);});installEquip();installUI();installRender();}
const timer=setInterval(settle,100);setTimeout(()=>clearInterval(timer),15000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',settle,{once:true});else settle();window.addEventListener('load',()=>{settle();setTimeout(settle,250);setTimeout(settle,1000);},{once:true});
window.weaponReadinessSystem={kind,ensure,assignments:assigns,assignedCount:assigned,activeCount,ownedCount:owned,committedCount:committed,storedCount:stored,ready,unreadyAt:unready,canEquipInCombat:combatReady,ensureEquipped,alternateVisualPlan:alternatePlan,settle};
})();
