// tests/save-diff-and-animation.spec.js
// Two related efficiency/scalability fixes, both in service of a world
// that's about to get much bigger:
//
// 1. Campaign 2's world is one fixed, deterministic layout (regenerated by
//    setupVillageScene() every time). Saves used to store the whole
//    overrideTerrain/tileObjects dicts; now they only store what differs
//    from that regenerated baseline (see persistence.js's diffAgainstBaseline
//    and loadGame's baseline-reset-then-merge).
// 2. A generic animated-tile mechanism (hexMap.js's registerAnimatedTile) so
//    future multi-frame terrain (animated water, etc.) can be added without
//    paying per-hex animation cost — one shared clock, cached per (terrain,
//    frame, zoom).
const { test, expect } = require('@playwright/test');
const { createCharacter } = require('./helpers');

test.describe('Campaign 2 save/load: diff against the deterministic baseline', () => {
    test.beforeEach(async ({ page }) => {
        await createCharacter(page);
    });

    test('saveGame only stores terrain/tileObjects entries that differ from the world-gen baseline', async ({ page }) => {
        const result = await page.evaluate(() => {
            const overrideCount = Object.keys(window.overrideTerrain).length;
            const baselineCount = Object.keys(window._campaign2TerrainBaseline || {}).length;
            window.toggleDoor(0, 4); // one player-caused change
            window.saveGame('diffcount_test');
            const saved = JSON.parse(localStorage.getItem('rpg_save_diffcount_test'));
            localStorage.removeItem('rpg_save_diffcount_test');
            return {
                overrideCount, baselineCount,
                savedTerrainCount: Object.keys(saved.overrideTerrain).length,
                savedTileObjectsCount: Object.keys(saved.tileObjects).length,
            };
        });
        expect(result.baselineCount).toBeGreaterThan(1000); // the real village+roads+etc footprint
        expect(result.overrideCount).toBe(result.baselineCount); // nothing diverged yet except the one toggle below
        expect(result.savedTerrainCount).toBe(1); // just the toggled door hex
        expect(result.savedTileObjectsCount).toBe(1);
    });

    test('loading a save resets to baseline first, so a stale change from the current session does not leak into the loaded save', async ({ page }) => {
        const result = await page.evaluate(() => {
            const baselineAt05 = window._campaign2TerrainBaseline['0,5']?.name;

            window.toggleDoor(0, 4); // change #1, present in the save
            window.saveGame('leak_test');
            window.setTerrainAt(0, 5, 'Water'); // change #2, made AFTER saving — must not survive the load below
            window.loadGame('leak_test');
            localStorage.removeItem('rpg_save_leak_test');
            return {
                door4: window.getTerrainAt(0, 4).name, // should be open (saved state)
                door5: window.getTerrainAt(0, 5).name, // should be back to whatever the baseline actually is, not Water
                baselineAt05,
            };
        });
        expect(result.door4).toBe('Wood Floor');
        expect(result.door5).toBe(result.baselineAt05);
        expect(result.door5).not.toBe('Water');
    });

    test('a fresh-process load regenerates the world without replaying the scripted intro (Wren banter, tavern shakedown timer)', async ({ page }) => {
        await page.evaluate(() => {
            window.hollowmereEventFired = true; // simulate having played well past the intro already
            window.toggleDoor(0, 4);
            window.saveGame('freshload_test');
        });

        await page.goto('/');
        await page.waitForSelector('#race-select', { state: 'visible' });

        const result = await page.evaluate(async () => {
            const ambientCalls = [];
            const origTrigger = window.triggerAmbientDialogue;
            window.triggerAmbientDialogue = (key) => { ambientCalls.push(key); return origTrigger(key); };
            let shakedownCalled = false;
            const origShakedown = window.startHollowmereShakedown;
            window.startHollowmereShakedown = (...a) => { shakedownCalled = true; return origShakedown(...a); };

            window.loadGame('freshload_test');
            await new Promise(r => setTimeout(r, 2500)); // long enough for the old unconditional 2s/8s timers

            return {
                ambientCalls, shakedownCalled,
                doorTerrain: window.getTerrainAt(0, 4).name,
                hollowmereEventFired: window.hollowmereEventFired,
                baselineExists: !!window._campaign2TerrainBaseline,
            };
        });
        await page.evaluate(() => localStorage.removeItem('rpg_save_freshload_test'));

        expect(result.baselineExists).toBe(true);
        expect(result.doorTerrain).toBe('Wood Floor');
        expect(result.hollowmereEventFired).toBe(true);
        expect(result.ambientCalls).not.toContain('wren_intro');
        expect(result.shakedownCalled).toBe(false);
    });
});

test.describe('SIMPLE_PERSISTED_FIELDS/PRESENT_ONLY_PERSISTED_FIELDS round-trip', () => {
    test.beforeEach(async ({ page }) => {
        await createCharacter(page);
    });

    // Guards against exactly the bug this list was built to prevent: a new
    // window.* flag added to a feature but never wired into persistence.js,
    // so it silently resets on save/load. Setting each field to a
    // non-default value, saving, mutating it again, then loading should
    // always bring back the *saved* value, not the post-save mutation.
    test('every SIMPLE_PERSISTED_FIELDS entry survives a save/load cycle, including the homestead and tavern-brawl flags', async ({ page }) => {
        const result = await page.evaluate(() => {
            window.campaign2PlayerFieldBought = true;
            window.campaign2PlayerField = { minQ: 1, maxQ: 2, minR: 3, maxR: 4 };
            window.tavernBrawlActive = true;
            window.tavernBrawlTriggered = true;
            window.worldSeconds = 12345;
            window.questLog = [{ id: 'test_quest', status: 'active' }];

            window.saveGame('persist_fields_test');

            // Mutate again post-save — load should override these back to
            // the saved snapshot, not leave them as-is.
            window.campaign2PlayerFieldBought = false;
            window.campaign2PlayerField = null;
            window.tavernBrawlActive = false;
            window.tavernBrawlTriggered = false;
            window.worldSeconds = 0;
            window.questLog = [];

            window.loadGame('persist_fields_test');
            localStorage.removeItem('rpg_save_persist_fields_test');

            return {
                campaign2PlayerFieldBought: window.campaign2PlayerFieldBought,
                campaign2PlayerField: window.campaign2PlayerField,
                tavernBrawlActive: window.tavernBrawlActive,
                tavernBrawlTriggered: window.tavernBrawlTriggered,
                worldSeconds: window.worldSeconds,
                questLog: window.questLog,
            };
        });
        expect(result.campaign2PlayerFieldBought).toBe(true);
        expect(result.campaign2PlayerField).toEqual({ minQ: 1, maxQ: 2, minR: 3, maxR: 4 });
        expect(result.tavernBrawlActive).toBe(true);
        expect(result.tavernBrawlTriggered).toBe(true);
        expect(result.worldSeconds).toBe(12345);
        expect(result.questLog).toEqual([{ id: 'test_quest', status: 'active' }]);
    });

    test('a save with no saveVersion at all (pre-versioning data) still loads, treated as version 0', async ({ page }) => {
        const result = await page.evaluate(() => {
            window.saveGame('legacy_shape_test');
            const key = 'rpg_save_legacy_shape_test';
            const raw = JSON.parse(localStorage.getItem(key));
            delete raw.saveVersion; // simulate a save written before saveVersion existed
            localStorage.setItem(key, JSON.stringify(raw));

            window.loadGame('legacy_shape_test');
            const loadedOk = !!window.player;
            localStorage.removeItem(key);
            return { loadedOk };
        });
        expect(result.loadedOk).toBe(true);
    });

    test('saveGame stamps the current SAVE_VERSION, and loadGame normalizes it back to that on load', async ({ page }) => {
        const result = await page.evaluate(() => {
            window.saveGame('version_test');
            const saved = JSON.parse(localStorage.getItem('rpg_save_version_test'));
            localStorage.removeItem('rpg_save_version_test');
            return { savedVersion: saved.saveVersion };
        });
        expect(result.savedVersion).toBeGreaterThanOrEqual(1);
    });

    test('factions (a PRESENT_ONLY field) is not clobbered back to a fresh default when the save genuinely has a value', async ({ page }) => {
        const result = await page.evaluate(() => {
            window.factions.silverhart_kingdom.standing = 77;
            window.saveGame('present_only_test');
            window.factions.silverhart_kingdom.standing = 0;
            window.loadGame('present_only_test');
            localStorage.removeItem('rpg_save_present_only_test');
            return window.factions.silverhart_kingdom.standing;
        });
        expect(result).toBe(77);
    });
});

test.describe('save quota exhaustion recovery', () => {
    test.beforeEach(async ({ page }) => {
        await createCharacter(page);
    });

    test('freeOldestSaveSlot deletes the oldest save by date and its metadata entry, keeping newer ones', async ({ page }) => {
        const result = await page.evaluate(() => {
            localStorage.setItem('rpg_save_metadata', JSON.stringify([
                { key: 'rpg_save_old_one', name: 'Old One', date: '2020-01-01T00:00:00.000Z' },
                { key: 'rpg_save_newer_one', name: 'Newer One', date: '2024-01-01T00:00:00.000Z' },
            ]));
            localStorage.setItem('rpg_save_old_one', '{}');
            localStorage.setItem('rpg_save_newer_one', '{}');

            const freed = window.freeOldestSaveSlot('rpg_save_unrelated_current_key');

            const metadataAfter = JSON.parse(localStorage.getItem('rpg_save_metadata'));
            const result = {
                freed,
                oldOneGone: localStorage.getItem('rpg_save_old_one') === null,
                newerOneStillThere: localStorage.getItem('rpg_save_newer_one') !== null,
                metadataStillHasNewer: metadataAfter.some(m => m.key === 'rpg_save_newer_one'),
                metadataDroppedOld: !metadataAfter.some(m => m.key === 'rpg_save_old_one'),
            };
            localStorage.removeItem('rpg_save_newer_one');
            localStorage.removeItem('rpg_save_metadata');
            return result;
        });
        expect(result.freed).toBe(true);
        expect(result.oldOneGone).toBe(true);
        expect(result.newerOneStillThere).toBe(true);
        expect(result.metadataStillHasNewer).toBe(true);
        expect(result.metadataDroppedOld).toBe(true);
    });

    test('freeOldestSaveSlot returns false when there is nothing left to free (never deletes the slot being written)', async ({ page }) => {
        const result = await page.evaluate(() => {
            localStorage.setItem('rpg_save_metadata', JSON.stringify([
                { key: 'rpg_save_only_one', name: 'Only One', date: '2024-01-01T00:00:00.000Z' },
            ]));
            const freed = window.freeOldestSaveSlot('rpg_save_only_one'); // the only save IS the one being written
            localStorage.removeItem('rpg_save_metadata');
            return freed;
        });
        expect(result).toBe(false);
    });

    test('saveGame recovers from a simulated QuotaExceededError by freeing an older save and retrying', async ({ page }) => {
        const result = await page.evaluate(() => {
            localStorage.setItem('rpg_save_metadata', JSON.stringify([
                { key: 'rpg_save_ancient_test', name: 'Ancient Test', date: '2019-01-01T00:00:00.000Z' },
            ]));
            localStorage.setItem('rpg_save_ancient_test', '{}');

            const origSetItem = Storage.prototype.setItem;
            let failedOnce = false;
            Storage.prototype.setItem = function (key, value) {
                if (key === 'rpg_save_quota_test' && !failedOnce) {
                    failedOnce = true;
                    const err = new Error('simulated');
                    err.name = 'QuotaExceededError';
                    throw err;
                }
                return origSetItem.call(this, key, value);
            };

            let messageShown = null;
            const origShowMessage = window.showMessage;
            window.showMessage = (msg) => { messageShown = msg; };

            window.saveGame('quota_test');

            Storage.prototype.setItem = origSetItem;
            window.showMessage = origShowMessage;

            const saved = localStorage.getItem('rpg_save_quota_test');
            const ancientStillThere = localStorage.getItem('rpg_save_ancient_test') !== null;
            localStorage.removeItem('rpg_save_quota_test');
            localStorage.removeItem('rpg_save_metadata');
            return { failedOnce, saved: !!saved, ancientStillThere, messageShown };
        });
        expect(result.failedOnce).toBe(true);
        expect(result.saved).toBe(true); // the retry succeeded
        expect(result.ancientStillThere).toBe(false); // freed to make room
        expect(result.messageShown).toContain('freed space');
    });
});

test.describe('animated-tile scaffolding', () => {
    test.beforeEach(async ({ page }) => {
        await createCharacter(page);
    });

    test('registerAnimatedTile cycles through distinct cached frames from a sprite sheet', async ({ page }) => {
        const result = await page.evaluate(async () => {
            // Synthetic 3-frame sprite sheet, one solid color per frame.
            const sheet = document.createElement('canvas');
            sheet.width = 90; sheet.height = 30;
            const sctx = sheet.getContext('2d');
            sctx.fillStyle = 'red'; sctx.fillRect(0, 0, 30, 30);
            sctx.fillStyle = 'green'; sctx.fillRect(30, 0, 30, 30);
            sctx.fillStyle = 'blue'; sctx.fillRect(60, 0, 30, 30);
            const img = new Image();
            await new Promise(res => { img.onload = res; img.src = sheet.toDataURL(); });

            const tile0 = getCachedHexTile('anim_test', img, 40, 0, 3);
            const tile1 = getCachedHexTile('anim_test', img, 40, 1, 3);
            const tile2 = getCachedHexTile('anim_test', img, 40, 2, 3);
            const centerPixel = (t) => Array.from(t.getContext('2d').getImageData(t.width / 2, t.height / 2, 1, 1).data);
            return {
                frame0: centerPixel(tile0), frame1: centerPixel(tile1), frame2: centerPixel(tile2),
                sameFrameIsCached: getCachedHexTile('anim_test', img, 40, 0, 3) === tile0,
            };
        });
        expect(result.frame0).toEqual([255, 0, 0, 255]);
        expect(result.frame1).toEqual([0, 128, 0, 255]);
        expect(result.frame2).toEqual([0, 0, 255, 255]);
        expect(result.sameFrameIsCached).toBe(true);
    });

    test('an unregistered (static) tile behaves exactly as before — one frame, fully opaque', async ({ page }) => {
        const isOpaque = await page.evaluate(() => {
            const t = getCachedHexTile('static_check', window.gameVisuals.wood_floor, 40, 0, 1);
            return t.getContext('2d').getImageData(t.width / 2, t.height / 2, 1, 1).data[3] > 0;
        });
        expect(isOpaque).toBe(true);
    });
});
