// tests/save-diff-and-animation.spec.js
// Two related efficiency/scalability fixes, both in service of a world
// that's about to get much bigger:
//
// 1. Campaign 2's world is one fixed, deterministic layout (regenerated by
//    setupVillageScene() every time). Saves used to store the whole
//    overrideTerrain/tileObjects dicts; now they only store what differs
//    from that regenerated baseline (see persistence.js's diffAgainstBaseline
//    and loadGame's baseline-reset-then-merge).
// 2. A generic animated-tile mechanism (hexMap.js's registerAnimatedTile) so
//    future multi-frame terrain (animated water, etc.) can be added without
//    paying per-hex animation cost — one shared clock, cached per (terrain,
//    frame, zoom).
const { test, expect } = require('@playwright/test');
const { createCharacter } = require('./helpers');

test.describe('Campaign 2 save/load: diff against the deterministic baseline', () => {
    test.beforeEach(async ({ page }) => {
        await createCharacter(page);
    });

    test('saveGame only stores terrain/tileObjects entries that differ from the world-gen baseline', async ({ page }) => {
        const result = await page.evaluate(() => {
            const overrideCount = Object.keys(window.overrideTerrain).length;
            const baselineCount = Object.keys(window._campaign2TerrainBaseline || {}).length;
            window.toggleDoor(0, 4); // one player-caused change
            window.saveGame('diffcount_test');
            const saved = JSON.parse(localStorage.getItem('rpg_save_diffcount_test'));
            localStorage.removeItem('rpg_save_diffcount_test');
            return {
                overrideCount, baselineCount,
                savedTerrainCount: Object.keys(saved.overrideTerrain).length,
                savedTileObjectsCount: Object.keys(saved.tileObjects).length,
            };
        });
        expect(result.baselineCount).toBeGreaterThan(1000); // the real village+roads+etc footprint
        expect(result.overrideCount).toBe(result.baselineCount); // nothing diverged yet except the one toggle below
        expect(result.savedTerrainCount).toBe(1); // just the toggled door hex
        expect(result.savedTileObjectsCount).toBe(1);
    });

    test('loading a save resets to baseline first, so a stale change from the current session does not leak into the loaded save', async ({ page }) => {
        const result = await page.evaluate(() => {
            const baselineAt05 = window._campaign2TerrainBaseline['0,5']?.name;

            window.toggleDoor(0, 4); // change #1, present in the save
            window.saveGame('leak_test');
            window.setTerrainAt(0, 5, 'Water'); // change #2, made AFTER saving — must not survive the load below
            window.loadGame('leak_test');
            localStorage.removeItem('rpg_save_leak_test');
            return {
                door4: window.getTerrainAt(0, 4).name, // should be open (saved state)
                door5: window.getTerrainAt(0, 5).name, // should be back to whatever the baseline actually is, not Water
                baselineAt05,
            };
        });
        expect(result.door4).toBe('Wood Floor');
        expect(result.door5).toBe(result.baselineAt05);
        expect(result.door5).not.toBe('Water');
    });

    test('a fresh-process load regenerates the world without replaying the scripted intro (Wren banter, tavern shakedown timer)', async ({ page }) => {
        await page.evaluate(() => {
            window.hollowmereEventFired = true; // simulate having played well past the intro already
            window.toggleDoor(0, 4);
            window.saveGame('freshload_test');
        });

        await page.goto('/');
        await page.waitForSelector('#race-select', { state: 'visible' });

        const result = await page.evaluate(async () => {
            const ambientCalls = [];
            const origTrigger = window.triggerAmbientDialogue;
            window.triggerAmbientDialogue = (key) => { ambientCalls.push(key); return origTrigger(key); };
            let shakedownCalled = false;
            const origShakedown = window.startHollowmereShakedown;
            window.startHollowmereShakedown = (...a) => { shakedownCalled = true; return origShakedown(...a); };

            window.loadGame('freshload_test');
            await new Promise(r => setTimeout(r, 2500)); // long enough for the old unconditional 2s/8s timers

            return {
                ambientCalls, shakedownCalled,
                doorTerrain: window.getTerrainAt(0, 4).name,
                hollowmereEventFired: window.hollowmereEventFired,
                baselineExists: !!window._campaign2TerrainBaseline,
            };
        });
        await page.evaluate(() => localStorage.removeItem('rpg_save_freshload_test'));

        expect(result.baselineExists).toBe(true);
        expect(result.doorTerrain).toBe('Wood Floor');
        expect(result.hollowmereEventFired).toBe(true);
        expect(result.ambientCalls).not.toContain('wren_intro');
        expect(result.shakedownCalled).toBe(false);
    });
});

test.describe('animated-tile scaffolding', () => {
    test.beforeEach(async ({ page }) => {
        await createCharacter(page);
    });

    test('registerAnimatedTile cycles through distinct cached frames from a sprite sheet', async ({ page }) => {
        const result = await page.evaluate(async () => {
            // Synthetic 3-frame sprite sheet, one solid color per frame.
            const sheet = document.createElement('canvas');
            sheet.width = 90; sheet.height = 30;
            const sctx = sheet.getContext('2d');
            sctx.fillStyle = 'red'; sctx.fillRect(0, 0, 30, 30);
            sctx.fillStyle = 'green'; sctx.fillRect(30, 0, 30, 30);
            sctx.fillStyle = 'blue'; sctx.fillRect(60, 0, 30, 30);
            const img = new Image();
            await new Promise(res => { img.onload = res; img.src = sheet.toDataURL(); });

            const tile0 = getCachedHexTile('anim_test', img, 40, 0, 3);
            const tile1 = getCachedHexTile('anim_test', img, 40, 1, 3);
            const tile2 = getCachedHexTile('anim_test', img, 40, 2, 3);
            const centerPixel = (t) => Array.from(t.getContext('2d').getImageData(t.width / 2, t.height / 2, 1, 1).data);
            return {
                frame0: centerPixel(tile0), frame1: centerPixel(tile1), frame2: centerPixel(tile2),
                sameFrameIsCached: getCachedHexTile('anim_test', img, 40, 0, 3) === tile0,
            };
        });
        expect(result.frame0).toEqual([255, 0, 0, 255]);
        expect(result.frame1).toEqual([0, 128, 0, 255]);
        expect(result.frame2).toEqual([0, 0, 255, 255]);
        expect(result.sameFrameIsCached).toBe(true);
    });

    test('an unregistered (static) tile behaves exactly as before — one frame, fully opaque', async ({ page }) => {
        const isOpaque = await page.evaluate(() => {
            const t = getCachedHexTile('static_check', window.gameVisuals.wood_floor, 40, 0, 1);
            return t.getContext('2d').getImageData(t.width / 2, t.height / 2, 1, 1).data[3] > 0;
        });
        expect(isOpaque).toBe(true);
    });
});
